### ISSUE TITLE
Automated ticket title by submitted form result

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#1]
Ticket title can be automatically generated by result of DeskDirector native form.

E.g.

New user `{0}`/`{1}` need new computer setup
1. What is user's name?
2. What is user's email?

**Comment by Nness** [comment]
This feature won't be resolved in 2018's second quarter and we are not yet sure whether we will add this to third quarter or not. It is definitely on our roadmap though. Please vote if you are interested at this feature.

**Comment by Andrew-Lahikainen** [comment]
We should also consider adding tokens for certain user properties.

For example:

New user `{name}` / `{email}` needs a new computer setup

Some tokens from the top of my head:

`name` `email` `companyName`

That should be enough for most use-cases.

**Comment by djgmog** [comment]
Would it be possible under the current framework to have the option to choose any field or combination of form fields to pull into the summary?

**Comment by Nness** [comment]
Sorry, current development policy is try to avoid debt. Anything we implement or added, we cannot easily remove them.

**Comment by stephenmonk** [comment]
Agreed, having it create meaningful subjects based on the form data or variables would be great.

**Comment by FluidNets-DamianS** [comment]
Although I would like to see this internal to DD this is easily done via Zapier.

**Comment by djgmog** [comment]
DamianS - Can you provide some further insight to your suggestion? Zapier can re-write the ticket summary based on certain fields within the ticket that was submitted by the form?

**Comment by FluidNets-DamianS** [comment]
Yes - we use a form for new user requests.  In that form we collect First Name, Last Name, etc...  When the form is submitted we do a webhook to Zapier.  In turn, Zapier uses a CW action to update the ticket.  In which case we update he summary to be labeled "New User (First) (Last) at (Company)".  We also do some other cool stuff like:
- Ask is a new computer is needed - if so we create a 2nd ticket "Computer Quote Request for (First) (Last)" in which case we set the status of that ticket to "Quote Demand" to trigger CW Sell to notify our sales team.
- We also check CW and if not found create a new contact record for that new user allowing them to now access the helpdesk portal.

**Comment by FluidNets-DamianS** [comment]
.

**Comment by FluidNets-DamianS** [comment]
I forgot to add, once you get the JSON from the DD Form into Zapier it will be very ugly an unusable except for filtering.  You will need to pass the JSON to a CODE action and run either Python or JavaScript to parse the data into usable fields.

**Comment by Nness** [comment]
For people who waiting on this, server side of work is done and functional. You can already use it, the only thing left to do is at portal level to remove ticket summary field.

This is working in progress, just to let everyone know what is happening.

**Comment by djgmog** [comment]
@Nness this is great news! Thank you for the great work. Will this be continued to have similar functionality to how WuFoo forms currently work (selecting specific fields in a form to populate the subject)? Would love to convert all of our forms once the features are matched. Thanks!

**Comment by Nness** [comment]
@djgmog 

It will be more superior than Wufoo's implementation. I will give an example here.

There are several different kind of parameter, system parameter like user name, request type name etc. Or answers from questions.

What wufoo implementation provide is following.
* Completely replace title with xxx
* Append to the end of subject

![2018-12-18_08h10_33](https://user-images.githubusercontent.com/1712143/50109359-6a1dc380-029c-11e9-8a8c-6df7e2a80507.png)

What new form title feature provides:
* Static title
* Information append to the end
* Information prefix at front
* Multiple token or parameters and able to locate any position of title.

**Comment by Aycorn** [comment]
@Nness Did you want to include hiding the "Give your request a title for easy reference" if a dynamic title is setup against this feature request? Or log a new one specifically for this feature?

![image](https://user-images.githubusercontent.com/30588784/53056107-edfb6280-350e-11e9-9529-3d6a2d226375.png)

**Comment by Nness** [comment]
@Aycorn, Don't make new one. This is not yet finish feature. Create issue on issues list and tag Chris into it.

**Comment by Nness** [comment]
I believe portal now has this feature completed. I will close this.
