### ISSUE TITLE
[9098] Deprecate multi-user desktop logins

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#10]
This feature was never publicly released, but is causing a few issues in certain environments. For example: https://github.com/DeskDirector/Issues/issues/5

[Additional access](https://github.com/DeskDirector/UserVoice/issues/7) can be used as a work around if anyone is relying on this feature. Additional access is likely going to get a rework as well. This rework should mean that it will be possible to bring back multi-user logins but with a much superior user experience.

**Comment by chris-ls** [comment]
This was removed in August 2018
