### ISSUE TITLE
Add way to group and filter tickets by board and/or by status (DD Portal)

### ISSUE THREAD

**Issue by bobsquid** [DeskDirector/UserVoice#100]
We use different CW boards for Service/Support tickets, Staging/Deployment tickets and Project issues.  We have had requests from many of the primary contacts at our larger clients (the people who have access to "all tickets") to be able to filter and sort by boards and statuses.  

Filtering by board would allow them to easily see, for one example, how many machines are in the deployment queue (and the status of each), and filtering by status would allow them to see, for one example, how many tickets are waiting for their input.  This isn't as big of an issue with smaller clients or individual users, but for the primary contacts at our larger clients the "all tickets" screen can get very cumbersome.  If this functionality can be extended to the "closed tickets" screen as well it would be even better.

If filtering/grouping is not feasible, another option could be to colour code the statuses and/or boards for easy identification.  This would not be as helpful, but it would be better than nothing.

FYI...There is a similar request for this feature in the TECH software, but not the DD Portal, which is why I've opened this one.

**Comment by TechheadPaulee** [comment]
Filtering by type/sub-type would be nice too.
