### ISSUE TITLE
[10897] Custom View Filters similar to ConnectWise

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#102]
Within ConnectWise, you can set custom views based on logical checking. This is a great feature across all Tech roles as you can display what is relevant and overall reduce ticket clutter.

An example below for "Live Tickets" which excludes any customer waiting statuses:

![image](https://user-images.githubusercontent.com/30588784/43101957-e208fc18-8f1d-11e8-90cd-e3ac59898de9.png)

**Comment by Nness** [comment]
Focus discussion on #44
