### ISSUE TITLE
[10888] Default Board settings on DD Admin

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#103]
I would envision seeing this available in General Configuration > General.

You can currently set a Default Activity Assign Member, in this same section the feature to set a Default Board.

This is mainly for situations where:

- A client has just signed up, and there are no Request Types created.
- The new "Something Else" feature available on the New Request Support System.

Leaving this blank would fall back to the client's PSA settings as the default.

Could implement this as a type field like most sections on DD Admin, or a pre-populated drop down.

![image](https://user-images.githubusercontent.com/30588784/43103448-2fc9a66a-8f22-11e8-9c2d-2254f34f3f46.png)

**Comment by DDAndyChen** [comment]
This is implemented in 18.42.1
