### ISSUE TITLE
[8823, 13696] Ability to print ticket details in portal

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#11]
Print view for ticket detail, so customer can use printer to print it.

**Comment by Aycorn** [comment]
Similar Request: 
Service Ticket #13696 - Ability to print a specific ticket through Desk Director?

**Comment by Andrew-Lahikainen** [comment]
This was shipped a few months ago in the new tickets ui for Portal. This can be switched on in the admin console under Portal > feature preview
