### ISSUE TITLE
[10979] Exclude tickets from Service Board by status.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#113]
Similar concept to what's available under Client Security > Opportunity > Excluded/Included Status.

Having this feature enabled for Tickets visible by clients, where certain statuses will not be displayed on the portal.

Scenario:  Tasks/tickets are assigned to specific companies for tracking purposes but the customer doesn't want the company to be able to see them.

**Comment by Nness** [comment]
Will those tickets ever been closed? Is it auto generated tickets based on certain event?

For company with those tickets, are all of their user able to see all tickets, or this is more of  problem for user who have access to all tickets?

What if tracking is logged into different board that for tracking purposes? Then only move to normal board when end user should see it.

**Comment by Nness** [comment]
Limit by status is not preferred for ConnectWise and it can be easily achieved with Autotask.

Autotask's ticket status is same across board, where ConnectWise have different set of status for different board. If we add such filter, then ConnectWise side will be so complex, both from configure point of view and also from query point of view.

In configure, customer have to go through each board to setup which status should be include, what should be excluded, in query, we have to pass all those information to database. I know some of customer have 500+ CW board status. Imagine such query against database.

**Comment by Nness** [comment]
I am going to decline this request, since no one is interested also this is not user friendly behaviour. If we ever introduce such logic, end user will rather choose email than portal. When they cannot find ticket in portal but they can inside email. This request is not logical.
