### ISSUE TITLE
DD Tech: Broadcast: Creating Company or Product Groups In DD

### ISSUE THREAD

**Issue by FluidNets-DamianS** [DeskDirector/UserVoice#114]
So as an alternative to my earlier request is the ability to create groups in DD and to utilize these for broadcast messages.  Again, as an MSP I have many different services and not all customers use all services.  In addition, if many of our customers use a specific telco vendor I would like to be able to easily select all these companies for a broadcast instead of looking in CW then manually selecting each company.

Also is broadcast accessible via the API?

**Comment by Nness** [comment]
We will revisit broadcast and notifications functionality again.

There are several things that related to your request.
* We are planning on adding tags to different entities. And utilize that for different purpose. It could treat it as `Group`. 
* We will revisit broadcast and notifications at some point, need refactor that. Split broadcast and notifications to it's own.
    * Broadcast is for temporary notification. Which can be removed. e.g. Train got delay, waiting for further notification
    * Notifications as source of history, it is target end user specifically, not group. Notifications cannot be removed, it will only be there for 7 days. e.g. ticket xxx is now closed. 

Notification API is there that you can use, not broadcast API. Broadcast API is TECH specific, if you have TECH cookie you can use it. Broadcast API can use API key. If you need API definition, just send ticket to support, I can answer that there.

**Comment by Aycorn** [comment]
Similar request: Service Ticket #22179 - Dev Idea / Query - Broadcast via groups
@Nness thoughts on this request from 2018 now that Tags are in place?

**Comment by Nness** [comment]
What we can do is, when select companies, allow tag filtering also allow `shift` + `click` to group select. That way can achieve similar thing without change core system. Which that's definitely doable.

**Comment by AirLHull** [comment]
As long as we can easily broadcast messages to specific customers based on a "tag", that is what we are looking for! I would be cool to have a list of "tags" available.

**Comment by AirLHull** [comment]
Is there any updates or further thoughts on this?

**Comment by AirLHull** [comment]
We essentially want to "Tag" companies with specific services (for example grp_365), then if there is an outage with a 365 services, we want to broadcast a message to said group.

**Comment by Nness** [comment]
This has been implemented and planned to be released on 14th of Dec 2020 alongside with email broadcast.
