### ISSUE TITLE
[11006] Hidden chat notification settings if component isn't purchased.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#116]
Having the following options only display if:
1) The Chat component is purchased.
2) The user has Chat permissions enabled.

![image](https://user-images.githubusercontent.com/30588784/43491587-3ce94c58-9579-11e8-9921-c24c1e9a7b74.png)

**Comment by chris-ls** [comment]
This is a bug not a feature request :)
This should be the default behaviour.

Issue created
https://github.com/DeskDirector/Issues/issues/32
