### ISSUE TITLE
[9153, 10213] Flexible menu system

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#12]
Allow top level menu items to be created, reordered, and renamed. This is similar to how the learning centre works, but it will not be scoped to only the learning centre.

**Comment by Nness** [comment]
The other goal of menu system is to move few menu access permissions out of current permissions system and to menu system. 
* ConnectBooster (Invoice)

The filter we will also change from company and contact filter into cascading override system.

We will share more detail in the future.

**Comment by prysmcorp** [comment]
Would it be possible to add a nested version in that sub-menu items could be added to the same parent menu item? E.g. much like how the learning center works now with a hierarchy structure. This would allow grouping of similar categorical or topical items.

**Comment by Andrew-Lahikainen** [comment]
@prysmcorp currently this is not possible, but we do have some ideas on how we might do this in the future. I suggest you open another feature request for that so we can track it separately and others can find it easier.

Just to let you know, you can already try out the new menu system, here's some docs:
https://help.deskdirector.com/category/p45er5j3a2-menu-system

**Comment by Andrew-Lahikainen** [comment]
Released, any further improvements to the menu system should be tracked as separate feature requests.
