### ISSUE TITLE
[11082, 14287] Web Portal color schemes at a company level.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#125]
Currently the first portal installer's color scheme is applied globally:
![image](https://user-images.githubusercontent.com/30588784/43875265-ebb5334e-9be3-11e8-9263-8a8392cb339b.png)

If a client is set up with a specific color scheme, there's no way to apply this at a company level.

Feature request to have this as a granular option that can be applied per company under web branding.

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #14287 - Theme in DeskDirector did not update

**Comment by Andrew-Lahikainen** [comment]
This has been completed. In the new admin console you can select theme on the company profile page.

![image](https://user-images.githubusercontent.com/10571313/63399581-149a4780-c425-11e9-9fd7-28e5d570c8d3.png)
