### ISSUE TITLE
DD Tech: Need to be able to change Autotask URL

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#126]
Currently the Autotask.net url is set to ww2 - this should be a dynamic option, so you can enter your local datacentre option

**Comment by Nness** [comment]
This is already dynamic. Default is ww2, where we use ww2 to figure out where they actually locates. Autotask did provide API for that. The thing is newer Autotask server is not covered by that API, or not yet synced. So the Autotask URL is editable to prevent that happening.

Those new server is also outside of their API document, which we don't have list of. The only way to figure out is customer login to their account and check the URL in browser.

As showing inside image. Server URL is editable but is not required. If didn't fill in, we will try to figure out through Autotask API. If Autotask API cannot figure out we will require enter that URL.

Andy has fixed general config page, so it won't have 500 error page if credential or server URL is wrong.

![2018-08-10_18h06_32](https://user-images.githubusercontent.com/1712143/43941416-2e1df092-9cc8-11e8-9465-9de5dff94078.png)

**Comment by Nness** [comment]
After server 18.43.1. You shouldn't encounter such problem, if not synced, you can go to general config page change server URL.

This is [original issue](https://github.com/DeskDirector/DeskDirector/issues/667).

**Comment by Andrew-Lahikainen** [comment]
@Nness I think this is referring to the links to Autotask from Tech. Tech hard-codes this url client side it doesn't use the API.

This is in development now. I do think this is a bug rather than a feature request. Reopening.

**Comment by Andrew-Lahikainen** [comment]
This has been completed and deployed (1.6.2).
