### ISSUE TITLE
[11177] BrightGauge.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#129]
Mentioned in this article:

https://www.deskdirector.com/brightgauge

Does this functionality have an E.T.A. ?

**Comment by Nness** [comment]
It is already functional inside DD-HUD.

DD-TECH can display web page, the given web page's URL can have token inside, which we replace token with corresponding value. That's how that functionality works.

It is currently not provided in DD-TECH, we are looking at open new tab.

**Comment by Andrew-Lahikainen** [comment]
@Aycorn was this for Portal or Tech?
