### ISSUE TITLE
[11224] Broadcast to Email.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#131]
Scenario: Company has an outage for their terminal server, meaning users are unable to log in or see DD Portal.

A broadcast was sent out that there was an outage, however no users could check since they couldn't log into the environment.

Having an option to email a broadcast, or any other recommended workarounds, for urgent scenarios where DD Portal cannot be accessed.

**Comment by FluidNets-DamianS** [comment]
There should be an option for users to sign up for broadcasts via text, email or both.

**Comment by Aycorn** [comment]
The original request of sending Broadcasts via email is now available: [Getting Started with Broadcasts
](https://help.deskdirector.com/article/jdkd5yrjrd-getting-started-with-broadcasts)

Marking as closed.
