### ISSUE TITLE
[11258] User who never login before don't know how to login.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#133]
End user who has contact exist inside system but never login through DeskDirector before, have hard time to figure out how to login.

**Comment by Nness** [comment]
This is copy of original request.

--------------------------
Scenario: Using the initial DD Portal login page "forgot your password" feature to get new clients to setup their password.

Change/Add the phrasing on this to also include a First Time Logging In? prompt.

![image](https://user-images.githubusercontent.com/30588784/44235930-6c451800-a1ff-11e8-9a91-9cd2fb0b3d8f.png)

**Comment by Nness** [comment]
Just to be clear, we won't implement the way it is described in original request. That will cause more confusion, since reset password doesn't allow to create contact. This can potentially lead people to wrong location.

**Comment by Andrew-Lahikainen** [comment]
It is now clear for users that they have not got a password set. Along with all the other changes of the new sign in page, I think this can be marked as completed.
