### ISSUE TITLE
[11394] Change Priority within DD Tech.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#136]
Similar to how ConnectWise handles changing priority:
![image](https://user-images.githubusercontent.com/30588784/44441583-72812d00-a621-11e8-8839-d7024fda4ce0.png)

Include a method for Techs to update the priority of the ticket, currently this is a static field:
![image](https://user-images.githubusercontent.com/30588784/44441592-7dd45880-a621-11e8-8bfe-03d8c4d2f66f.png)

**Comment by Andrew-Lahikainen** [comment]
Closing as this was implemented a long time ago
