### ISSUE TITLE
Dynamic Fields in Forms

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#14]
Ability to add dynamic data to fields to enhance tickets, i.e. On the Create New User form, the ticket created has "Add new user | <first_name> <last_name>" for the title

**Comment by Lowell-Syncrety** [comment]
Oh, would love this.  I'm converting our WuFoo forms over to DD Forms, love the speed of DD Forms and hopefully can find some actual use for webhooks (hope to see some functional examples as KB articles), but we're losing this feature where we could choose a couple fields in the form to append to the Summary.

My dream would be to have a way to use webhooks to connect into DeskDirector's CWM API connection which would give us tons more flexibility (i.e. customer chooses Specific Due Date and that will pump the date into the ticket's Due Date field), stuff that it seems Zapier and the like can't do.  They just do basic stuff that DeskDirector is already doing, like creating a new ticket, or useless stuff like updating a company address or contact.

**Comment by Andrew-Lahikainen** [comment]
This seems to be the same request as https://github.com/DeskDirector/UserVoice/issues/1

When I read the title of this request, I thought it was going to be something else.

Dynamic fields to me means that you might have dynamically populated form controls. For instance, you might have a select input (dropdown) which is of type `contact`. When the user clicks this, it would display a list of all contacts from their company. Another type could be `priority`.

Can I close this issue? Lowell you can vote on issue #1

**Comment by Nness** [comment]
I will close this. since it's duplicate.

**Comment by Andrew-Lahikainen** [comment]
@PreciseNZ has created an issue for the version I described here https://github.com/DeskDirector/UserVoice/issues/53
