### ISSUE TITLE
[11517, 19584, 24515] Phone Number field in DD Forms.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#142]
The phone number type can ask for a country code and perform phone-number validation.

Currently the "number field" inside dd forms is *not* suitable for phone numbers.
The number field is designed for pure numbers (the UI even provides increment/decrement actions next to it).

A current known workaround for this is to use a Short Text field instead.

**Comment by FluidNets-DamianS** [comment]
Any thoughts on this issue?  Either add a phone number field.  Another option would be to allow changing field types.  Currently I have to delete and re-add new short text field, then update my integrations.

**Comment by cdandrea** [comment]
Sorry guys, I was somewhat surprised to see this as an open issue. I felt a little dumb today when we had a partner ask us to add a proper form validation to the phone number field. I didn't think much of it, recalling that we had validation already in place. But, as pointed out in the OP, it's limited to whole numbers, with masking option, never mind a country code feature. Is this not something that can be implemented?

**Comment by Nness** [comment]
Phone field now has been released. It also has capability to enter more than one phone number. It can recognize country code and can validate any country's phone number.
