### ISSUE TITLE
Chat Beta - ETA to get chat conversation embedded in ticket

### ISSUE THREAD

**Issue by FluidNets-DamianS** [DeskDirector/UserVoice#144]
I heard before this was in "alpha" that the goal was to be able to view the chat in-line with the ticket conversation/thread instead of an attached file.  Wondering what the ETA is?

**Comment by chris-ls** [comment]
Hey Damian,

That functionality is coming as part of a refresh of the ticket details UI.
Work on that is already underway and we are looking to have that out some time in the next 6 weeks.
Most likely there will be a preview version available even earlier which will be toggleable per user, for people to test out.

**Comment by chris-ls** [comment]
I will close this issue since it is not a feature request
