### ISSUE TITLE
DD Tech: Right Pane

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#15]
Currently the right hand pane shows ticket information.  Would be great to be able to see Device Configuration (if available), or other client specific data.  For example, for the DD Support team, we can see their server, ravendb details, license details etc, whereas Lancom could have dynamic links to IT Glue, Labtech etc.

**Comment by Andrew-Lahikainen** [comment]
I've added a separate issue for configurations https://github.com/DeskDirector/UserVoice/issues/34

**Comment by Nness** [comment]
I believe this is more associate with HUD's tabs and company information. We can have those tabs display as links and allow open them in default browser tabs, while company information we can either record at our side or use PSA specific company note field.

**Comment by Andrew-Lahikainen** [comment]
This has been completed (as ticket links).
