### ISSUE TITLE
[11715] Autotask Ticket Category as option in Request Type

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#155]
Ticket Category drop down should be one of choice for request type.

**Comment by Nness** [comment]
There are few more drop down that could potential to be added in.

Service Level Agreement
Monitor Type

**Comment by FluidNets-DamianS** [comment]
These are missing for CW as well

**Comment by Nness** [comment]
@FluidNets-DamianS Which one do you mean? Or What do they called in ConnectWise.

**Comment by FluidNets-DamianS** [comment]
In DDtech we are missing access to agreements.  In addition have access to type, sub-type but not item which is the 3rd tier/classification.

**Comment by Nness** [comment]
ConnectWise is missing Agreement and Sub-Type-Item. Is that correct? We will look into it.

**Comment by FluidNets-DamianS** [comment]
Selecting Agreement is missing as "Item".  Type and SubType are present.

**Comment by Nness** [comment]
Duplicated user voice with #173 

@FluidNets-DamianS  TECH will soon allow change priority, source, item. Also we are working on assign other members to ticket.
