### ISSUE TITLE
TECH allow change Status for ticket (CW)

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#163]
We can't currently use DD Tech even in testing as we need techs to be able to change the Status of a ticket to In Progress or else they can't enter time.  Also they need to change the status to something else once they're done the work (no tickets but the one they're working on right now can be in In Progress status, for example).

**Comment by FluidNets-DamianS** [comment]
You can't select "In Progress" from here:
![image](https://user-images.githubusercontent.com/10325877/46306832-50b18900-c583-11e8-9e70-98c6bcbbb2d5.png)

**Comment by Lowell-Syncrety** [comment]
OK, but that's confusing.  Tech needs to start a timer on this ticket right now, before submitting a note.  Your screenshot shows an active timer.  On a ticket that does not allow time due to being "Scheduled" or whatever, there's no timer.  
If I just change the Submit As field to In Progress, still no timer shows up.

**Comment by FluidNets-DamianS** [comment]
Ah..  ok.  We only prevent time on "Completed/Closed" tickets.  Can you save the note as In Progress then get a working timer?

**Comment by Andrew-Lahikainen** [comment]
We are already planning to change this before the end of the quarter.

Here's a rough prototype you can click through to get an idea of some of the changes relating to tickets:
https://xd.adobe.com/view/86a299a2-31d2-4a57-bf24-7c6cb3049616/

We're separating time entries and notes. We are also removing status from the input and placing it near type and sub type.

These changes should remove much of the confusion around how Tech worked with regards to notes and time. There were too many hidden behaviours which made it hard to use initially.

Let us know what you think.

Also the prototype does not show the timer any more, it just shows the start and end time which can be edited. We will likely put the timer back in, but allow the start and end time to be displayed inline by pressing an "advanced" button on the time entry form.

**Comment by Lowell-Syncrety** [comment]
I think that's an improvement, thanks!

**Comment by Andrew-Lahikainen** [comment]
This is now live by the way

**Comment by Andrew-Lahikainen** [comment]
Closing since this has been live for a long time...
