### ISSUE TITLE
Switch between different contacts based on email

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#165]
Portal user that manages multiple companies able to switch between different contact based on email.

If there are multiple contact with same email, and they are under different company. That contact can potentially switch to other contact.

DeskDirector currently have an **experimental** feature that allow one contact to access multiple companies or different contact. That **experimental** feature have several issues.

* Require manually setup
* It cannot access invoices or quotes
* When log note, it is use ticket's owner as author to create note, that is not correct behaviour.
* List tickets for multiple companies is unexpected and require advanced UI to filter tickets
* User cannot have different permission under different companies.

New approach is to leverage email identity, since all authorization is based around email, so it make sense once verified email, contact can access any contact with that email. It has less overall technical debt, it can also achieve more with less. It can resolve all the issues above.

**Comment by Andrew-Lahikainen** [comment]
Will track here: https://github.com/DeskDirector/UserVoice/issues/258
