### ISSUE TITLE
[11755, 18516] Changing Service Board from DD Tech.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#166]
The current board section is static on DD Tech:

![image](https://user-images.githubusercontent.com/30588784/46388051-893d9800-c726-11e8-83b0-5ce08987c4e2.png)

Feature request to make this an editable field/dropdown.

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #18516 - Desk Director Chat + Other Items

**Comment by Andrew-Lahikainen** [comment]
This has been implemented and shipped
