### ISSUE TITLE
[11862] Sandbox portal for pre-staged testing.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#168]
Often a Desk Director customer will have to make a change to their live environment.

Has there been any thought into a sandbox portal where MSPs can make changes to see changes before they're rolled out?

An example of this might be re-branding a portal, and wanting to get the branding/colors correct before they're pushed to live.

**Comment by Nness** [comment]
For branding/colors they should be able to test through web-client? Setup those branding setting then impersonate one of contact.

**Comment by Andrew-Lahikainen** [comment]
I think this can mostly be accomplished by company level features/branding and impersonation. Will close and wait for specific feature requests relating to this.
