### ISSUE TITLE
[21362] Contact Groups

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#17]
Having to manually add 50-100 people to every request type, learning, etc that they shouldn't have is tiresome when users are only able to utilize certain items.
 
Adding the contacts to a group and then having the groups be the target of the filtering/exceptions would simplify not only the initial configuration but future contact additions. They could be placed in the respective group(s) and would get their respective items.

**Comment by Lowell-Syncrety** [comment]
Adding the ability to organize users by groups (or even eventually companies by groups) is always helpful.

**Comment by Nness** [comment]
I believe permission based request type might be better.

1. Company and Contact can both have tags
2. Request type have setting says only user with specific tag can view it.

e.g.: 

Scenario 1:    
Request type `New Employee` have tag requirement of `HR-Admin`, and it is a global available request type without filter. With tag requirement, only user with `HR-Admin` able to see it.

Scenario 2:
Request type `Need new server setup on AWS` have tag requirement of `AWS-Server` and `Admin`. So only company tags + contact tags have both `AWS-Server` and `Admin` present can view this request type.

For group concept, it is not fit with our software architecture, to maintain the performance and avoid debt, group concept won't be considered.

**Comment by PreciseNZ** [comment]
Further to this, groups could extend the admin function, for example having a 'manager' at a branch that can see all the branch tickets, rather than the entire companies tickets

**Comment by justinDJC** [comment]
Adding to this. a Filter option for Site would be good.

We have a few companies that smaller business units under them. To filter a request type to select Sites of a company would be great.

Groups sounds good too, like 'IT Contacts' . Both have different but similar uses.

**Comment by Nness** [comment]
#538 as different approach

**Comment by Nness** [comment]
#538 has been started. Also adding contacts and companies are very easy with latest request type setting page rewrite. You can filter contact or company by tags then add them by bulk.
