### ISSUE TITLE
Ability to link directly to a request type via URL

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#175]
Would like the ability for URL Linking to a specific form.  Companies can then put links in documentation or their site which sends users to a specific form to be completed.

Two authentication options:
1) Use in conjunction with a global token to auto-login the user and present the form
2) Provide callback on login screen so users are authenticated first, then taken to the form instead of the standard home screen

**Comment by Nness** [comment]
Change title to reflect true meaning. Form is not directly exposed but through request type.

**Comment by bbowersztds** [comment]
Agreed and would love this.

**Comment by Andrew-Lahikainen** [comment]
This was implemented a long time ago: https://help.deskdirector.com/article/rb70qsabfd-portal-deep-linking

Closing issue 👍
