### ISSUE TITLE
[22667] Granular permission access for members

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#176]
Would like the ability to give member limited access within the admin console.  This could be used so they can update client information or permission, but not update the SMTP Settings or Portal Colors etc.

**Comment by Nness** [comment]
Current plan is separate to two different role.
* Master role who can access everything.
* Manager role who can access to portal configurations only. That included following.
    * board permissions
    * feature permissions
    * invoice and quote access permissions
    * forms
    * request types.

**Comment by AirLHull** [comment]
Just to confirm this does include the ability to go into specific end users accounts and be able to edit their permissions? As a Service Desk, managing the users access and request types are the main thing for us.

**Comment by Aycorn** [comment]
Would the "manager" role work for Streamline IT users managing their own company?
Streamline Member A for Company ABC could then access and edit Company ABC's forms and contact permissions.

**Comment by AirLHull** [comment]
At this moment we would want to assign these roles to our internal users first before opening the gates to client, however i like the forward thinking on that idea!

**Comment by Nness** [comment]
For this issue, streamline IT won't be in the consideration. If include it would be became huge amount of work. @Aycorn  you can create a separate user voice.

* Request Type
* Forms
* Menu
* Email template

None of them can be company specific at moment. Even if we introduce the capability that means majority of admin portal need to be redesigned and re-imagined.

**Comment by Aycorn** [comment]
Similar Request: 23852 - Can't access Admin portal as Subcontractor member vs Regular member
