### ISSUE TITLE
Add option to say "I have a token" on Portal login page

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#183]
After requesting a token, would be good to be able to say that I already have a valid token so I can use that.

Use case: I close the page by accident, but the token is still within expiry

**Comment by Andrew-Lahikainen** [comment]
I think this can be closed due to the release of the new universal sign in page. When choosing token login the input to enter the token is immediately visible. It will still trigger another email to be sent, but it will be the same token if it's within the token's expiry time.
