### ISSUE TITLE
[12380] Modify CC list in ticket (CW, TECH)

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#184]
Similar to the functionality within ConnectWise, the ability to add a CC to your ticket:
![image](https://user-images.githubusercontent.com/30588784/47831098-eeeb7580-ddf3-11e8-8207-3ab17f7b8014.png)
![image](https://user-images.githubusercontent.com/30588784/47831105-f874dd80-ddf3-11e8-8fb2-b0c39dba7f40.png)

**Comment by Lowell-Syncrety** [comment]
Yeah; I see the "Ccs" checkbox now but it doesn't allow me to add a new CC email address on the fly which is what a tech needs to do from time to time.

**Comment by dr3dgen** [comment]
@Lowell-Syncrety I agree. This is the most common place that additional contacts are added for us. The fact that we can't see them or add here makes workflow a bit more challenging.

**Comment by Andrew-Lahikainen** [comment]
Do you think Portal users would also like to see/add ticket CCs?

**Comment by dr3dgen** [comment]
From the CW side, they don't see the CCs unless we send communication to all parties via email from the portal. It would probably be beneficial, but could also add additional headache from oversight. (e.g. Users including their managers as a contact for a ticket to try to push higher priority/greater sense of urgency.) It might be better just to give our technicians access. What I also like is if there is an update for the ticket that only needs to go to the specific contact CC in the ticket, you can deselect the ticket owner.

**Comment by FluidNets-DamianS** [comment]
This may need to be set per company or per DD instance.   Ex is that the Connectwise mail handler can be configured as follows:

- Ignore email CC's
- Add CC's to ticket

Definitly a benefit, however if you are CC'ing someone outside the customer or support org there can be security risks so for us better to leave in our control (we dont add CC's via Connectwise mail handler).

**Comment by Lowell-Syncrety** [comment]
When just going to Add Note in a ticket in DD Tech I don't even see the "Send to Contact" and resources options. Could you add these? We would like to send a note without having to make it a time entry.

**Comment by Aycorn** [comment]
Similar: Service Ticket #22187 - Question: Adding a CC to a Ticket
