### ISSUE TITLE
Search functionality on DD Admin Portal

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#19]
Similar to being able to search the Settings section on and Android phone, have a search box embedded at the top of the page where you can search for key words across the Admin Portal.
 
""Search" feature. Similar to my Android phone, when I go into settings I cannot find anything of the settings I want as it moves with each update. However at the top of "Settings" there is a search and I can enter any setting it will appear in a list. An example was I spent 30minutes looking for the reference to OneNote in the console."

**Comment by Nness** [comment]
This should tight to admin console rewrite. I will put this on backlog.

**Comment by Aycorn** [comment]
Closing - admin Portal has since introduced a search capability:

![image](https://github.com/user-attachments/assets/b7869be8-91b2-4ee9-844f-516c516b6ece)
