### ISSUE TITLE
Search field for request type inside portal

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#197]
It would be great to have a search box added to the top of the "Create a New Ticket" page.  Someone could start typing in and it would start filtering down and showing them forms that either had that text in the form or in metadata tags we added for this purpose.

For example, someone typing in "Excel" would see both the "I need an application installed" and "I'm having a software issue" form come up.  Excel might be in a drop-down in the one form, might not exist at all in the second one but we added it as a keyword tag so that form would come up when someone searched for "Excel".

**Comment by FluidNets-DamianS** [comment]
I wouldn't hold my breath unless new menu system can do this.   What we did is wrote things the way client call about them:

Categories:                              Form:
-------------------------------------------------------
I have a problem with...
                                              ... an Application
                                              ... my Computer
                                              ... my Phone
I cannot login to...
                                              ... my Computer
                                              ... my Email
I need to order a...
I need to manage a user...

Then in the APPLICATION form we list different options.  At the root a user could choose either:
Microsoft > Internet Explorer
or
Browser > Internet Explorer

We then can then tag accordingly via the API.

**Comment by Lowell-Syncrety** [comment]
The cool thing about a search box is that now that all the forms are in DD Forms that's all that has to be indexed, plus the metadata tags of course.  It doesn't have to be related at all to the menu system as it would be added in the blank white space next to "Create a New Ticket" and doesn't depend on which menu system you're using.

**Comment by Lowell-Syncrety** [comment]
Moving one step beyond that, V2 would also index all learning items we have so those would show up, making it super useful to start building that out with tips and tricks.

**Comment by Nness** [comment]
With current implementation this is not easy to achieve. We had several design similar to that, but was docked somewhere waiting for next time we refactor request type and form system.

New menu system won't be able to solve that.

**Comment by FluidNets-DamianS** [comment]
The problem we found with "learning" is that they are each isolated pockets.  Critical to have search and links, etc.  We ended up going with a different software to behave as our searchable KB.  Future plan will be to compare new tickets against KB and offer relevant help while they are waiting for a tech to respond.

**Comment by Lowell-Syncrety** [comment]
Yeah, but at least outside of Learning, it should be easy to index all items in DD Forms, plus provide us with a background ability to add tags to forms for search capability.  Or is that a difficult technical feat?  I'm so used to seeing search everywhere that it seems not hard anymore.

**Comment by justinDJC** [comment]
Would absolutely love this. With a large client base with a huge amount of different applications to support. It would be fantastic if we could overload request types in to the system and have clients simply type in keywords e.g. ApplicationName Issue and have the Request type come up.

We send certain application support issues direct to a Streamline IT board for internal IT so having the application in a drop down of a Form is not idea.

**Comment by Lowell-Syncrety** [comment]
Yeah; I'd really like to have this and keep thinking of it often. All you'd have to index is all the data you have (don't have to index stuff from URLs). I have entered data into DD Forms. I have entered descriptions into Learning. If this was indexed so search-as-you-type would just work for people that'd be so great. 

Imagine that a user is presented with both our traditional menu plus a Search box. As they type, both ticket forms AND Learning results start surfacing. Maybe they find their answer in an FAQ we have for them. Or maybe they see the right ticket type show up for them to select. Is that a hard thing to do just with the data we've added?

Gen 2 would allow us to add keywords to tickets and learning items for better search results; these would be hidden to the end-user. Ideally we'd see reports on what people searched for and if that search ended up in clicking on something or not; that's how we'd figure out new keyword tags to add to specific items.

**Comment by Lowell-Syncrety** [comment]
I see the Tags feature showing up in Menus but can't find any documentation about it. Is this going to come to other parts of the system, so that we can start doing search? I noticed the Bigger Brains section now has a great search as you type function.

**Comment by Nness** [comment]
@Lowell-Syncrety 
Currently, tags is available for contact, company, request type, forms, tickets, members.

* Contact - allow tag filtering in admin portal
* Company - allow tag filtering in admin portal
* request type - allow tag filtering in admin portal
* forms - allow tag filtering in admin portal, or TECH when adding form to request for more info.
* tickets - allow TECH to filter ticket by tags
* members - not yet implement anywhere, only available in API at moment.

For this uservoice, original request is request type search not form search. We did recently redesigned portal side request type list. In the future we might introduce simple search. 

Simple search is using string contains, instead of full text search. Since mechanic is different between company, contact list vs request type list in portal.

**Comment by Nness** [comment]
This has been implemented and released on client portal 3.20.

**Comment by Nness** [comment]
Tag can also be used to improve search result at client portal. Even though user cannot see tag, but if match, it will count as a match.
