### ISSUE TITLE
[12643, 12728, 13567, 13793] Request Type Ordering - Currently Alphabetical

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#203]
![image](https://user-images.githubusercontent.com/30588784/48743200-e08fcb80-ecc6-11e8-8480-747664310b72.png)

As per the New UI mentioned on this article: https://www.deskdirector.com/business-blog/october-product-update-quick-wins-with-a-new-portal-ui?utm_campaign=Blog&utm_source=hs_email&utm_medium=email&utm_content=67409824&_hsenc=p2ANqtz-9Z1PAyl5bLuMu5X7cUjvPXxZSKdsYOU4Pie8TIErkVCMtOZI0odE5ALUuz19l33F5C64nSSyqeNZWchA0spqtHeM5SCA&_hsmi=67419740

By default request types are sorted in alphabetical order. The current workaround of prefacing Request Type names with a number e.g. "1) ABC" "2) DEF" 

Since the New UI contains pre-existing numbers on the far left of each request type - this visually doubles up.

**Comment by Nness** [comment]
There is rework on admin console and service catalogue system(Request Type). This will be able to tracked from #207 and there will be more detail on service catalogue soon.

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #13567 - Change the order of Options when creating a new ticket.

**Comment by Nness** [comment]
Until we redesign request types, we will introduce a way to get around this issue. The plan is to introduce convention, if the name of request type is prepend with number in certain style, we will trim off that number and order it according to that. 

Request type with specified order convention will be displayed before request type without convention. 

e.g. 

* Other
* 1: Email
* 5: Phone
* 3: Printer
Above list will be order and displayed as:

* Email
* Printer
* Phone
* Other

**Comment by Nness** [comment]
This ordering improvements has been implemented inside server 18.82.1
Documentation is under [here](https://help.deskdirector.com/article/3nm9d44vin-request-type-ordering)
