### ISSUE TITLE
[12784] Default ticket settings

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#208]
The current Source field within ConnectWise is based on the board defaults.

Feature request to have this based on a setting within the Admin Console.

![image](https://user-images.githubusercontent.com/30588784/48991035-f6553300-f195-11e8-8f28-43de2655167d.png)

**Comment by Andrew-Lahikainen** [comment]
I've renamed this to be more general. There are more properties of a ticket that you may want to set defaults for if they come from DeskDirector.

There are a few cases where Portal will create a ticket without using a request type:
* When there are no request types available for the logged in user
* When they choose "Something Else" in the new UI
* When they create a chat session from the new request support UI

One option to solve this is just to define defaults that are used in each of these cases. Another option would be to allow MSPs to create request types for these specific situations. Or we can do both, and use the defaults if the MSP doesn't set up the specific request types for these situations.

**Comment by Nness** [comment]
We have default source and default board setting inside admin now.
