### ISSUE TITLE
[12373] Main tabs

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#210]
Creating this as a separate issue to https://github.com/DeskDirector/UserVoice/issues/185. Right now on our development branch Tech has session tabs, we haven't designed for main tabs just yet.

**Comment by Lowell-Syncrety** [comment]
So it's still on the table to have a session tab, in a ticket, that can open our PSA right there?  That's 99% of the usage of our Staff HUD app right now for technicians and without that there's not enough functionality yet in the Tech product for us to switch over.

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety yes, the "open in PSA" link needs to iframe ConnectWise just like the other session tabs. This issue is for main tabs - these are the tabs in the Staff HUD that are at the top of the application, rather than the tabs that show when you open a ticket.

**Comment by Lowell-Syncrety** [comment]
So figured this out, but there's one glitch.  The link I use is https://api-na.myconnectwise.net/v4_6_release/services/system_io/router/openrecord.rails?locale=en_US&companyName=yourCWcompany&recordType=ServiceFV&recid=[ticketnumber]  where "yourCWcompany" is your CWM company name.

Now it opens CWM inside the app!  But if I open a second ticket, and do the same thing when I go back to the first ticket it's no longer in CWM but back to DD Tech for that ticket.  Is there a way to make the CWM session persistent across ticket tabs then?  We're almost there!

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety Yep, this is an issue in general when switching tabs, it does not remember the navigation state inside the ticket. I've created an issue to track this here: https://github.com/DeskDirector/Issues/issues/80

**Comment by Nness** [comment]
There might be another problem with this right? Didn't remember navigation state inside ticket is one side of story. While every time navigate to PSA page, it will cause reload. So it is best to open PSA page inside tab, else the loading time will be nightmare right?

Inside HUD, every browser view are cached, which cause huge memory usage. In web app, I'm not certain if iframe can be cached, but use ticket session for PSA page sounds like very slow.

**Comment by Andrew-Lahikainen** [comment]
Yeah it's not great, but my view is that people shouldn't need to access that tab often so it being slow is somewhat acceptable. If they do need to access their psa often, then Tech isn't the tool for them.

**Comment by Lowell-Syncrety** [comment]
> Yeah it's not great, but my view is that people shouldn't need to access that tab often so it being slow is somewhat acceptable. If they do need to access their psa often, then Tech isn't the tool for them.

On the contrary. I mean, we don't mind it being slow; even the CWM client can be slow on a regular basis. But with our techs they use Staff HUD and never open the CWM client because all they need is in the Staff HUD. So having multiple ticket tabs, some of which have full PSA sub-tabs open in them is extremely useful and functional. We don't care if it uses a lot of RAM; we stock their computers with a lot of RAM. We need them to use the one app for all things service and they can do that today in Staff HUD.

**Comment by Lowell-Syncrety** [comment]
I think if some companies just use very basic functions of their PSA (poor utilization of what should be a fully-utilized tool, IMO) then they can switch easily to DD Tech today and not miss much. We use a lot of the PSA in CWM so when we're missing a function, option or field that we regularly depend on we just can't use the DD Tech tool. And that's true even without custom fields, but especially true as we do use custom fields and don't expect that DD map all those things to DD Tech.

So light PSA users never have to go to a PSA tab but if it's there for the power PSA users then there's not much reason to stay with Staff HUD.

**Comment by Andrew-Lahikainen** [comment]
Thanks for the input @Lowell-Syncrety, and just to give you an update - Main Tabs are expected to be released early next week. Just a few small tweaks needed and then you should have close to the same experience as HUD.

**Comment by Lowell-Syncrety** [comment]
Sweet. At that point we're going to get technicians to start using DD Tech and see if we can just move over from Staff HUD.

**Comment by Andrew-Lahikainen** [comment]
These have been released
