### ISSUE TITLE
Desktop Client Speed

### ISSUE THREAD

**Issue by bbowersztds** [DeskDirector/UserVoice#219]
The desktop client is very bulky and we wish it were more streamlined to be as LIGHT as possible so that it runs very quick. The web is a lot better at this, but the broadcast and other features on the desktop client are better. Would love it if you guys could get the desktop client to be less slow.

**Comment by Nness** [comment]
@bbowersztds , could you submit an support ticket and our developer can go through your case? I have just tested the desktop client, launch it seems fast. 

When submit ticket, please include following information.

* Short video to demonstrate the opening of desktop client
* Once app is open, from top left select help to record app version.
* Use CMD to perform IP trace to our server from your local machine
* Use CMD to perform IP ping to get latency
* Describe installed machine environment, whether it is setup to use AD to login or not.
* Given device's spec and windows version.

**Comment by Nness** [comment]
@bbowersztds I will close this for now until we get more information from you through support ticket. Thanks
