### ISSUE TITLE
Ability to add a form description at the top of the form

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#22]
I would like to have either the ticket Description show up to the end-user as I did in WuFoo forms, or be able to move a Statement item up above the "Give the ticket a title" field.  For example, in the "I have an issue not listed here" General Support Request, here's my description:

![image](https://user-images.githubusercontent.com/8813029/41441790-44834b64-7088-11e8-91e2-a204621b8f8c.png)

That description doesn't show up in the ticket so I had to add a Statement right at the top of the request as below but it shows up below the first field and I'd rather it show up at the top.  In the end, I think it'd be great to have the form Description as above show up (checkbox to enable this or not if you wish) but *also* have the ability to put a top-level Statement item in a form.

 
![image](https://user-images.githubusercontent.com/8813029/41441796-4b2b6f32-7088-11e8-8ea1-17a3df16ab1b.png)

**Comment by Nness** [comment]
I believe this issue won't be a problem once we have implemented ticket title template. Which is described inside issue #1. I will close this.
