### ISSUE TITLE
[13061] Static ticket titles in DD Forms.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#223]
Feature Request to remove or lock down the Ticket Title question that is automatically added on to Desk Director Forms.

If a format is specified for the title, this will override what the user enters in here anyway. I would like to make sure that they are unable to input information into the title field that will be overridden with our specified title format.

This would only be for some forms - for example New User forms that have a specific format we want the title to have. For general support tickets we would be fine for the title to be entered by the user.

**Comment by Nness** [comment]
https://github.com/DeskDirector/UserVoice/issues/1

@Aycorn this is original user voice and the work on this is not yet finished.
