### ISSUE TITLE
[13509] Disable Somthing Else flag per Company.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#232]
Discussed primarily on request #109 

The ability to disable the Something Else feature is only available if the New Support Request System is enabled globally.

![image](https://user-images.githubusercontent.com/30588784/51280978-f959fa80-1a45-11e9-8b4d-140958884432.png)

Request to have this flag available at a company level for customers performing a staged rollout to their clients.

**Comment by chris-ls** [comment]
This has been implemented
