### ISSUE TITLE
[13564] Export of Contacts with active Permissions set

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#236]
![image](https://user-images.githubusercontent.com/30588784/51446374-1f4d0b00-1d76-11e9-9274-ffcc1f46e4cd.png)

Feature request to have an exportable list of any contacts with the "Permissions" tab set to "ON".

This will allow customers to quickly review users with explicit permissions, and revoke when required.

**Comment by Nness** [comment]
Currently without export, we already can limit contact or company list right?

**Comment by Aycorn** [comment]
You can export contacts by permissions:

![image](https://github.com/user-attachments/assets/cb6aed8d-8c3c-4d4f-9499-71753d49c2dc)
