### ISSUE TITLE
New Ticket Interface: Flag for Review doesn't respect permissions

### ISSUE THREAD

**Issue by prysmcorp** [DeskDirector/UserVoice#238]
In the new ticket interface the flag option is not respecting the permissions that are defined globally, at a company, or contact level.

Please review.

**Comment by Nness** [comment]
Sorry. this is user voice for new ideas or feature request. Please reach out our support.

**Comment by prysmcorp** [comment]
Ok, this is feedback on a beta item. Can it be submitted under DeskDirector / Issues ?

**Comment by Nness** [comment]
please report to support. 
support.deskdirector.com or support@deskdirector.com

Once support is identified, we will create issue on DeskDirector/issues. 

Please include screenshot and how to reproduce when submit bug report to support. I already passed your issues to associated developer, more info will be better.
