### ISSUE TITLE
[13780] Approvers by Request Type

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#244]
Feature request different Request Type approvers.

Say for example one tagged group/customer can approve the changes related to Network request types, and a separate tagged group/customer can approve Hardware request types.

**Comment by Andrew-Lahikainen** [comment]
@Nness @chris-ls I think we need a mega-issue for all request type feature requests since we're thinking of redesigning them at some point. It would help clean up some of these feature requests and keep discussion in one place. What do you think?

**Comment by Nness** [comment]
@Andrew-Lahikainen sure. For this one, I think the root cause is approver only care certain kind of ticket. This is good opportunity to introduce tags.

**Comment by NetFusionDesigns** [comment]
In Addition to this - it would be nice to have an option to specify the number of approvers required.

IE certain sceneriors like maintenance on a ERP system would require approval from 3/5 specific approvers

**Comment by bobsquid** [comment]
This is a request we have had from multiple clients, so I'd definitely like to see it implemented.  Many of our clients have different approvers for financial requests vs security changes, and they often don't want those overlapping, so it has been a bit of a pain point.

**Comment by Nness** [comment]
This has been implemented. 
https://help.deskdirector.com/article/zt9zs2y5rl-ticket-group-permissions
