### ISSUE TITLE
Better system to organize form sections

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#246]
Since introduce of form sections and section condition. Currently we don't have anyway to reorder or organize sections. 

Overall, form designer could take additional design to improve usability. aka 3rd version of form editor.

**Comment by Andrew-Lahikainen** [comment]
Related? https://github.com/DeskDirector/UserVoice/issues/57

**Comment by NetFusionDesigns** [comment]
Yes, please enable an option to reorder sections and have sub-sections up to 3 levels

**Comment by Nness** [comment]
new form editor supports section ordering.
