### ISSUE TITLE
[13727] equal Condition for multi selection field within DD Forms

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#248]
![image](https://user-images.githubusercontent.com/30588784/52183374-2abb2e80-286c-11e9-8a00-9f35448b6ba3.png)

Feature Request to have a Contains_Only condition in addition to the 2x available currently.

**Comment by Nness** [comment]
Contains all is s ame as contains only. Contains all means anything list in there must be selected.

**Comment by Nness** [comment]
The scenario for this is not trigger when additional has been ticked. 

When a field is triggered on option 1, then if option 1 and 2 been selected, this shouldn't be triggered.

**Comment by Nness** [comment]
Change to equal instead of contain only, not as obvious to understand as equal.

**Comment by Nness** [comment]
Latest admin portal and portal supports this.
