### ISSUE TITLE
Infrastructure Overview

### ISSUE THREAD

**Issue by NetFusionDesigns** [DeskDirector/UserVoice#250]
Automate Integration to have a client dashboard displaying server outages. As well as linking request types to specific servers, which would prevent staff from creating tickets for items we are already aware off.

Example: Request type CRM Issue, we would map it to all our customers CRM servers - if any of them are offline, there should be banner informing the user when submitting a CRM ticket that there is already an outage and it's being worked on

**Comment by Nness** [comment]
That's what broadcast is for. When broadcast has been set, then it will be display alert toast when user try to create ticket.
