### ISSUE TITLE
[14104] Embed video code for Learning Center as an alternative to URLs.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#254]
Feature request for being able to use embedded code for videos as a method of presenting videos within the DD Portal. It is currently only possible to use URL's.

**Comment by Nness** [comment]
Please give some embed video code as an example. I think embed video code has embed url.

**Comment by Nness** [comment]
Until more resource has been provide, I will mark this as declined. Since I don't feel this is an issue.
