### ISSUE TITLE
[14130] Ability to customize the "Good Morning / Afternoon / Evening" content.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#256]
![image](https://user-images.githubusercontent.com/30588784/53212969-ec1ad600-36ab-11e9-8229-65f07bc3db64.png)

Feature request to have this as a custom brand asset. An example would be the DD Customer's logo with a "Welcome Back" message. This can be a static image.

**Comment by Lowell-Syncrety** [comment]
Yes, even the ability to add company logo and personalization. "Good afternoon, Lowell!"

**Comment by AirLHull** [comment]
100% agree that would be a wicked idea!

**Comment by Aycorn** [comment]
I believe the referenced screen in my original request is now longer part of the sign in experience. Marking as closed.
