### ISSUE TITLE
Spellcheck on ticket notes.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#257]
Feature request to have Spellcheck enabled on the ticket note field in DD Portal:

![image](https://user-images.githubusercontent.com/30588784/53366630-efaea580-39a8-11e9-9aed-71c1002384cc.png)

**Comment by chris-ls** [comment]
This should be treated as an Issue rather than a feature request, since this functionality is available on the web version of the Portal.

I have opened a new Issue here:
https://github.com/DeskDirector/Issues/issues/79
