### ISSUE TITLE
[14176, 20436] Solution for contacts with email addresses across multiple companies.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#258]
Normally under the scenario of a contact belonging to multiple franchise companies with ConnectWise, each contact will have the same email address.

Primary Company | Contact: aaron@company.com
Franchise Company | Contact: aaron@company.com

Desk Director currently forces the user to log in as 1 contact - however works around this using the "Additional Access" feature.

Feature request when someone enters their email address to sign in, if their email address is associated with multiple companies, it would present them with a drop-down allowing them to choose which company to log in as.

If that's not doable, a fall back could/should be that when submitting a request through a DD form that it would somehow present the company they want to submit for.

**Comment by kcjones76** [comment]
Hey Aaron, thanks again for posting this. Your paraphrasing summed it up pretty well. I look forward to see how this can be implemented. By the way, it's cdandrea@tenecom.com.

**Comment by Andrew-Lahikainen** [comment]
We've talked about this before internally and it is something we want to do. Pretty much with the same user experience you have described.

We do have motivation to do this since we want to deprecate the Additional Access feature due to a few problems it has.

I'll talk to the team about it and see when we might be able to tackle this one.

**Comment by kcjones76** [comment]
Hey Andrew, that's great to hear. This is one of the killer features that would help us really seal the deal with our client base. While it doesn't affect all of them, there is a heavily-weighted portion that this would take full advantage of this.

If and when it does get moving within your development, we wouldn't mind participating in any closed testing. I'm not sure if it's helpful, but I'd like to elaborate on where the need arises.

- Parent company, e.g. MegaCompany
- Child companies or business units tracked as separate companies under ConnectWise, e.g. MinCompany A, MiniCompany B, MiniCompany C...
- Controller that submits ticket requests on behalf of both the parent and child companies, e.g. controller@megacompany.com. This controller is listed as ConnectWise contact under each of the above ConnectWise companies

1. Controller enters email address, followed by their password or magic token.
2. DD would then recognize the fact that the email is associated with multiple companies within ConnectWise. At which point a company drop-down would be presented, comprised of all those companies. In our opinion this may be cleanest approach as it could avoid building up anymore complexity within the DD forms. It would also create a direct separation at login, including the initial view of the specific tickets, contacts, etc., under that logged in ConnectWise company. 
3. Perhaps the use of Impersonation could be incorporated for use by that contact as well, versus limiting this to an admin feature. The idea being they could flip to other companies their email address is associated with, e.g. perhaps a company drop-down beside their profile in the top-right or in the left navigation bar with the other action buttons.

**Comment by Andrew-Lahikainen** [comment]
@kcjones76 work has started on this, expected to be released at the end of this sprint (25th October)

**Comment by kcjones76** [comment]
This is great news, thank you!

Can I inquire how you guys see implementing this? Will it be closer to the suggestion I presented in point 2 of my follow up response to this thread

**Comment by Andrew-Lahikainen** [comment]
@kcjones76 Here's a gif showing the behaviour on my machine:
![hWYiJP0bOm](https://user-images.githubusercontent.com/10571313/67137476-9cb89400-f292-11e9-90c6-c331b4814ef2.gif)

The implementation is as how you described in point 2.

**Comment by Andrew-Lahikainen** [comment]
Shipped 🚀
