### ISSUE TITLE
Partial or wildcard search on portal

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#262]
Currently when searching in the desktop app, you must enter the full word for the search to find the ticket.  Would be good to be able to do a partial word search or have wildcard options

**Comment by Nness** [comment]
It is already partial search. Minimum char for each partial search word is 3 char. 

e.g. 
`sear` will translate to `sear*`. While `se` and `s` will only perform exactly match. 

Decision for such thing is improve search result, for partial search when only 1~2 chars is provide, it is likely to provide any meaningful result.

The only improvements that's planned is for multiple word search.

For example. currently when search for terms: `ticket dama`. It will translate to `ticket ticket* dama dama*`. This gives less context and low accuracy. 

Future iteration will be translate `ticket dama` to `ticket dama` boost 20 then `dama*` boost 1. That way, exactly match is on top, but partial search only apply to last word with less importance.
