### ISSUE TITLE
[14358] Include Global Permissions Information in Request Type Export

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#267]
Feature request to include the Global Access flag and inclusion/exclusion list on the current Request Type Export Excel file.

![image](https://user-images.githubusercontent.com/30588784/54321805-73c68580-4657-11e9-83f0-793eef207eae.png)

![image](https://user-images.githubusercontent.com/30588784/54321798-6a3d1d80-4657-11e9-8f9c-e1f16f5e8f01.png)

**Comment by Nness** [comment]
We are currently working on redesign request type, unless we cancel that project, else this won't be considered.

New design is supposedly to be easier to use than existing one.
