### ISSUE TITLE
[14389] Externally adaptive DD Form Fields

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#268]
Feature request to have DD Form Fields update via API.

An example being a new user guide, where the "Which security groups should this user be a part of?" is automatically kept up to date based on the currently active Active Directory groups.

This could be something where an integration into something like Sharepoint is available, and it is the customer's responsibility to maintain the data being updated in the Sharepoint table.

**Comment by Nness** [comment]
This feature is actually started. Field that will populate depends on API. But actual sharepoint implementation is not our responsibility. We will build several built in API for such dynamic field, it is open for customer or consulting to fill the gap.

**Comment by cdandrea** [comment]
As this is now listed as started, can we understand a little more about the plan? Is the intention to introduce new form objects that rely on source data to be populated? This would be a major feature!

**Comment by chris-ls** [comment]
@cdandrea 

The gist of the feature is that there will be a new DD Form field called a "Dynamic Field"

The Dynamic Field will require a URL (the API endpoint) to be configured.
When the question is displayed in the Portal, the Portal will send a GET request to the API endpoint along with any search term the user entered and will then display the returned results, allowing the user to select one (or many) of the options.

The data returned by the API endpoint will need to follow a specific format, which will be described in full once we release.
We will probably be providing a couple of built in API's specifically for this purpose.
e.g. returning a list of contacts

To display options in the form which represent your **own** business logic will require some work.
In the example given above: "Which security groups should this user be a part of?" 
This will require that you create your own API endpoint which handles all of the logic of getting data from SharePoint and formatting it into the correct format that the form expects.

**Comment by Lowell-Syncrety** [comment]
Another great use of this would be the ability for a customer to select from a set of apps that we've said are installed at their site. So when they need an app installed, or having problems with an app a drop-down would show just the ones at their site. We've already talked about making a separate table for this but don't know how to link that into DD Forms as a field.

**Comment by Andrew-Lahikainen** [comment]
Implemented a long time ago. Here are the docs: https://help.deskdirector.com/article/109t6ieaao-desk-director-forms-dynamic-fields

Closing 👍
