### ISSUE TITLE
Print Ticket Button

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#27]
Our customers are asking us about a missing feature in the DD portal which is the ability to print the ticket. The ConnectWise portal has a print ticket button which formats the ticket in a great format for easy printing and reading. I would like to see something like this in your portal.

**Comment by Lowell-Syncrety** [comment]
Oh yes, we do this as well in scenarios where we have a product attached to a ticket and need a printout of that ticket physically attached to the product on our Outgoing shelf.

**Comment by Nness** [comment]
I will close this one, since it is duplicate with #11. #11 has CW ticket attach to it.
