### ISSUE TITLE
[15066] Line Breaks within DD Forms

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#285]
Currently line breaks aren't reflected within DD Forms.

![image](https://user-images.githubusercontent.com/30588784/56924000-00ea6e80-6b20-11e9-8010-4b24db2f772c.png)

![image](https://user-images.githubusercontent.com/30588784/56924003-021b9b80-6b20-11e9-967b-48e96dbb34dd.png)

**Comment by jonovisits** [comment]
+1 on this!

**Comment by Nness** [comment]
This is markdown spec. Please check markdown documentation for how to perform new lines. 

In short, you need extra line to specify new line, or 2 space at end of line to specify new line.
