### ISSUE TITLE
DD Tech: Add "Discussion" to note/time entry

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#290]
Referencing this issue: https://github.com/DeskDirector/UserVoice/issues/24

Supposedly it was implemented, to have "Discussion" one of the options a tech can choose when writing a note in a ticket. We don't see this; we just have "Internal" and "Resolution". To minimize clutter on invoices (all notes with "Resolution" show up on an invoice" when we are just asking questions or getting more information from a customer or third-party those things go in CWM's Discussion section. So is the Discussion checkbox simply something we'll see in an update or is it not showing up for some other reason?

**Comment by Lowell-Syncrety** [comment]
Yeah, this is one smaller issue preventing us from moving to DD Tech from Staff HUD. Many times we're just communicating with the customer and if that's in "Resolution" that means it will show up on their invoicing. We don't need standard back-and-forth communication to all show up on the invoice. Can one more checkbox just be added, at least for CWM users?

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety 

The 4 states are:
* Discussion
* Discussion Resolution
* Internal
* Internal Resolution

The default is discussion:
![image](https://user-images.githubusercontent.com/10571313/63201454-6ff0d080-c0d9-11e9-98ea-e710c88ac299.png)

Then discussion resolution:
![image](https://user-images.githubusercontent.com/10571313/63201471-85fe9100-c0d9-11e9-907f-8be6d7ffe887.png)

Then internal:
![image](https://user-images.githubusercontent.com/10571313/63201490-97479d80-c0d9-11e9-8491-89e254aa3393.png)

Then internal resolution:
![image](https://user-images.githubusercontent.com/10571313/63201501-9f9fd880-c0d9-11e9-93cf-bdb7ed6898d5.png)

Internal notes can't be discussion.

From your last comment it seems like you want to just leave both checkboxes switched off? If this is still being marked as resolution - then that's a bug.

**Comment by Lowell-Syncrety** [comment]
Oh, wow. OK, this isn't clear from the interface. A little note next to the checkboxes might be good (i.e. "If no options checked notes will log as Discussion type". Thanks for the clarification, and nice to know we don't need a new thing added.

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety yeah, implicit behaviour is never ideal. I'll see if I can add a helper text to help with this.
