### ISSUE TITLE
No contact number information available against a ticket/contact within DD Tech.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#295]
It would be nice to display the contact's callback information directly on a ticket within DD Tech.
Somewhere on this left hand column as a suggestion.

![image](https://user-images.githubusercontent.com/30588784/57426302-be890600-7272-11e9-8f8b-63b87c9720a4.png)

![image](https://user-images.githubusercontent.com/30588784/57426235-8a154a00-7272-11e9-8c1d-bc90da792835.png)

**Comment by Andrew-Lahikainen** [comment]
@Aycorn too much of a hassle to go to the contact tab? I don't think the ticket api has this information immediately available so it's another api call which I would want to avoid if possible.

**Comment by Aycorn** [comment]
@Andrew-Lahikainen please confirm where this is?

![image](https://user-images.githubusercontent.com/30588784/57820351-8ccaee80-77e0-11e9-8bb3-7c7c22c28da1.png)

**Comment by joeseppie** [comment]
@Andrew-Lahikainen - We also need the contact phone number available somewhere.  If not on the ticket screen, at least on the contact tab.  It's not there either.

**Comment by Andrew-Lahikainen** [comment]
This has been shipped :)
