### ISSUE TITLE
DD Tech: Ability to select who a ticket gets emailed to

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#297]
We would like to request a distinction between contact, resources, and CC’s below notes on the ticket window in DD Tech, as it is not clear who the update is going to. CW lists the email addresses next to check box to distinguish who the ticket update belongs to at the bottom of the window. I've included an attachment with the ConnectWise view for your review.

If this is not a possibility, I think it would be even better to have the ability to send a message to the ticket contacts and resources and append it as an addendum to the ticket!

**Comment by Andrew-Lahikainen** [comment]
I'm not 100% sure what this one is referring to, there's no image.

**Comment by Andrew-Lahikainen** [comment]
Closing because unclear
