### ISSUE TITLE
[18810] DD Portal: My/All Tickets default as a User setting

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#300]
When a user that has the ability to see all tickets goes into their portal, they are defaulted to the "my tickets" view and some folks would like to have the default be "All Tickets". I haven't found any way to do this yet, but it would be nice if we could set the default - or maybe the user sets the default. In either case, if they want to see All Tickets we they log in, then we'd like to be able to configure it that way.

**Comment by FluidNets-DamianS** [comment]
I concur.  If a user selects view all we should remember that setting going forward.


Damian C. Stalls
vCIO Director
805.856.1815 Direct

________________________________

**Comment by chris-ls** [comment]
Done. Will ship this week.

The setting will persist in the client's localstorage. (on their machine)
This means it will persist when the user closes/reopens the app.
But it won't follow them around from machine to machine.

**Comment by Nness** [comment]
The user should set their defaults not MSP's job to do that. Remember their last entry is first step on improve this. We should have more option for user in the future.
