### ISSUE TITLE
[10450] File Attachment / Clipboard Access

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#31]
The file attachment option should function similar to ConnecWise in that I should be able to attach a file or content from the clipboard.  Often I use GreenShot to take a screen capture and annotate it and want to send it to the user.  In CW I can re-copy to the clipboard then attach to the ticket.  In DDTech i have to save, then attach, then delete.

**Comment by Lowell-Syncrety** [comment]
Didn't actually know you could paste from clipboard in CWM, but looks like it puts it in as an attachment... the ideal is for companies to allow for inline pasting of images from clipboard.  Then when sending things like instructions through the ticket we can paste specific screenshots with descriptions or notes inline.  That seems to be a very hard thing to implement in a web rich text control as it's rare to see it implemented.

**Comment by Andrew-Lahikainen** [comment]
This shouldn't be too hard to implement, will probably consider this when Tech starts redesign of time entries.

**Comment by Nness** [comment]
I think we should clarify on this. Clipboard paste as file should be easy, but inline images is hard because of PSA. Autotask and ConnectWise doesn't support inline images, thus it will display as markdown link on PSA's ticket detail.

The inline experience will be same as GitHub's comment.

**Comment by Lowell-Syncrety** [comment]
Fair enough, that makes sense.  Limited by PSA in this case.

**Comment by Andrew-Lahikainen** [comment]
This has been shipped :)
