### ISSUE TITLE
[19029] DD Forms: Ability to pre-select options for Choice fields

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#314]
Feature request to have multi-choice questions with pre-selected answers.

![image](https://user-images.githubusercontent.com/30588784/58599526-c584c080-82d4-11e9-861b-266e9fce0370.png)

In the example, it's more common for the user to require access to Group Shared Docs, rather than not have access.

For form efficiency and user experience, ideally we would have this pre-selected and only de-selecting for edge cases.

This also serves as an internal reminder to the engineer behind the ticket as the form's input into the PSA will now include this for majority of entries.

This also serves the purpose of a new end user being delegated the responsibility of filling out the form, as they may be unsure of what a "standard" setup would require.

**Comment by Nness** [comment]
#202 
Close this because same topic.
