### ISSUE TITLE
[15476, 18559, 18965] Show/Edit service item

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#315]

**Comment by joeseppie** [comment]
Andrew, can I get an update on when Service Item will be added to DD Tech?  This is holding us up from moving all techs and updating clients to use v2 portal.  Thanks!

**Comment by Andrew-Lahikainen** [comment]
@joeseppie next week's release will have this, I'll update this issue when deployed

**Comment by joeseppie** [comment]
Status update?

**Comment by Andrew-Lahikainen** [comment]
@joeseppie This is implemented in the dev build, I've just got to fix a small issue where updates aren't being shown when board/status/type etc are changed by the user.

Expected released next week - apologies for the delay in this.

**Comment by joeseppie** [comment]
@Andrew-Lahikainen thanks for that update.  How's it progressing now?

**Comment by Andrew-Lahikainen** [comment]
@joeseppie it's looking good, but still a little bit of a wait. We're actually refactoring the entire ticket module to add a few more features, improve responsiveness, and improve ux.

We've added change service item, assign other resources, markdown rendering, responsive ticket details.

Here's a video gif showing a few of the changes:

![ticket-refactor-demo](https://user-images.githubusercontent.com/10571313/70289653-48fe0c00-183a-11ea-8001-19dbd4c9a092.gif)

**Comment by joeseppie** [comment]
@Andrew-Lahikainen do you have an approximate ETA?

We aren't using the new chat yet because we haven't made techs use DD Tech yet (because Service Item is missing).  We now have clients asking for the new chat and we are waiting to enable v2 for all clients as well.

I'm also rebuilding all of our request types, and I wanted to make this one big "upgrade" to announce to clients.

Thanks.

**Comment by Andrew-Lahikainen** [comment]
@joeseppie unfortunately looking like it will be around the first couple of weeks next year.

**Comment by Andrew-Lahikainen** [comment]
Shipped, thanks for your patience everyone ❤️
