### ISSUE TITLE
Changes made to MasterAdmin

### ISSUE THREAD

**Issue by HasnainKhattak** [DeskDirector/UserVoice#325]
In the admin portal, we should see a prompt that the change is applied when we make a contact MasterAdmin. Currently when hitting the save button, there is no notification. Would be good to have a prompt, green bar at top to confirm the change has been done.

At the moment, when I make a change to user I got back to the contact list and access the contact again to make sure the MasterAdmin checkbox is checked.

**Comment by Aycorn** [comment]
I don't believe this is required as the Admin console has since had a UI overhaul.
