### ISSUE TITLE
Approval Discussion Note Template for "Your Reason"

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#334]
Feature request to include the Approval Granted template as well as the Approval Reason as a discussion note. Currently this nice template is only included if you don't provide a reason:

![image](https://user-images.githubusercontent.com/30588784/60856098-23081780-a25a-11e9-9f19-150e3a45e41d.png)

![image](https://user-images.githubusercontent.com/30588784/60856105-2a2f2580-a25a-11e9-8e78-0a3ea86639d3.png)

Something like this:
![image](https://user-images.githubusercontent.com/30588784/60856148-4fbc2f00-a25a-11e9-90fc-5eb151fd2ddd.png)

**Comment by Andrew-Lahikainen** [comment]
I've created an issue which tracks this feature request #335
