### ISSUE TITLE
Search Ticket History Contents in Portal

### ISSUE THREAD

**Issue by dr3dgen** [DeskDirector/UserVoice#343]
Our clients are requesting the ability to search/query their closed tickets using full-text, beyond just the ticket name, for reoccurring issues. (e.g.  If there is a specific error that came up three months ago, but the user can't remember the exact fix, they would like to be able to search for the resolution through use of keywords recalled from the case in the _Closed Tickets_ search field and apply the fix themselves, rather than ask the technicians about it or look down an endless list of tickets that they've made, but don't remember.

This would likely require some indexing. Perhaps by date - or maybe function similar to an email inbox search (minus the headache :) )

**Comment by Andrew-Lahikainen** [comment]
Related https://github.com/DeskDirector/UserVoice/issues/46

**Comment by Andrew-Lahikainen** [comment]
I'll close this off as a duplicate, but we'll be able to reference this from the other issue :)
