### ISSUE TITLE
[10294] Add work type when creating ticket using request types

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#35]
We're thinking that this will be a global setting which gets applied for every request type. Later on if we implement on the request type level, it will overwrite the global setting.

**Comment by walbertson** [comment]
Commenting to show interest. We utilize this field in Autotask and it's set as a Required field. Any ticket submitted through DeskDirector then has to have this field be manually adjusted when forwarding or making other edits via AutoTask. I contacted support and they indicated it's not on the roadmap. Lack of adding all fields from Autotask is seriously making me reconsider whether DeskDirector is a platform we should continue using.

**Comment by Nness** [comment]
For work type, here is API reference.

* SOAP API as [AllocationCode](https://www.autotask.net/help/Developerhelp/Content/AdminSetup/2ExtensionsIntegrations/APIs/SOAP/Entities/AllocationCodeEntity.htm)
* RESTful API as [BillingCode](https://www.autotask.net/help/Developerhelp/Content/AdminSetup/2ExtensionsIntegrations/APIs/REST/Entities/BillingCodesEntity.htm)


For SOAP API, Ticket has `AllocationCodeId` we can set.
