### ISSUE TITLE
DD Tech: Desktop App

### ISSUE THREAD

**Issue by 4rsl** [DeskDirector/UserVoice#354]
Has anyone raised the possibility of having a desktop app for Tech in a similar setup to Portal? I personally tend to find the webpage getting buried in my workflow, or worse having multiple instances open which seems to cause issues. For example, if I have two tabs open with a chat request in two different windows and I answer one of them, the other doesn't go away. So, then I hunt down the instance and close it, but it often happens again. I realize this may be a workflow problem, but I figured I'd ask anyway. Thanks!

**Comment by Lowell-Syncrety** [comment]
We are almost ready to switch from the old app Staff HUD to the new DD Tech but there's one key feature missing from DD Tech (ability to have multiple ticket tabs with full PSA session embedded) that we love with Staff HUD. For DD Tech, I'd recommend making it behave like an "app" so it gets its own icon and stays separate from other browsers. Really great feature. If you're using Edge (Dev based on Chromium) this is super-easy by going to settings, Apps, Install this site as an app. In Chrome it's a lot more steps but still do-able.

**Comment by Andrew-Lahikainen** [comment]
@dr3dgen technically this is now possible with the new login flow, but I don't know if I would recommend it 😅. The new login flow will ask which platform you want to login to, so if you install the desktop Client Portal on your machine, but instead sign in to the Tech Portal you will have what you want. I haven't really tested this, but one issue might be on startup where the desktop client will try to sign in with AD, which will bypass the sign in page and go straight to the Client Portal.

**Comment by dr3dgen** [comment]
Haha, I'll test it out and report back! Thanks!

**Comment by iskolares** [comment]
The new version of the DD Desktop app, now has a specific version for DD Tech.

Please check and test this from your end.

**Comment by Aycorn** [comment]
The `TECH Portal` has an installable application available from the Admin Console under Portal > Desktop Installers.

![image](https://github.com/user-attachments/assets/ad045b8d-3125-4293-b751-302728fe20ab)
