### ISSUE TITLE
Portal: Highlight missing email on login page

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#358]
Was just wondering if it is possible for an error to appear or the screen to shake when someone clicks on the "send token" button without typing in an email. Currently nothing happens and for some reason our clients are confused and think the button is broken without typing their email. I think adding in a screen shake or a message saying "Please enter email" and highlighting the Email field would resolve this issue.  Another option to add would be disallow the Login / Send Token buttons without a valid email address entered.

I know that the proper solution to this is end user training, but you know, users.

**Comment by Andrew-Lahikainen** [comment]
This has been resolved by the new sign in page. Users are required to enter their email address before they can progress to request a sign in token. See docs here: https://deskdirector.helpdocs.io/article/py9m7qwhuv-sign-in-to-desk-director
