### ISSUE TITLE
DD Tech: Billing Type does not change appropriately when Work Type changes

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#361]
In CWM when we select the Work Type "Phonecall/email" it is a "No Charge" billing type, so it sets the "Billable" field of a ticket to "No Charge". When I set the Work Type to that in DD Tech it leaves the Billing Type as "Billable" and when checking CWM, it's also set to Billable.

**Comment by Andrew-Lahikainen** [comment]
Please submit a support ticket!
