### ISSUE TITLE
DD Tech: Contact "Send to" checkbox keeps unchecking itself

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#362]
Before I start writing a note in a ticket in DD Tech or CWM I first define who I'm sending it to, and if it's internal only, etc. so I don't forget. In DD Tech when I send a note (either in Add Note or Add Time Entry) about a sentence in the "Contact" checkbox goes unchecked. I can select it again, but shortly it unchecks again. It's about every 30 seconds. Tried in Edge and in Edge Dev (chromium-based).

**Comment by Andrew-Lahikainen** [comment]
Thanks for the report!

For bugs, just submit a support ticket and we'll confirm and add it to our bug tracker.

This is a known issue, raised recently. Here's the link to the issue:
https://github.com/DeskDirector/Issues/issues/114

I'll close this issue off. Please subscribe to the linked issue if you want to be notified when it is closed.
