### ISSUE TITLE
Adding company/contact filters on Request Types should automatically select the "Search" field

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#366]
Currently you need to Tab once the new window opens before typing:

![image](https://user-images.githubusercontent.com/30588784/64667088-ad643600-d4ac-11e9-8891-10e8f5b159dd.png)
![image](https://user-images.githubusercontent.com/30588784/64667090-afc69000-d4ac-11e9-8586-de856c93bcf5.png)

**Comment by Nness** [comment]
This has been addressed with new implementation.
