### ISSUE TITLE
[20249, 23817, 24595] File attachment upload limit (File size)

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#371]
PSA has restriction on file upload size. It is 6MB. To get around the limit, means file needs to be stored inside a third party. While doing that, it should also put consideration into GDPR and security.

One of potential is find a storage that our customer can create, it is permission protected. That means when customer leave us, all files is within the storage they have created.

For their client who uses portal, they can access those file through portal. There is no direct link to download.

**Comment by Nness** [comment]
There are two potential option.

* OneDrive
* Blob storage.

Both can be created by customer. OneDrive means it can group's OneDrive location, where group is shared with customer's employee. It also have direct access link.

Azure Blob Storage means there is no direct access link, but through azure storage app. Only user who granted access to blob can access. Where TECH and portal can both allow user to download or view attachments.

Blob have better throughput, it supports bigger file up to 1GB. OneDrive's advantage is access from link that saved inside ConnectWise or Autotask attachment.

**Comment by DDAndyChen** [comment]
Related ticket 23817

**Comment by Aycorn** [comment]
I believe this has since been addressed as the [File System](https://help.deskdirector.com/article/mgqai596yd-file-storage) feature and will mark this as closed.
