### ISSUE TITLE
DD Forms: Add friendly name for URL

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#377]
I'd like a URL "type" of question that allows me to put in a URL but have a friendly view for it. For example, I have a very long URL that is a Quosal reorder URL the customer can use to reorder toner. Currently outside of using a service like bit.ly or manually creating our own custom DNS entries there's no easy way to just use HTML to show a friendly name for a long URL.

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety you can use markdown to format these URLs. For example:

```markdown
[I'm an inline-style link](https://verylongurl.verylongurlsarenotuserfriendly.longurl/massiveguid/1234-23123-4124-2333)
```

Will render as
[I'm an inline-style link](https://verylongurl.verylongurlsarenotuserfriendly.longurl/massiveguid/1234-23123-4124-2333)

(github uses markdown too)

**Comment by Lowell-Syncrety** [comment]
OK, that's great! I had put in a ticket and support told me there isn't a way to do it.

**Comment by Lowell-Syncrety** [comment]
Nice! And you already did it for me. :)

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety 

That was @Nness, he left a response on ticket 20362 😂
