### ISSUE TITLE
DD Forms: Ability to remove "Summary" field

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#378]
If we want to have a form that is simply informational, that contains a Statement field or maybe a URL or link to a video (embedded?) it would be nice to get rid of the required "Summary" field and Submit button.

Either that or a special type of "form" that we can use in the Request Support section that is simply informational.

**Comment by Aycorn** [comment]
@Lowell-Syncrety we have similar forms configured that use the [Ticket Title Automation](https://help.deskdirector.com/article/yujwtdnt4l-ticket-title-automation) feature.

By default this hides the Ticket Summary, however doesn't hide the Submit button.

Our "How do I..." tickets all contain a "I have watched the video and require some help" section that needs to be ticket before clicking submit:

![image](https://user-images.githubusercontent.com/30588784/66284274-8b32cc00-e923-11e9-9a2f-5dcc15278196.png)

Hopefully this helps, will still wait for an official response from the Dev team.

**Comment by Lowell-Syncrety** [comment]
Thanks, @Aycorn! While trying to do what I needed to, I was thinking of your example that I've seen before.

**Comment by Nness** [comment]
As Aaron has mentioned, title automation is the way to remove summary.
