### ISSUE TITLE
Support Office365 shared mail box (send email)

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#379]
When sending email, currently system only allow sending from user's main email account. It does not support shared email.

Shared email require consent scope of: `Mail.Send.Shared`.

Shared mail should include permission for `Send on Behalf` and `Send As`. They can be configured according to following image. (Under, Groups => Shared mailboxes)
![2019-10-03_10h43_26](https://user-images.githubusercontent.com/1712143/66084238-a2dc1e80-e5ca-11e9-9295-691d28731901.png)

When sending email, it can use following format.
```javascript
// POST https://graph.microsoft.com/v1.0/me/sendMail
{
	"message": {
		"subject": "Meet for lunch?",
		"body": {
			"contentType": "Text",
			"content": "The new cafeteria is open."
		},
		"toRecipients": [
			{
				"emailAddress": {
					"address": "jason@deskdirector.com"
				}
			}
		],
		"sender": {
			"emailAddress": {
				"name": "Shared",
				"address": "shared-test@deskdirector.com"
			}
		},
		"from": {
			"emailAddress": {
				"name": "Shared",
				"address": "shared-test@deskdirector.com"
			}
		}
	}
}
```

If user does not have permission to send on behalf. The error return back is
```javascript
// 403 Forbidden
{
    "error": {
        "code": "ErrorSendAsDenied",
        "message": "The user account which was used to submit this request does not have the right to send mail on behalf of the specified sending account., Cannot submit message.",
        "innerError": {
            "request-id": "0fbc6046-3158-47c1-b535-d4e8c45cd46d",
            "date": "2019-10-02T21:38:04"
        }
    }
}
```

At moment, we don't have anyway to check whether user have access to shared mailbox other than exception. Unless the initial consent has higher permission.

**Comment by DDAndyChen** [comment]
The send email method would be "Send As"
https://docs.microsoft.com/en-us/graph/outlook-send-mail-from-other-user#send-as

**Comment by DDAndyChen** [comment]
This has been implemented and released
