### ISSUE TITLE
Change Portal Login Page Background Colour

### ISSUE THREAD

**Issue by notoli** [DeskDirector/UserVoice#38]
We would like to be able to change the login page's background colour, as we embed the portal on a page on our website using an iFrame.

We would also like to be able to remove the portal title from the login page, this has already been logged under issue #37.

![image](https://user-images.githubusercontent.com/40300119/41475335-72cb381e-70b6-11e8-8914-c12aa3221ee1.png)

**Comment by Nness** [comment]
As state inside #23, is fully configurable login page able to solve this problem? Instead of allow change in application color theme.

**Comment by Nness** [comment]
We are investigating on the way we do color branding. Let's see if we can find a better way to resolve such need. I will put it in backlog first.

**Comment by stephenmonk** [comment]
I think this is highly needed.  It does not look the best with the options we have.  For example if you use the dark them navigation and have  nice logo with white in it...that doesn't look good for login because it is white.  At least make the login box dark too if you chose dark as a quick fix.

**Comment by Nness** [comment]
I am closing this for issues #76 and #77 . Customize portal theme will be tracked under that two issues.
