### ISSUE TITLE
Account prompt on log in for contacts with multiple email addresses configured.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#380]
Customer's will often have contacts across multiple companies with the same email address. This configuration is often for billing reasons, where company/branch entities are split into separate CW companies.

Example:
Contact: aaron@company.co.nz
Company: Company Franchise 1

Contact: aaron@company.co.nz
Company: Company Franchise 2

Contact: aaron@company.co.nz
Company: Company Franchise 3

Currently, the only login method that supports this setup is to set a password against each account, and log in using each account's specified password.

Feature request is to have this detection as part of the login process, with the customer selecting which account they would like to access.

1) Prove you have access to the associated email address using Token method
2) Prompted that multiple accounts exist
3) Customer selects which account they would like to access. Is provided information like open tickets and company name.

![image](https://user-images.githubusercontent.com/30588784/66284692-8242fa00-e925-11e9-9cc6-b5dfaf60cd84.png)

**Comment by cdandrea** [comment]
Is this similar to an existing request #258

**Comment by Andrew-Lahikainen** [comment]
@cdandrea work has started on that issue, just mentioning you here since it appears you commented on #258 on another Github account

**Comment by Andrew-Lahikainen** [comment]
This has been completed in the new sign in page. See docs here: https://deskdirector.helpdocs.io/article/py9m7qwhuv-sign-in-to-desk-director
