### ISSUE TITLE
DD Tech: Add ticket link to email when adding a form to a ticket

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#385]
I love the option to add a form to a ticket to get more information. The email notification that gets sent to the user however, doesn't show the form (of course) but also doesn't let them know that either:
- They need to open the app to view the form
- (Ideally) They need to click on a link to get to the ticket in the portal.

I think both things should be stated so that a user knows what they have to do next with that ticket.

**Comment by Nness** [comment]
I'm on my task to release next admin portal. It should include customized sample you can import for inline form email template. It should be released within next few hours.

**Comment by Nness** [comment]
Admin portal is now under DI for release, below you can find latest changes. Ticket link is also contained within inline form template sample which you can import.

It should generally available within an hour.
-----------
* Fix - material icons link under menu item edit page is incorrect
* Enhance - Email template's error page now always accessible. 
* Enhance - Email template's error page now always display count
* Enhance - Email sample now can be branded
* Enhance - Forms search list now retain query history inside browser history.
* Enhance - Inline form's email template preview now have sample data to enhance the result
* New - There is now contacts search and list page under company page
* Enhance - Contacts search and list page now restyled and with new capability on filter by company.
* Enhance - Quick link to remove contacts search and filters.
* Enhance - Contacts page now retain query history inside browser history
* New - Add Knowledge base article site link to the side navigation bar

Up coming changes - currently under development mode (require server - 18.96.1)
* New - Request types that uses this form page under a specific form 
* New - Request types that uses this form count on forms list
* Enhance - Restyle of menu item creation page and edit page. It also include capability to use notebook inside menu item.

**Comment by Lowell-Syncrety** [comment]
So we just tested this... We added a form to a ticket that I own, and I just got this sentence in the email: "We need more information from you for ticket below." It shows the ticket information below in the email but there's no link to the ticket, no link to the form, no instructions to log on (or go to the app) to fill out a form. Am I supposed to be setting something up for this to work?

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety this article sort of goes through how you can enable a template for this email:
https://help.deskdirector.com/article/uyzo7l6lzw-html-email-templates-desk-director

It goes through how to enable the sample template for Approval Required, but you can do the same steps for Forms Request, just import the sample and enable the template.

Let us know how that goes.

**Comment by Lowell-Syncrety** [comment]
OK, I'll check into that, thanks!
