### ISSUE TITLE
Login improvements

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#386]
This issue is created regarding to several login related issues or improvements. We will attempt to resolve them all together in near future.

* First time login, create password or contact #133 
* Default login method #164 #373 #221
* Display message on unsuccessful login #299
* Highlight missing email on send login token #358
* Option to allow user change their password inside portal #367
* Allow choose the account to access during login #380

The improvements currently planned is two step login. 
1. Ask for email
2. Which platform to login into. 
    * Portal
    * TECH
    * Admin
3. Provide several login method
    * Password
    * Magic token (Password less)
    * OAuth (Office365 login)
4. On successful login provide account selection if given email is associated with several accounts.

**Comment by Fly-Kick** [comment]
Despite being sent here by support none of these seem to deal with securing access to the admin portal via MFA? Can this please be added?

**Comment by Nness** [comment]
@Fly-Kick You can treat OAuth(Office365 login) and Magic token (Email token) as MFA. The reason is access is controlled by service with very good security.

That means unless you can broke into Office365 account or mail account, else you cannot access our app. Where Office365 is supporting MFA and login USB stick, where email provider such as MSFT or Gmail also have very high standard on security.

**Comment by Nness** [comment]
@Andrew-Lahikainen 
API is under `/api/v2/auth/login/method?email=xxx`

Sample response is:
```
{
  "name": "Jason He",
  "email": "jason@deskdirector.com",
  "adminMethods": [
    "oauth",
    "passwordless"
  ],
  "techMethods": [
    "oauth",
    "passwordless"
  ],
  "portal": {
    "requireCreate": false,
    "methods": [
      "reset-password",
      "passwordless",
      "oauth"
    ]
  }
}
```

Let's also handle `redirectUrl`. For OAuth, redirectUrl should recorded in state. Also where he try to login. 

There might be few adjustment we need to make inside OAuth API. Let's explorer first. Keep me and Andy updated on anything you have encountered. 

Release of this page can be on new release system. I will find time to adjust it.

**Comment by Nness** [comment]
I couldn't reproduce the issue for [initialize code](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/app.module.ts#L47-L54) try to resolve. 

I believe, angular will only navigate to base path when path is not match. 

e.g. page landed on `localhost:4200/test2` where base URL is `/test1`, then angular will navigate from `/test2` to `/test1`. If this is the case, then it is related to baseURL setup issue, we shouldn't put those code there to fix infrastructure issue, where future reader could be confused.

**Comment by Nness** [comment]
It is best to combine request with operation, else there is no way to guarantee the outcome. [improvement](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/services/auth-repo.service.ts#L26-L43)

When we combine into single task, there won't be case where future developer forgot to update one of field inside `AuthRepoService`. Since there is no relationship between `private email?: string;` and `private userRes?: HttpResult<ApiErrorResponse, User>;`

Especially with old code it is vulnerable to concurrency. One of common issue is, request 1 could finished after request 2. It override the latest result. 

Other concurrency vulnerability is related when to define email field. If you or any future developer assign email before await, then by the time await is finished, email could be different already.

e.g.
```JavaScript
this.email = email;
result = await getmethod();
this.result = result; // << race condition
```

When combine request and process together, it is impossible to have such accident.

**Comment by Nness** [comment]
Avoid use complex inline method as much as possible, readability of code is very low. Especially with async method e.g. [paramMap.subscribe](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/components/select-platform/select-platform.component.ts#L35-L71)

For simple mapping or find index functions, inline function is good option and should be used. Where code is complex and result large chunk of code inside inline function body, it makes original method so fat that's hard to read.

One of issue I had in rxjs code was this as well. A single method expand nearly hundred line of code, inside have so many different kind of links, nested functions etc etc. I don't event want to read it.

**Comment by Andrew-Lahikainen** [comment]
@Nness initialisation code preserves query parameters. That's it. Angular consumes them on app startup and you cannot access them through their queryParamMap.

**Comment by Andrew-Lahikainen** [comment]
I'll add a comment to clarify why this is being done

**Comment by Andrew-Lahikainen** [comment]
Good call on authrepo changes.

For inline method critique, I disagree that it hurts readability. Jumping around different functions can be just as hard to read if not more so if they also mutate shared state. But of course I'll keep that in mind when contributing to DD repos.

**Comment by Nness** [comment]
I cannot reproduce for `paramMap`. What I did is:

```
// removed whole provider
router.navigateByUrl(`${path}${url.search}`, {
   queryParamsHandling: 'merge',
});
```

Setup dev environment to have base URL to be `/test/`, then navigate to `http://localhost:4200/test/email/jason@deskdirector.com/platforms?test=` and then refresh etc. It still there.

Do you mean `paramMap` doesn't contain that param?

![image](https://user-images.githubusercontent.com/1712143/82767431-a3883480-9e7b-11ea-886e-58238c545c4c.png)
![image](https://user-images.githubusercontent.com/1712143/82767436-aaaf4280-9e7b-11ea-91e6-5391039a86c3.png)

**Comment by Andrew-Lahikainen** [comment]
@Nness oh yeah, you're right - this code isn't apparently needed. Maybe at some point I was doing a navigation without setting all the right queryParam preservation options and it was just removing my queryParams.

I thought it was related to this: https://github.com/angular/angular/issues/12157

**Comment by Nness** [comment]
For inline function, when inline function have so many code inside, it makes reader wonder, which code is from original method which is inline. If that make sense. 

When reading, you have to concentrate and create an in human brain scope says, this section of code doesn't belong to this method. Thus, the larger that inline method is, it is harder to track on what is going on.

Especially I have to first figure out where this inline method ends.

**Comment by Nness** [comment]
I actually remember issue angular/angular#12157  . It was an issue that I have to dealt with. I thought it apply to both initial load and in app navigate. Since it says it is served by behaviour subject. I was assume when it initialized for ActivatedRoute, it is always empty, either in app navigate or initial load.

Good to see that this is now fixed.

**Comment by Nness** [comment]
Different way to write [signin.component.html](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/components/signin/signin.component.html) is:

```HTML
<ng-container *ngIf="!error; else errorBlock" [ngSwitch]="method">
  <app-oauth-signin *ngSwitchCase="''"></app-oauth-signin>
  <app-token-signin *ngSwitchCase="''"></app-token-signin>
  <app-password-signin *ngSwitchCase="''"></app-password-signin>
  <app-password-reset *ngSwitchCase="''"></app-password-reset>
</ng-container>

<ng-template #errorBlock><p class="text-error" *ngIf="error">{{ error?.message }}</p></ng-template>
```

I haven't change the code, it is small improvement. 
* if else avoid multiple check.
* switch also avoid multiple check, so angular knows children only depends on one parameter.

**Comment by Nness** [comment]
Here is [fix](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/components/oauth-signin/oauth-signin.component.ts#L132-L134) for OAuth redirect URL. It was not working with `baseUrl` scenario.

`location.path()` that's provided by Angular can give you current path, then `location.prepareExternalUrl()` method can help you extend base URL. On top of that, use `Location.joinWithSlash` to combine with host. 

That way, you can get accurate URL based on your current location.

----

To simplify OAuth-Signin component, I would suggest to split into two component.
* trigger sign in component
* resolve sign in result component. 

That way it is more specific and logic can be simpler. e.g. trigger sign in only have to monitor path, and only have to trigger once per initialize.

Both component you don't necessarily have to `subscribe`. Either initial snapshot have session ID or doesn't have session ID. It will never be a case you need to observe. 

Of course, unless angular is bugged like it was at 2016, where first parameter map is empty.

**Comment by Nness** [comment]
[optional oauthApi](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/components/oauth-signin/oauth-signin.component.ts#L41) This injection is kind of dangerous. 

It is optional parameter, where you did [check whether platform is valid](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/components/oauth-signin/oauth-signin.component.ts#L71-L74). Which is good. 

The problem here is there are multiple responsibility. 
* query and route change monitor that's checking platform
* injector that pass in correct `OauthApi`

None of them can ensure if one is true the other is also true. I know in theory it does but two are handled by completely different code which hold responsibility separately.

My suggestion would be, instead of inject `OauthApi`, use resolved platform to get `OAuthApi` from `ApiService`, then pass into `handleCreateSession` method.  That way, you know by the time inside `handleSignInClick`  the `OauthApi` will never be null.

**Comment by Nness** [comment]
In OAuth, you can inject `window` or `location` without direct access. [code](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/components/oauth-signin/oauth-signin.component.ts#L163). 

I know I have been lazy on logging,where I directly use `console.log`. For inject `window` or `location` might be better.

Not huge issue, since comopnent should never be used under web worker environment. It is just my habit since angular 1, where I try to inject it instead of directly use it.

**Comment by Nness** [comment]
Do we need to specify [Stay signed in for 60 days](https://github.com/DeskDirector/universal-signin/blob/master/projects/signin-app/src/app/components/password-signin/password-signin.component.html#L23)?

If we ever change that value, we have to change login page as well. Isn't `remember me` a wording that's commonly used by every login page?

**Comment by Nness** [comment]
@Andrew-Lahikainen review is done. Some of change I have made and uploaded.

Not all the suggestions been applied. Only did one fix and one bundle request with process task.

**Comment by Nness** [comment]
@Andrew-Lahikainen by the way. Since yesterday's server 18.121.1's release, all server now has this new API.

```
POST https://xxx.deskdirector.com/api/v2/auth/remember_me
```

* 401: Unauthorized
* 204: No content when success
    - It will return back set cookie header with 204. Convert all DD related cookies to permanent.
    - Set cookie won't extend expire time, expire time will be original expire time. e.g. if an cookie expire in one hour, use this won't cause it to change to 60 days. It will still be one hour.

**Comment by Nness** [comment]
@Andrew-Lahikainen forgot one thing. Login page, many images or material UI's icon take time to load.

There are many flickering when navigate inside app. 

* TECH icon not yet loaded, and the width is zero, where admin and portal icon display. Looks weird.
* Login method width will be so wide before font has been loaded. 

I would suggest for material icon, setup static width or give max width property. Another way to resolve is SVG, since you only depends on 2~3 SVG. 

As for TECH icon, consider mobile view to give minimum width or set static width.

**Comment by Andrew-Lahikainen** [comment]
@Nness Thanks for the review

One thing I didn't want to change is the subscriptions to paramMaps since angular will not reinitialise components when routing if it routes to the same component. I previously did use snapshots, but this lead to problems with the password and password reset components since they link to each other. I know I can change the route structure to avoid this. I'm pretty sure we can also force Angular to reinitialise components on all route changes. Maybe we should consider this if we want to avoid observables altogether.

For the "stay signed in for 60 days" message, I think this is far more clear even if it does require a change if we change our cookie policy. Remember me doesn't really mean anything concrete to me and every implementation might differ. I'd wager that more sign in pages these days have a similar such message than the generic "remember me" one. One way to manage this would be to create a cookie policy I can query from the front-end that I can use to create the message. You could also reference this policy when instantiating the back-end's cookie middleware so that everything is consistent.

I wasn't sure what you meant about

> Login method width will be so wide before font has been loaded.

I don't see this (I do see the flickering).

**Comment by Andrew-Lahikainen** [comment]
@Nness just had to sign in to Sharesies again and the use "Stay signed in". As a user this feels like a bad experience. Every time I log into Sharesies I tick that box, but every unknown amount of time later I'm asked to log in again. What the hell? So it doesn't do anything? Huh!? That's how I feel as a user who doesn't know about cookie expiration etc.

**Comment by Andrew-Lahikainen** [comment]
@Nness Asb's remember me checkbox does something totally different:

![image](https://user-images.githubusercontent.com/10571313/82847046-ffb48c80-9f3f-11ea-8ca9-5654471d9458.png)

**Comment by Nness** [comment]
ASB and ANZ's web portal have security hole everywhere. I don't think they can be an example.

Remember me as common phrase, the meaning is concrete. [IBM](https://www.ibm.com/support/pages/inactivity-timeout-or-remember-me-or-session-timeout). 

Remember means it will keep session as you reopen browser. 

You can use tooltip to express the detail information. `stay signed in for 60 days` is not common language that login page uses. Even session cookie is true  for `stay signed in for 60 days`. As long as they didn't close browser.

What I am refer here is `Don't make me think`. Remember me is common language for web site login, every knows what it means. `ASB` against original meaning, that's why they add tooltip. This is bad experience.

**Comment by Nness** [comment]
I'm not sure if you understand my message correctly, for not use subscribe and use snapshot is based on different route and different component. 

What I have said is, consider use different route and different component, in terms of simplify the logic. Where one component only deal with create login session the other deal with return back process.

In that way, logic can be further simplified by snapshot. So by use snapshot is based on route and component split.

**Comment by Andrew-Lahikainen** [comment]
With respect, security holes or not - the behaviour differs. Users use these websites, they also use ours. Therefore there is a difference in behaviour between websites. People do not read IBM papers on what the phrase "Remember me" means.

**Comment by Andrew-Lahikainen** [comment]
Office 365 uses an explicit message now when signing in, so does New Relic, so does any app with a focus on security.

**Comment by Nness** [comment]
Office 365 only said don't ask me again in 60 days for 2FA. Nothing to do with remember me. 

This for OAuth
![image](https://user-images.githubusercontent.com/1712143/82847368-d432a180-9f41-11ea-9ea6-ffeb98b42096.png)

This for cookie session
![image](https://user-images.githubusercontent.com/1712143/82847415-16f47980-9f42-11ea-9ad8-8ef6a4c69732.png)

**Comment by Andrew-Lahikainen** [comment]
@Nness I understood that concept re: snapshots. I was kinda referring to a specific case I had where navigation can occur between the password component and the password reset component which lie at the same path.

**Comment by Andrew-Lahikainen** [comment]
@Nness nice message by MS right?

**Comment by Nness** [comment]
For other cases, if subscription needed is need. Only thing I said was to move the logic out to an method for easy read.

As for OAuth, I said split component to simplify the logic.

**Comment by Andrew-Lahikainen** [comment]
Yep got it

**Comment by Nness** [comment]
They never said cookie will expire in 60 days. Read carefully. It only apply to remember this machine on 2FA. 

For cookie it said, Stay sign in.

**Comment by Andrew-Lahikainen** [comment]
I know. Still - nice message?

**Comment by Andrew-Lahikainen** [comment]
Basically I'm asking whether you would prefer a message like that, rather than explicitly writing the number of days. We now have the api to set a persistent cookie.

**Comment by Nness** [comment]
I don't want to make promise on 60 days.

**Comment by Andrew-Lahikainen** [comment]
So, do you like the way Microsoft does it? We can do the exact same thing now.

**Comment by Nness** [comment]
Sure, just don't say 60 days. Just express the sign in session will last after browser restart. Whether 60 days or not could change anytime. I don't want to make such promise

**Comment by Nness** [comment]
I don't want to receive any ticket asking, why session expired early. We expire when it is on schedule or anytime we feel like to. It is the security promise we given to end user. We expire early if needed. 

There could be firewall or others remove cookie too. 

2FA is slightly different, Microsoft try to keep browser's query as finger print. Combine IP with browser header to say this PC's this browser requested 2FA before, so I don't ask them again for 60 days. 

Cookie cannot achieve that.

**Comment by Nness** [comment]
I know it is shit from user point of view, but it is something we use to protect ourselves. Since we can only achieve to tell 3rd party to keep cookie. Whether they keep it or how they keep it. We don't have anyway to guarantee. If we can guarantee, sure, give promise.

This is similar as Andy and I making change today to make sure email auto login token is not send out by default this week and introduce a flag. We don't want to make promise that we cannot keep. 

Things may change in the future, I'm not in a position I want to make promise on cookie length yet.

**Comment by Andrew-Lahikainen** [comment]
I understand that, I think the message Microsoft uses is a good one. It suggests that you will still be asked to login again at some point, just not as much.

**Comment by Andrew-Lahikainen** [comment]
@Nness all requested changes have been implemented 👍

**Comment by Nness** [comment]
Awesome, I will check later today and will see if we can include in this week's server release.
