### ISSUE TITLE
DD Forms: Don't pre-populate required fields

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#388]
So the special "Summary" field is present on every form (wish we had the choice), and is a required field. But it's already pre-populated with the name of the form. So for example, we have a "High Priority Request" form. I don't have a secondary "Description" field because the summary should be enough. But then customers aren't forced to update the Summary field because there's already text in there, "High Priority Request".

If anything has to go in here can it be one of those fields that has greyed-out suggested text that isn't really filled in but disappears when the customer starts typing in there? Maybe I have to look at the new dynamic title function; not sure if that helps here.

**Comment by Nness** [comment]
For your high priority request form title, I believe is populated by request type's title template. You can remove that, so the initial summary is empty.

Below is your high priority request type. You see that title template? If you remove that, it shouldn't populate the summary field.
![2019-11-06_09h11_07](https://user-images.githubusercontent.com/1712143/68242436-5f674b00-0075-11ea-9f0e-d1e26efe0577.png)

**Comment by Lowell-Syncrety** [comment]
Thanks @Nness that's helpful.
