### ISSUE TITLE
[20651] Include ticket summary on Status Update Notifications

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#389]
![image](https://user-images.githubusercontent.com/30588784/68175956-d35b1200-ffe7-11e9-8c20-6cea8143e1da.png)

Feature request to include some/all of the ticket summary rather than the ticket number.

This is to better inform the customer without the opening the portal to see which ticket "61781" is.

**Comment by Andrew-Lahikainen** [comment]
@Aycorn This has been completed and will be deployed next week.

**Comment by Andrew-Lahikainen** [comment]
Deployed
