### ISSUE TITLE
HTML template engine for Email

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#39]
This template engine should be for following emails.

* Approval related
* Reset password
* Passwordless token

**Comment by Aycorn** [comment]
I believe this is done with the introduction of [Email Notifications](https://help.deskdirector.com/article/f9ghog7q3i-get-started-with-email-notifications) and [Custom Email Templates](https://help.deskdirector.com/article/4n8f0085bf-custom-email-templates).

Closing.
