### ISSUE TITLE
[20847] Profile Images not displaying

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#391]
When a profile image is uploaded in Portal, the image is not displaying next to the Time Entries/Notes, instead it is just showing the tech's initials.

Can confirm same for both web and app.

**Comment by Andrew-Lahikainen** [comment]
This is only a problem for tickets v2, which is still in beta (very nearly complete though). It's already implemented on our dev branch and will be deployed today to everyone.

**Comment by Andrew-Lahikainen** [comment]
Fixed and deployed
