### ISSUE TITLE
Collapse Admin Console Side Menu

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#401]
Add the ability to collapse the Admin Console's side menu.

Example below when trying to work with multiple side-by-side windows at a smaller resolution.
This area takes up a lot of screen real estate.

![image](https://user-images.githubusercontent.com/30588784/69921932-70c43b80-14eb-11ea-9742-e33093ffa01c.png)

**Comment by Nness** [comment]
How smaller is smaller? Do we have any specifications?

From design specifications for admin, it is not for mobile, maybe for tablet if task is simple. It is designed for desktop.

**Comment by Aycorn** [comment]
The scenario is a single monitor user with 2x DD Admin Console windows open side-by-side. This would be 2 960x1080 windows.

My thoughts would be to have the parent menu icons display, and the menu pop out with options on hover:

![image](https://user-images.githubusercontent.com/30588784/70571390-ea49e100-1bf1-11ea-992c-5f77c397b241.png)

This is a request to have an option for the side menu to collapse/hide. This could be automatic based on screen resolution horizontal ratio, or a collapse button.

**Comment by Aycorn** [comment]
The admin console has since introduced a collapsed menu with supporting burger option to expand as needed at smaller resolutions
