### ISSUE TITLE
[21263] Additional Email Address CC from DD Form

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#404]
Feature request to specify an additional email address within DD Forms to be added on a ticket.
This email address will shows against the "CC" section of a ticket in ConnectWise as an example.

![image](https://user-images.githubusercontent.com/30588784/70878572-24fab180-2016-11ea-971f-da874ca426f3.png)

**Comment by Nness** [comment]
Close this as it is same for #93 #346
