### ISSUE TITLE
"Add Note" as default behavior for ticket statuses with Time Entry disabled

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#410]
If a status has "Time Entry Not Allowed" enabled, the current default behavior is to load the Add Time Entry tab and display the message _Cannot add time on the current status_

Suggestion to change the default behavior of any status that cannot enter time to the Add Note tab instead.

This eliminates an extra step for Techs / Professional Service Members and provides flexibility for members that don't need to enter time without impacting a Member who logs time.

**Current Behavior:**
Can log time on status? Add Time Entry Tab > Add Note
Can't log time on status? Add Time Entry Tab > **Change Tab** > Add Note

**Expected Behavior:**
Can log time on status? Add Time Entry Tab > Add Note
Can't log time on status? Add Note Tab > Add Note

![image](https://user-images.githubusercontent.com/30588784/72851743-965a0e00-3d00-11ea-90b7-a5ad1dfabf6c.png)

![image](https://user-images.githubusercontent.com/30588784/72851753-9ce88580-3d00-11ea-9bae-537ddf640654.png)

**Comment by Nness** [comment]
I believe this has already been addressed.
