### ISSUE TITLE
DD Tech: Search and select Status as user types it in

### ISSUE THREAD

**Issue by Lowell-Syncrety** [DeskDirector/UserVoice#420]
When changing the Status of a ticket in DD Tech we have to manually scroll up and down to find the one we want (they aren't organized alphabetically, as we order the statuses by most used). We'd like to be able to just start typing a status and have it go to the next most likely one.

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety I've added a status filter and I've also implemented status sorting based on ConnectWise's sort field.

I'll mark this as closed as I think it will resolve your issues. Tech is rolling out now, so expect your instance to have the latest version in around 5 - 15 minutes from the time of this message.

**Comment by Lowell-Syncrety** [comment]
Nice! Thanks! It works, and also works for any term inside which is nice, as we start some statuses with a star or bracket.
