### ISSUE TITLE
[23043] Disable Office 2010/2013 video within BiggerBrains

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#424]
![image](https://user-images.githubusercontent.com/30588784/74299562-27bd1d00-4da1-11ea-9fef-37a8efa97621.png)

Change request to have the most recent videos display for customers within Bigger Brains.

**Comment by prysmcorp** [comment]
Yup. The majority of customers are no longer using these outdated versions of Microsoft Office. Does DD cache these or are they pulled directly from BB? May be a harder ask if you guys are simply "reading all" from BB.

**Comment by Nness** [comment]
We are pulled directly from BB

**Comment by Nness** [comment]
Office 2010 been disabled, while 2013 remain. Office 2013 extended support end on April 11, 2023

**Comment by Aycorn** [comment]
This request has been actioned by the current availability of 2010/2013 courses in DD Admin Console under BiggerBrains.
