### ISSUE TITLE
DD Tech doesn't refresh Boards total when loading the Tickets page

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#426]
- Boards and Status count is 1
- Load into the ticket
- Close the ticket
- Select **Tickets** from the top left
- No tickets displayed, however Boards total still shows as 1 until Refreshed

Expected Behavior: Boards total is refreshed when loading the Tickets page

![image](https://user-images.githubusercontent.com/30588784/74692075-af8ba700-5239-11ea-82a1-07db3e967451.png)

**Comment by Nness** [comment]
This is not user voice but issue. I have addressed it. It should be on `staging` now.

`/tech/staging`
