### ISSUE TITLE
DD Tech doesn't show which ticket is in which status while a board is selected

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#427]
In the screenshot below I have 2 active tickets.
1 is in a waiting status, the other is in an escalation status.
With a board selected from my filters, I have no indication which ticket is in which status from the ticket overview panel:

![image](https://user-images.githubusercontent.com/30588784/74692467-663c5700-523b-11ea-834d-216b2a017212.png)

**Comment by Nness** [comment]
It is mean to use status facet. too much info . this won't be considered. 

Worst case is make board not selectable or auto select status.

**Comment by Nness** [comment]
If you feel either not selectable or auto select default or first status, then open another user voice. Or change exist one and reopen it.
