### ISSUE TITLE
[11430] Sort by status

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#43]

**Comment by Aycorn** [comment]
Additionally raised on ticket: Service Ticket #11430 - New Tech Portal Question

**Comment by Nness** [comment]
This won't be implement as sort on status. It will be implemented in different form to help navigate around for tickets under different status.

**Comment by Andrew-Lahikainen** [comment]
This has been implemented and deployed. Sorting by status is possible, as well as status grouping under boards.
