### ISSUE TITLE
Export contact filter

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#437]
I think this functionality was available in a previous release.
Feature request to add an export to CSV option while filtering contacts within the DD Admin Console.

![image](https://user-images.githubusercontent.com/30588784/75827445-d16e5780-5dfd-11ea-956a-252f4c07edd7.png)

**Comment by Aycorn** [comment]
![image](https://user-images.githubusercontent.com/30588784/75827511-fbc01500-5dfd-11ea-9bdf-c98ae7f0a179.png)

![image](https://user-images.githubusercontent.com/30588784/75827519-fd89d880-5dfd-11ea-8d7e-59c58c939246.png)

**Comment by Nness** [comment]
I'm not sure what's the use case, I created export functionality because at one stage I have removed permission filtering. Now the permission filtering is there.

**Comment by Aycorn** [comment]
@Nness this was useful to provide reporting and pivotable data within Excel to members without Admin Console access.

**Comment by Nness** [comment]
next admin console release should have this.
