### ISSUE TITLE
[9246, 10897] Add way to group tickets by board and then by status

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#44]
API already exists for this feature, we just need to come up with a suitable design for TECH. We had some really rough designs a while ago. I'll leave them here to give a better idea on what this feature is.

![image](https://user-images.githubusercontent.com/10571313/41516383-80e98c3a-7308-11e8-9ed3-654c5d1a634d.png)

![image](https://user-images.githubusercontent.com/10571313/41516387-89c56c02-7308-11e8-800e-7eaa33171c27.png)

![image](https://user-images.githubusercontent.com/10571313/41516415-ba4fc9c6-7308-11e8-92e3-dd7b9f546dec.png)

**Comment by bobsquid** [comment]
Is this just referring to TECH?  

I'd love to allow this functionality on the DD portal as well, so the end user can sort and filter by board and status (i.e. service tix vs project tix, in progress vs waiting for customer, etc)...

**Comment by Andrew-Lahikainen** [comment]
@bobsquid this is just referring to TECH. If you would like to see this in Portal can you create another feature request? What would be really handy is if you describe the problem you're experiencing with the current Portal which makes this feature necessary for you. You can also describe what types of Portal user this would be useful for. Do you see it as important for *all* Portal users, or technical contacts, or managers etc?

**Comment by bobsquid** [comment]
I was asked to create another feature request as this one was just for TECH.  Why was that request moved here?

**Comment by Andrew-Lahikainen** [comment]
@bobsquid is this what you're referring to? https://github.com/DeskDirector/UserVoice/issues/100

It hasn't been moved!

**Comment by bobsquid** [comment]
Okay I see, sorry about that!







  [cid:SIG-Pace_8cec8766-e136-4573-a78e-d5a13ed878ed1111111.jpg] <http://www.pacetechnical.com/>


Jay Da Costa
Director of Service Delivery
905-763-7896 x226


[cid:SIG-Great_55f3a646-6146-45d5-ba1c-023fd59406b41111111.jpg]<https://www.greatplacetowork.ca/en/best-workplaces/best-workplaces-in-canada-small><http://www.greatplacetowork.ca/>


[https://web.crewhu.com/external/v1/dashboard/csatWidget/59afff2ba89e9251839a8abd]


[cid:SIG-msp_00fb0681-886b-424b-abb2-1cc5a88c12971111111.jpg][cid:SIG-mspartner_479d07c5-a784-4b62-8641-3a2089a2c5f61111111.jpg]






-------- Original message --------

**Comment by Andrew-Lahikainen** [comment]
We've started exploring some designs for this new screen:

tickets by board:
![web 1920 2](https://user-images.githubusercontent.com/10571313/44701768-6a733280-aae4-11e8-8309-c9e8fa4f22c4.png)

creating a view:
![web 1920 3](https://user-images.githubusercontent.com/10571313/44701783-7bbc3f00-aae4-11e8-9680-f06eac89831a.png)

Still need to explore how this design would fit in with the ticket details screen since it's quite a large change in how the app works.

**Comment by Andrew-Lahikainen** [comment]
This has been released. Views will be looked at later.
