### ISSUE TITLE
[21844] Dynamic Menu Item URLs

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#441]
Feature request to include dynamic content in the Menu Item creation:
![image](https://user-images.githubusercontent.com/30588784/77608133-74833e80-6f70-11ea-9b35-ff6849df8f86.png)
Example above, passing through a ConnectWise variable before a URL is loaded for the customer.
Could look into using existing subset of Deeplinks rather than PSA variables: https://help.deskdirector.com/article/rb70qsabfd-portal-deep-linking

**Comment by Nness** [comment]
It is already passing into URL before the website been hit. You can try it. 

The only thing you have to be aware is additional info are inside query parameter. instead of route.
