### ISSUE TITLE
Add menu item deeplink support

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#447]

**Comment by Lowell-Syncrety** [comment]
I'm not sure what this means, but it sounds cool. What's the goal of this request?

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety this is for the custom menu system (the one you can turn on inside feature preview in the admin portal).

It basically allows you to create a permanent link to navigate to the menu item page. This is useful for email templates and stuff. You can read more here: https://help.deskdirector.com/article/rb70qsabfd-portal-deep-linking
