### ISSUE TITLE
Improve ticket search UI

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#45]
At the moment, it's unclear why the search is matching a certain ticket.

**Comment by Andrew-Lahikainen** [comment]
This wasn't actually started. The search term for tickets can match on description, and currently the description is not displayed on the ticket list items.

This would need some more design.

**Comment by Aycorn** [comment]
Closing: I believe this has since been improved, see [How search works in DeskDirector products](https://help.deskdirector.com/article/09gt8a3cb2-how-search-works-in-desk-director-products) as reference.
