### ISSUE TITLE
[19445] Approval email send to approver individually and include login token

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#459]
When sending out approval required email. Email often send to multiple approver at once. In this way, it is impossible to apply auto login token.

To achieve auto login token, it require system to send email to individual approver separately.

The difficulty at moment is infrastructure, since individual mail require separate data source and construction. The memory and process impact could be something.

Reserve here as backlog for future. Until we move our server from .net framework to .netcore or .net 5. When performance been hugely improved.

**Comment by jameskirsop** [comment]
Was this actioned, or closed without change?

**Comment by Nness** [comment]
implementation finished, deployment will be by end of Nov or around Dec. As it's implement on v19. There is database migration planned. If you want it early, create support ticket and let us know.
