### ISSUE TITLE
[22706] Allow ConnectWise/Autotask portal user to login with alternative email

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#464]
ConnectWise contact can have multiple email registered. It could be good for them to login with alternative email.

It should also allow them to switch account if alternative email is same for other contact.

**Comment by justinDJC** [comment]
Please!

**Comment by justinDJC** [comment]
Further to this - Wondering if a this would be the same or a different issue.

Could alternative email be used in additioan to primary email to detect users across multiple companies, and enable the Switch Account feature?

Having a contact with the same email address on two companies breaks the EMail Connector in ConnectWise, it doesnt know who to attribute the email to. However it's required for DD to link users together to allow account switching!

**Comment by Nness** [comment]
This has been implemented and will be general available by 1st of Sep. Change below apply to both CW/AT

- User able to login into portal with alternative email
- User able to switch account/company with alternative email
