### ISSUE TITLE
[23374, 25525] Different sending email accounts per board

### ISSUE THREAD

**Issue by akkibhat** [DeskDirector/UserVoice#469]
"Each one of our service boards has a different email address so can we customise it so the email is sent from the correct email address? We are not able to receive email replies into the service boards otherwise."

Enable different sending email accounts per board

**Comment by iskolares** [comment]
Related ticket #25525

**Comment by Aycorn** [comment]
I believe this is now supported using [Notification Events](https://help.deskdirector.com/article/rgbtfi6xj9-setting-up-email-notification-events)
