### ISSUE TITLE
[9246] Add weekly and possibly monthly view to schedule view

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#47]

**Comment by Lowell-Syncrety** [comment]
Yes, this would be great. Plus the ability to customize the time increment to 15min like we can do in Outlook. This is a long, long standing complaint with CWM. 95% of my activities are less than 15min (mostly sales or dev items) but they cram over top in Schedule, and mash together in CWM. For service folks that's less of an issue but still they often have short ticket schedules, a phone call, a follow-up, etc. that is 15min or less.

**Comment by Aycorn** [comment]
The Scheduled Panel is now a deprecated feature and will not receive future development efforts.

> **Deprecated Panels**
> Enable ConnectWise Schedule Panel

Closing.
