### ISSUE TITLE
[23320] Timestamps on ticket list to show last updated instead of created date

### ISSUE THREAD

**Issue by akkiogra** [DeskDirector/UserVoice#470]
Time stamps on the Ticket List page. Essentially, seeing a description of the ticket really isn’t that important to our techs as that’s the primarily the summary/subject’s job. And we will see the ticket description once we open the ticket. What we’d prefer is a time stamp on the ticket summary of the last status change or if a client or tech responded last. To us, knowing if someone responded/when at a glance is far more important.

**Comment by Nness** [comment]
it is latest responds, not description.
