### ISSUE TITLE
[23320] Add "Unassigned" to ticket filter options

### ISSUE THREAD

**Issue by akkiogra** [DeskDirector/UserVoice#472]
In the Ticket Filter we’d love to be able to filter by tickets that are unassigned only as a first step. This is very handy for techs in general to make sure they are assigned correctly and quickly without having to scroll through possibly dozens of pages. This also would make a dispatcher role, significantly easier.

**Comment by dustinabingham** [comment]
Not to mention, for teams or remote providers who do not have the dispatcher model.

**Comment by Nness** [comment]
This has been implemented with #471. It will be deployed on Jan 2021. Check #471 for more detail.
