### ISSUE TITLE
[23328] Contact Permission Bulk Updates

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#476]
Making permission changes to a large sub-set of contacts currently requires going into each contact's permissions tab individually.

Feature request to have a "bulk" permission update option available from the Contacts page:

![image](https://user-images.githubusercontent.com/30588784/91246158-4914b200-e7a3-11ea-8591-ed82707c355a.png)

DD Admin Console currently has the option to select contacts within the list, I would envision selecting contacts using the check boxes available (screenshot above) and having the option to Update Permissions.

You can could use this in tandem with the current "config permissions overwrite" filter to quickly update a large amount of contacts.

**Comment by Nness** [comment]
This has been implemented and released with admin portal 1.29.3 release.
