### ISSUE TITLE
[23644] DD Tech - Dynamic Page Title with Ticket Summary/Number

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#483]
Using Chrome as an example, the current page title is "DeskDirector Tech":
![image](https://user-images.githubusercontent.com/30588784/94203773-20074e80-ff14-11ea-8878-ce3d683fa28c.png)

Feature request to have this dynamic, using the ticket number/title in focus if available.
![image](https://user-images.githubusercontent.com/30588784/94203959-78d6e700-ff14-11ea-937d-3015b11313dd.png)

The alternative to this would be a "Open in new DD Tech Tab" shortcut. This would allow Techs to load multiple tickets at once.
This would utilize the existing functionality of the "Go to ticket" feature:

![image](https://user-images.githubusercontent.com/30588784/94204155-d834f700-ff14-11ea-9b32-8a06c7549ccd.png)

**Comment by DevanMorrison** [comment]
Upvoting & commenting. This is huge for several reasons --

1. The new DD tabs aren't really user intutitive. When you click the "+" it asks for a new ticket number. On an MSP side, I'm not going to memorize or go over every ticket number for several clients when say, responding to network outages from an ISP side, or a server going down & we're working on mass communication thru tickets.

2. The workaround suggested doesn't even work correctly as listed. If you enter a Go to Ticket, it opens up the new ticket in the current window, replacing the current ticket -- hence no multiple tickets to even look at.

**Comment by Nness** [comment]
Do you guys know tab can be pinned?  If you pin then go to new ticket then previous will remain. 

Pin button is there. I might change icon later to make it more obvious.

**Comment by Nness** [comment]
Go to ticket is not designed for you to search. It is shortcut for when you know the ticket number. Such as people messaging you with number. CSAT negative review email notification with number. Etc etc. 

When you know company name and topic. Then ticket list search and filter is the place to go .

**Comment by DevanMorrison** [comment]
We discovered the pin folder about an hour later to see if it was a browser specific issue, etc. Better icon use would make more sense. We hadn't really looked at the folder with any thought in any prior time using the helpdesk over 6 months now.

For this workaround to open a new ticket above does not work in the above example then. Say an MSP has multiple tickets open for the same issue or multiple issues the tech is working on at once. I would have to open a ticket, pin it, click the tickets button to get back to the main dashboard, find the next ticket, open it, hit pin, etc. During times of high ticket volume or during outages, etc, this just adds extra clicks versus just using the browser, and hitting right click and opening a new tab while staying in the Tickets dashboard the entire time. 

I also see use case out of this for having multiple DD tabs open for multiple MSP sites. For example I could have a Chrome tab open for each DD site being managed to watch ticket queues going in to then assign resources, respond, etc. This setup natively as is basically forces the user to only have one tab for DD up and operate out of it. When some sites may have say 100 tickets, another 20, and another 5, being able to actively monitor, respond, and work multiple clients in separate interfaces would make sense on our part.

**Comment by Nness** [comment]
The way to organize tickets certainly not perfect. 


Personally I use browser tab more often. Any ticket I’m interested open in new tab from ticket list. If need long term monitor. Either pin it or assign myself then put under a specific status. 

I do have few ideas around but restructure TECH is not on high priority at second half year. 

Low hanging fruit I’m looking at moment is ticket list filter bookmark. That can solve some of problems.

**Comment by Nness** [comment]
I have created an article to help use of TECH portal. This is use latest changed I have made to TECH. Where browser tab now display ticket ID and name now.

https://help.deskdirector.com/article/1sbv8isl3v-tech-portal-how-to-take-advantage-of-browser-tab
