### ISSUE TITLE
[23674] Company and Technician filters on DD Tech Mobile

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#484]
Feature request to include the current Assigned Technician and Advanced Filter options for the mobile view of DD Tech:

![image](https://user-images.githubusercontent.com/30588784/94731730-c0042280-03c1-11eb-8a3f-daedff7020b6.png)

![image](https://user-images.githubusercontent.com/30588784/94731666-a662db00-03c1-11eb-8b70-ce46f8a07792.png)

**Comment by Nness** [comment]
Now you have this on 1.28.1. Release within 10 min if nothing goes wrong. Under CI/CD
