### ISSUE TITLE
DD Forms: Time Feature 

### ISSUE THREAD

**Issue by dr3dgen** [DeskDirector/UserVoice#486]
For our on/off-boarding processes, we've tried to utilize Forms as an all-inclusive approach. Sometimes people start with the company or leave at different times, so having a **Calendar** or **Date** option isn't quite specific enough. Right now I have a work around with a character limit of four and a limit to numeric characters for scheduled departure or arrival time, but it doesn't look very neat and it's not intuitive for the HR team using it.

Can we get a **Time** feature added to Forms?

**Comment by Nness** [comment]
This has been recorded in #486

This is under our backlog where we want to invest into. The earliest would be around Nov or Dec.

**Comment by Nness** [comment]
You can subscribe to #352 to get notified.
