### ISSUE TITLE
[23759] Post DD Chat logs as Internal or Discussion note, rather than file attachment

### ISSUE THREAD

**Issue by DDAndyChen** [DeskDirector/UserVoice#491]

**Comment by justinDJC** [comment]
Thanks Andy for creating a feature request for this.

I think it would really help with the user experience and also making using DD Tech for chat only (with a potential transition ticket management) smoother.

We currently don't use Tech, but are wanting live chat options - so having discussion info, including chat logs, readily available inside of ConnectWise with minimal hoop jumping and also to the end user the the Portal would be really nice.

**Comment by KennethVarrone** [comment]
I would love to have chat go to internal or discussion. This is holding me back from moving from CW Chat to DD Chat.

**Comment by DavidM-03** [comment]
> I would love to have chat go to internal or discussion. This is holding me back from moving from CW Chat to DD Chat.

Agreed

**Comment by Nness** [comment]
Current plan is to log as internal note but not display inside tech portal. Since tech portal already exposed it in timeline

**Comment by Nness** [comment]
This is done and in CI/CD. 

The behaviour is, log as internal note but not display inside TECH portal.

If history is more than 3100 chars, then it will also saved as attachment. (only save first 3100 chars).
