### ISSUE TITLE
[23904] Color Shading for Agent Collision

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#499]
A customer is asking if we can add enhancement to the DD Tech Portal Agent Collision, to add more visibility when someone is already working on a ticket.

Image as sample visualisation
![Screenshot 2020-11-03 102150](https://user-images.githubusercontent.com/13637718/97920532-76429980-1dbe-11eb-8c32-8c4ddef1b087.png)

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/97944195-8c198400-1de9-11eb-95e4-e1fb798c6b0d.png)
Added pulse.
