### ISSUE TITLE
Make more data available for macros

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#5]
Macros support the following tokens:

`{contact.email}`
`{contact.name}`
`{ticket.number}`
`{ticket.summary}`
`{member.name}`

We could add more. Currently available information:

`{contact.entityId}`
`{member.entityId}`
`{member.email}`
`{msp.name}` (hidden, for DD only)
`{msp.psa}` (hidden, for DD only)

**Comment by Lowell-Syncrety** [comment]
Is there any documentation on how to create and use macros?  Sound intriguing but didn't seem self-evident last time I looked at them.  I know this isn't a help forum, but if I set up some macros I might have some input here...

**Comment by Aycorn** [comment]
I believe [Macros](https://help.deskdirector.com/article/3cwyogd56c-getting-started-with-macros) now support all the original suggestions from Andrew.

Marking as closed.
