### ISSUE TITLE
[23897] Ability to remove (or not use) default system menu item on new menus created

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#500]
Currently, when creating new menus, the default system menu items can't be removed and is forced together with the new menu items clients will add.
![image](https://user-images.githubusercontent.com/13637718/98593094-89fa7c80-2337-11eb-9738-3dd833449831.png)

Can we allow removal of the default system menu item when creating new menus? This gives more control to the clients on how they want to customize their menu items.

**Comment by Nness** [comment]
user voice is not place to ask question.
