### ISSUE TITLE
Make sticky notification great again

### ISSUE THREAD

**Issue by OpsChris** [DeskDirector/UserVoice#503]
I have looked through the Knowledgebase articles and can’t seem to see a way of how to customise the main notification on desktops directing users towards a broadcast notification. 

It currently states: ‘There’s a notification from your service provider’ I’d like to change this from ‘service provider’ to the service providers name.

**Comment by Nness** [comment]
Differ to current poorly implemented sticky notification. Original sticky notification was desiged that you can see actual broadcast, and able to confirm the broadcast from the sticky panel.

Original spec was:
* Important broadcast should display as red themed message, and sticky forever until confirmed.
* Normal broadcast should display for 10~15 seconds then withdraw from the sticky panel.
* User can click confirmation button on actual sticky panel to confirm message
* Panel's title should be client portal's customized name.
* Panel's logo should be small, inline with title.
* Panel can display multiple broadcasts at same time

Existing implementation:
* Big logo flag with generic message that's not aware of the context. It could be chat warning, it could be broadcast.
* Only thing that's from original spec was stick.

**Comment by Nness** [comment]
Close this in favor of new desktop portal user voice.
