### ISSUE TITLE
[24018] Add option/button to 'quick copy' ticket number

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#506]
Currently, from the DD tech portal, the ticket number only appears on a linked button, making it difficult to copy the ticket number.

Customer is asking to add a ‘quick copy’ feature that allows them to copy the ticket number. Autotask provides 3 quick copy options for each ticket as seen in this screenshot:
![image](https://user-images.githubusercontent.com/13637718/99450152-3adec800-2985-11eb-90b3-d6f47e83882f.png)

**Comment by Nness** [comment]
![firefox_1v9Q7XNUdx](https://user-images.githubusercontent.com/1712143/100941433-7c16d080-355e-11eb-9be7-6f1648896bd8.png)

![firefox_3bEcrOzVm6](https://user-images.githubusercontent.com/1712143/100941419-77521c80-355e-11eb-8ce4-82a0a5f95914.png)
