### ISSUE TITLE
[24019, 25763, 25773] Ability to add additional contacts (CCs) to ticket - Autotask

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#507]
Customer is asking if we can add the ability to add CCs or ‘Additional Contacts’ to a ticket to the DD Portal (Autotask instance). 

This way, they can add other users to a ticket for increased visibility.

**Comment by Nness** [comment]
Autotask currently exposed additional contact as raw SQL relationship table. It is hard to sync them over as batch, unless we sync over by ticket (individually).

e.g. on relationship table
|Ticket ID|Contact ID|
|--|--|
|2|203|
|2|102|
|30|203|
|30|211|
|30|959|


When sync over tickets, we can say sort by ticket ID then take 500. And slowly loop through. While for relationship table, it's hard to sync over efficiently. Thus until now, the info has not been pulled down from Autotask.

**Comment by iskolares** [comment]
Related request ticket #25763

**Comment by iskolares** [comment]
Related ticket #25773

**Comment by Chrispe66** [comment]
Is there a way to not sync the contact on the ticket but rather just add them to the DD side so they get notifications? Maybe this is an independent feature.

**Comment by Nness** [comment]
This has been completed with latest server, tech and client portal release. (TECH 1.40, client portal 3.34)
