### ISSUE TITLE
[9457] Add configurations to tickets

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#51]

**Comment by Nness** [comment]
This won't be in initial release of TECH. This is new area that we need to explore.

**Comment by FluidNets-DamianS** [comment]
Definitely something that will be needed.  While I don't use this myself all of my techs do use the Automate and Control buttons now visible in Manage to access machines.

**Comment by Andrew-Lahikainen** [comment]
This has been implemented

**Comment by Aycorn** [comment]
@Andrew-Lahikainen - Is this functionality to add/remove configurations on tickets from DD Tech? Or view current configurations assigned?

**Comment by Nness** [comment]
view only.

**Comment by Nness** [comment]
For add or update need different user voice.
