### ISSUE TITLE
[24145] Add separation between ticket owner and technician replies on tickets

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#510]
Customer is asking if we can add a bit of indication/separation on the ticket replies between the technician and ticket owner.

Here's a screenshot showing the UI they are suggesting
![image](https://user-images.githubusercontent.com/13637718/101084080-50edb900-3612-11eb-82c0-208e50029dd6.png)

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/101406090-e4d6c200-393d-11eb-87b3-933dfe5d1533.png)

when move avatar to right side, it will cosume one column. This is timeline not chat. 

change will be released on 14th Dec 2020, You can preview under `/tech/staging`.
