### ISSUE TITLE
[24143] Advanced Time Entry Calculator

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#511]
Customer is asking if we can add a Advanced Time entry form which can take a numeric value (in minutes) that technicians can manually input the time it took to complete a work. The entered value will automatically calculate the start time, using current time as the end time.

This will save techs' time in having to check the clock as their start time, calculate the number of minutes they took to complete a task, then add it to the start time to determine the end time. Here's a suggested UI
![image](https://user-images.githubusercontent.com/13637718/101086643-0b32ef80-3616-11eb-9d3d-2b2e79d3280f.png)

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/101405849-9b867280-393d-11eb-907e-3ecd26b3e0be.png)
This will be released on 14th of Dec. You can preview it under `/tech/staging`
