### ISSUE TITLE
Revise UI for Change Approval notes dialog

### ISSUE THREAD

**Issue by jameskirsop** [DeskDirector/UserVoice#513]
This text box for the optional notes entered when approving changes is comically small when some of our customers like to write long responses. Can the input field be changed from a single line to a slightly wider and taller text box so that it's easier to see longer messages?

It seems there's already some spare vertical space in the dialog that could be used :)

![Screen Shot 2020-12-21 at 5 39 57 pm](https://user-images.githubusercontent.com/1734219/102833595-a82ebe80-4445-11eb-8e65-0a4fb6df57d0.png)

**Comment by Nness** [comment]
This has been implemented and is on deployment pipeline. Input field has been changed to ordinary text field. It allows multi line scenario or long note.

Version 3.16.1
