### ISSUE TITLE
[24253] Need new email token for Name of Approver receiving the email

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#514]
Since the change to approval required email on server v19. System now sending email to individual approval instead of one email to all approver.

That means, each email has single receiver. With such change, some of customer want to add email header to give greeting to receiver. Which at moment it is not possible.

`Contact.Name` token is for ticket owner, while `Approvers` is for all approver, not current receiver. Then we have `ApprovedBy` token, which is for approval declined or approved email.

In such case, we will need a new token for this scenario. e.g. `Receiver`.

**Comment by Nness** [comment]
There is concern regarding to this request.. When user receive email such as:

```
Hi John:
A New Ticket Requires Your Approval.
```

Such ticket will cause receiver to think you are the only approver or it require high attention. Is this how it should be? When there are multiple approvers, do we want to make it looks like if you don't do this world will end?

This is good to have feature, not necessary at this stage until we can sort out the scenario.

**Comment by jameskirsop** [comment]
In MSP land, all change requests should require _high_ attention - it's in their nature to warrant a quick response. If a change isn't approved, it often means an issue can't be resolved (or moved towards a resolution) - causing frustration for a customer and the MSP. It's up to the account manager on the MSP side to handle the communication to the customer to ensure people are aware if there are multiple approvers.

Leaving that commentary aside, a personally addressed email will be better than:

- An email with no personalised salutation
- Incorrect salutation (which is what you get if you try and use any of the current tokens that are available)

For us, the new changes you made in v19 to allow individual emails are useless without being able to correctly and personally address the messages.

**Comment by Nness** [comment]
Thanks for input. Whether change in v19 is useless or not depends on personal perspective. Also the initial intention to send to each approver individually was not to solve personalized solution but allow us to give auto login for approver.

What we have achieved with individual email are:
* Allow login token, so email can contain quick action link to approve or decline the request.
* Internal test on Microsoft's adaptive card. Where email can became an app, that they can approve or decline without access portal, also they can see if ticket been approved or declined by others within email as they open it.

Second implementation we are currently under internal test, in the future we will allow selected partner to try out.

One thing I cannot agree is frustration for a customer. If they are frustrated, they are frustrated at their own company's approver not MSP. It is high attention if you can specify name, that is only applicable if they read the mail. To be clear, I'm not saying it is not important, but rather not as important. Amount of attention that can add to the email through salutation is very limited, human often skip them. As they scan through the mail.

We will consider it but won't be on higher priority. The benefit of this implementation is only on good to have, not on must and game changer level, if that make sense.

**Comment by jameskirsop** [comment]
> Amount of attention that can add to the email through salutation is very limited, human often skip them. As they scan through the mail.

While I agree with the sentiment, our experience is that personally addressed emails from our support tools (ConnectWise Manage, DeskDirector etc) have a higher response rate than automated ones without personalisation. Improving our communication effectiveness using the tools we choose to use is important to us, so we can provide the best support experience possible. Having clear, friendly and personalised communication moves us towards that goal.

With nearly two months passed, do you have an update on the second implementation and access to it?

**Comment by Nness** [comment]
This is not yet on roadmap. As approval email didn't change for 7~8 years. This request is only come on to surface because we now allow sending email individually.

Thus, this is not bug, nor it's caused by breaking change. This feature is good to have, not must or urgent. 

It is under normal user voice stage, which is require high request before we will consider. 

Sorry about the message not been clear.

**Comment by Nness** [comment]
This should be treat as finished. Latest server release has the capability to use receiver's name inside email template.

This also apply to every other email template except ConnectWise's CC email.

Default template should be updated to reflect change within next few weeks. Close as this user voice is mainly focus on additional token.

**Comment by jameskirsop** [comment]
This is great, except the token is one available in the 'Approval Required' ticket template, not the 'Approval Granted', or 'Approval Declined' templates also. All 3 templates require this token so that the varying recipients are addressed correctly throughout the change approval process.

**Comment by Nness** [comment]
My mistake. Any email that's sending as group won't have receiver. 

* Approval Rquired - We send to individual approver separately. (has receiver token)
* Approval Granted - We send to ticket owner and CC approvers. Multiple people will receive this email. (no receiver token)
* Approval Declined - Same as granted

What you can do is use status changed email, that way you can have receiver. Of course that will only send to ticket owner.

**Comment by jameskirsop** [comment]
Thanks @Nness.
I just received an 'Approval' email with all recipients in the 'To:' field, not the ticket owner in 'To' and the approvers in the 'CC:' field. Your workflow seems appropriate providing the emails are sent in the way described...

**Comment by jameskirsop** [comment]
@Nness, I've just tested the 2nd use case, 'Approval Granted' again - and the owner and all approvers were in the To: field. Are you able to address and correct this so it's inline with [your comment](https://github.com/DeskDirector/UserVoice/issues/514#issuecomment-800726322)?

**Comment by Nness** [comment]
Only Approval required email is currently sent out separately. Granted and declined at moment only serve as notification.

**Comment by jameskirsop** [comment]
@Nness, yes, but you [said above](https://github.com/DeskDirector/UserVoice/issues/514#issuecomment-800726322) that the ticket owner is sent the email directly and approvers are CC'd for Granted and Declined. This is not occurring at the moment as everyone is sent the email via the To field.

**Comment by Nness** [comment]
Right, that's what you mean. We will make adjust, expect it to be resolved and deployed within next 2 weeks.

**Comment by Nness** [comment]
You can submit support ticket to trace on progress.

**Comment by DDAndyChen** [comment]
Approval decision emails will have the approvers in CC's in the next release (19.21.1)

**Comment by jameskirsop** [comment]
Thanks @DDAndyChen. Confirming email To/CC'ing appears to be working in the way that it should within the context.
