### ISSUE TITLE
[24328] Move chat window so it does not cover ticket details pane

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#520]
In TECH portal, an opened chat window covers up the Boards dropdown (main Tickets page) on a on a 1920 x 1080 monitor

![image](https://user-images.githubusercontent.com/13637718/103835430-226c6d80-50eb-11eb-8037-6ffc08b17621.png)

Customer is asking if we can move the chat window, so it does not cover the boards dropdown.

**Comment by JPGerhardt** [comment]
Would be cool if you could make it able to be dragged left or right, or even better a pop out window.

**Comment by Nness** [comment]
This has been moved to right aligned, which will in term cover part of ticket list. This is as far as we can do without significant change of design. 

Right side panel's expand need reserver some space.
