### ISSUE TITLE
Display ticket status inside ticket list (TECH)

### ISSUE THREAD

**Issue by dustinabingham** [DeskDirector/UserVoice#521]
I wanted to put in a request to see about adding an additional streamline to status or customer interaction to tickets a little more obvious, which would support faster spotlighting for technicians scrolling through their tickets to see a status change or customer interaction. Obviously, we have the status filter, board status filters, and the hover status behavior (which are great, don't get me wrong).

But being able to see at a glance in your ticket list the statuses of your tickets in your queue versus clicking through each status, would be beneficial. Not to mention it helps those technicians who don't have dispatchers or managers that manage tickets for them. It also improves the beginning of shift planning and scheduling.

But the thought is perhaps either adding in a status stamp somehow to the ticket summary box somewhere (the hover creates a stop-go kind of feel because you have to wait for the hover to notice- its a slow down of pace for each ticket). I'd recommend placing something beside the technician's name for example. (Assigned to John Smith - Waiting on Customer). Or the other thought would be to snag some practices from other ticket platforms in which they will BOLD all tickets in a technician's list that have had any update since the technician's own last update - this would cover customer responses, status changes, or changes made by other technician's or managers outside of the assigned technicians own updates. This way, the assigned technician would know when his tickets have been updated more readily. The other option I've seen with this style of update notification is the ticket UI box would shift to a different shade of color so it was quick to see in a ticket queue. One our customers recommended color coding each ticket box to a status. I don't think it is necessarily a bad thought but I think it adds in an additional layer of complexity that would give very little. But I thought I'd share, none the less.

All in all, I've always operated on the notion that the less action economy a tech has to perform when filtering and sorting their work loads, the faster and more effective they become. It shouldn't be a marathon to get the information you need. They've already got enough on their hands. I'll state, our services are unique as we are operating in the IT for Education industry and time is of the essence when it comes to teachers because they have so little time to do anything, so the quicker we can help them and the less we burden them with, the better. The nature of teacher schedules often times have them waiting on ticket responses and support beyond a typical work day, because they are having to submit tickets on their breaks and then only again responding on their next break or work day. So, the quicker we can respond and see their updates, the more time we can whittle down on the time it takes for teachers and students to receive support. This is just my opinion of course, everyone has different processes and mentalities of support and your platform supports more than just a customer like us, with their own processes, needs, and cultures.

But I thank you for taking the time and allowing an open forum like this for feature requests. You guys continue to impress me over and over. I've never seen such an interaction between developers and customers from a company. Kudos to you guys, always. I am so impressed with your product and your companies values on communication and support.

**Comment by Aycorn** [comment]
I believe this has since been implemented - status names now included in each DD Tech ticket:

![image](https://github.com/user-attachments/assets/bf067213-2c52-4e82-ae84-90e6836daf30)
