### ISSUE TITLE
[24515] Dedicated phone number field for forms

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#531]
Currently, there is only a number field available for forms which is used as a phone number field by customers and this creates several format and validation issues.

A dedicated phone number field is recommended to be able to correctly handle and validate phone number input .

**Comment by iskolares** [comment]
Related to https://github.com/DeskDirector/Issues/issues/209 and https://github.com/DeskDirector/Issues/issues/210

**Comment by Nness** [comment]
We already have an user voice #142
