### ISSUE TITLE
CSV export for survey data

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#533]
Provide CSV export API for survey data. Which include ticket survey and custom survey. 

Customer can use CSV in 3rd party applications, such as PowerBI from Microsoft to visualize data in different way, or combine with other data.

### CSV export should allow following filtering.

| Filter  | Type |
| ------------- | ------------- |
| Start Time  | Date Time|
| End Time | Date Time  |
| Company ID | Integer |
| Member ID | Integer |

### Exported CSV data should be following.

| Column | Type |
| ------------- | ------------- |
| survey_result_id | string |
| survey_id | string |
| survey_name | string |
| company_id | integer |
| company_name | string |
| contact_id | integer |
| contact_name | string |
| created_at | ISO date time |
| updated_at | ISO date time |
| question_[id]_id | string |
| question_[id] | string |
| question_[id]_type | csv, nps |
| question_[id]_value | integer, null |
| question_[id]_comment | string, null |

### Ticket Survey CSV export should contain extra data below

Ticket board, assigned members are data that's been recorded at the time of ticket closure. It only reflect the state at the time of submit survey.

| Column | Type |
| ------------- | ------------- |
| ticket_id | integer |
| ticket_name | string |
| ticket_identifier | string |
| board_id | integer |
| board_name | string |
| closed_date | ISO date time |
| resource_[id]_id | integer |
| resource_[id]_name | string |

### Custom Survey CSV export should contain extra data below.

| Column | Type |
| ------------- | ------------- |
| campaign_id | string |
| campaign_name | string |

### Handle array data

DeskDirector server will handle array data, split them into different columns. Each of those column have unique name.

e.g. if there are 2 questions. such as.

```
[
   { question: "How is our service", id: "1-A" },
   { question: "Would you like to recommend others?", id: "2-A" }
]
```

CSV output for above should be:

| Column | Type |
| ------------- | ------------- |
| question_1-A_id | 1-A |
| question_1-A_name | How is our service? |
| question_2-A_id | 2-A |
| question_2-A_name | Would you like to recommend others? |

Such behaviour is designed to optimize on excel. Of course PowerBI may work better with other kind of format. This spec should be finalized by 27th of Feb 2021. Then by 3rd of March 2021, this should hit release cycle.

Alternative way to hand array is to leave JSON data inside. Such as.

| Column | Type |
| ------------- | ------------- |
| questions | JSON object |

**Comment by DDAndyChen** [comment]
API design
POST /api/v3/tech/customers/surveys/results/csv


```
{
  "Format": "string", //"powerbi" (default) or "excel"
  "Filter": {
    "SurveyType": "string", // "ticket" (default) or "custom"
    "Range": {
      "Start": "2021-02-03T20:00:38.326Z",
      "End": "2021-03-03T20:00:38.326Z"
    },
    "Surveys": [
      "survey_id"
    ],
    "Boards": [
      1
    ],
    "Companies": [
      22
    ],
    "Members": [
      55
    ]
  }
}
```

**Comment by Nness** [comment]
Let's simplify this by remove survey filter. We should only return results for a single survey, not multiple survey. Else the data is hard to read and work with.

e.g. 

URL: `api/v3/tech/customers/surveys/{surveyId}/results.csv`

That way, for each CSV column it can represent proper question rather than mixed.

**Comment by DDAndyChen** [comment]
API design updated
GET /api/v3/tech/customers/surveys/{surveyId}/results.csv

Example

> api/v3/tech/customers/surveys/default/results.csv?format=powerbi&boards=7&boards=1
