### ISSUE TITLE
[24723] Make text field max length condition (validation) more flexible

### ISSUE THREAD

**Issue by blacktipit-x** [DeskDirector/UserVoice#534]
The current DD forms lack validation flexibility to support cases like:
- set custom text field length restriction
- phone type field and validation (10 digits, ITU standards, etc)
- email validation

As an example, ConnectWise API limits first name to 30 characters - there are no ways to set this as the minimum is 50.

For inspiration, look at Google form which uses a similar interface, but provide more flexibility including arbitrary length and ability to use regular expression as validator (which would cover phone and email nicely).

Thanks.

**Comment by Nness** [comment]
There is email field.
![image](https://user-images.githubusercontent.com/1712143/109072206-8f020100-7759-11eb-8d4d-9a35c9472dbf.png)


There is phone field user voice. #142

There is also text length restriction can be used.
![image](https://user-images.githubusercontent.com/1712143/109072423-e3a57c00-7759-11eb-9a0e-ff605810a791.png)

**Comment by Nness** [comment]
It is better to write user voice request to our support first, let our support create user voice. That way if anything already exist or planning, they can explain.

If no reply on this issue it will be closed next time I visit.

**Comment by blacktipit-x** [comment]
I was not aware of user voice - I filed features there.

I will update the feature as I don't think the answer I received is correct.  Thanks!
D.


Blacktip
DANIEL MARTIN[CTO]
www.blacktipit.com  |  407.212.7625
We make technology invisible®

**Comment by blacktipit-x** [comment]
Hello,

Let me try to be more specific.

1. Custom text field length - how can I set the text field length to **30** characters (or any length)?

2. Email - how can I validate the domain of an email address - say I want first.lastname@company.com, where I can make sure the user specify the right company?   Can the form check if the email already exist in the ConnectWise integration?

3. Phone - as stated in the linked issue 142, have a 'phone' field which would support and validate how user type phone numbers (321) 123-4567.

As stated in the original message, google form is a good example to look at.  It provides custom length on text fields and the support of regular expression would help with item 2 and 3 above.

D.

**Comment by Nness** [comment]
That's why it is best for you to log support ticket. We don't accept multiple request that's recorded in a single issue. 

1. We will add more options, whether we will allow free typing on character limit count, maybe.
2. Email, such complexity is not the goal of our form system. You can use dynamic field to achieve that, or put logic at automation to either automatically construct email or reject it.
3. Phone field will be able to support different format. You can try out through our chat's callback. It will use same kind of engine.

**Comment by Nness** [comment]
Next admin release should have more options on text max length. Additional options are [20, 30]. Estimated available time is early next week.

I will leave this open for allow max length count free entering rather than dropdown.

**Comment by Nness** [comment]
Just let you know that a new admin portal has been released with option to have 20 and 30 maximum length validation on text field.

**Comment by Nness** [comment]
Since release of phone field, I will consider this as finished. As I keep saying, don't create user voice with multiple request. Split them up to be more specific.
