### ISSUE TITLE
Catch all company for contact creation

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#537]
![image](https://user-images.githubusercontent.com/1712143/110369122-ce601400-80ae-11eb-81b5-d27b694a546f.png)

Additional setting to allow catch all company when login user doesn't exist and email domain is not registered with any company. Case covered for user that's using public email domain, such as gmail or hotmail.

Setting to choose an catch all company on above contact creation setting page.

* Setting only be respected when contact creation is allowed.
* Setting only be respected when contact authentication rule allows creation.
* Contact auto creation happen to catchall company only when either OAuth or mail token login is enabled.
* Flow of contact creation should be same as normal contact creation. Which requires identify given user's email is valid.

For case as gmail, mail token is the only login choice, where hotmail OAuth may be used. Thus, mail token login and email sender setting are essential for this feature.

**Comment by CharlesWarwick** [comment]
This could be a faster implementation 

- We could allow a *.* domain in the email domain field to signify that a company is the catch al
- If there are two *.* domains, then the first one found wins
