### ISSUE TITLE
[24845, 26060] Improve tagging when creating broadcasts

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#544]
Currently, when using tags to search for a company when creating a broadcast, you need to fully and correctly spell the tag to get the list of company(ies) that uses the tag. The same goes when using the Contact tag filter.

The customer is asking whether we can improve this (possibly predictive/suggestive search?). It becomes a pain when they've used long tags, so they need to spell out the whole tag before they can see the company/contact they want to target.

**Comment by iskolares** [comment]
Partly related request #26060 (tags needing to be spelled out correctly for the search to work) 

This ticket is more inclined to search using tags inside the admin console (not when creating broadcast), but it's the same behaviour.

**Comment by cdandrea** [comment]
Thanks for appending to this. Just something else for consideration...

> It would be great is a centralized, master tag database could be built and/or dynamically populated as new tags are introduced. If we start to type out a tag, it presents hits in real time. At the very least, if DD could use partial matches when using tags for filters that would remove some frustration.

**Comment by Nness** [comment]
Most of list that supporting tag filtering, will allow you to click on the tag that any item has. What you can do to get around is:

* Search for an item that with the given tag,
* Click the tag to filter (if not support click to filter, just copy and paste to tag filter)
* Remove the search field to get all items.

We will look into auto-complete on tag filter in the future.

**Comment by cdandrea** [comment]
@Nness - sorry, I'm not following. The request is to pull up a tag to add it. Unless we type it exactly, it will not come up with a result.  If we've established "vip" as a tag, then we can type "vip" and all matches will come up. That's a simple example and easy to remember. However, as tags become more actively used, there could be all kinds of variations to slice and dice companies/contacts. In the case of broadcast messages/emails, we may have different "mailing lists" targeting specific companies/contacts based on the services they subscribe to. 

While auto-complete would be perfect, having results for partial matches would go a long way. That way we get some hits, recognize the full tag, attached to a company/contact, that we're actually looking for and use your tips to refine the list to exactly that tag.

**Comment by Nness** [comment]
* Partial match will never happen unless Twitter and StackOverflow also implemented it.
  * I have attached example from Twitter, where type tag it will show up recommendation, but when search partially it result as empty.
  * StackOverflow is also the case.
  * I do know one way to make it happen but I can not justify the outcome. This is from technical debt vs benefit point of view.
  * Type ahead and suggestion can be done
  * All tag used for a given collection can be done 
  * All tag used by all collections possible but not guaranteed. (ticket, contact, member, company) - exclude form, request type etc.


The way of manual discover tag is based on the knowledge of the tag. When there is a long tag, the people who created tag should know who he give to. So he can search for that user or entity and copy the tag. If it is from the same list, he can search the entity, and click on the tag to filter by tag then remove search to get full result.

Anyway, that's just hack. Not saying it is solution for this.


![image](https://user-images.githubusercontent.com/1712143/127059015-3783448a-d80d-47ca-b305-1baf19de6804.png)
![image](https://user-images.githubusercontent.com/1712143/127059034-2dc3405a-990a-4b32-817e-9b20eb940fed.png)

**Comment by Nness** [comment]
I have put the this on our roadmap as TODO, as we do want to promote tag. As for estimate, probably by end of this year. We may adjust priority if more and more customer feel it is burden.

**Comment by Nness** [comment]
The tagging suggestion on admin portal has been released yesterday. TECH portal is up coming.

**Comment by Nness** [comment]
Implemented and released.
