### ISSUE TITLE
DD Tech | Copy option for Summary with Deeplink

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#548]
Feature request for a ticket copy option that generates ticket summary with a hyperlink to the DD Tech deep link.

Produce something like this that can be easily pasted into another application like Teams: [This is my ticket summary](https://support.deskdirector.com/tech/tickets/123456/details)

**Comment by Nness** [comment]
![firefox_mRPqzgYLTp](https://user-images.githubusercontent.com/1712143/114952517-8650c000-9eaa-11eb-9e02-cea06869bb58.png)
It should be in next TECH release. or you can use under staging path.. e.g. /tech/staging.
