### ISSUE TITLE
[25175] Number of tickets not appearing on Ticket list filters in new client portal

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#549]
The number of tickets is not appearing on Ticket list filter in new client portal after the recent client portal update (v3.20).
![image](https://user-images.githubusercontent.com/13637718/114949603-72ef2600-9ea5-11eb-8448-21a92d8b4e27.png)

This was how the ticket filters in the client portal looked before the update
![image](https://user-images.githubusercontent.com/13637718/114949464-31f71180-9ea5-11eb-90e7-594612bc3fb9.png)

The number summary comes handy in giving the clients idea of how many tickets are in each filters

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/114955326-99668e80-9eb0-11eb-833b-55ff006612b9.png)
