### ISSUE TITLE
Request Type Groups - Ability to assign Companies or Contacts via the Request Type Group page

### ISSUE THREAD

**Issue by beverleyh473** [DeskDirector/UserVoice#553]
In the Request Type Groups, you can create a new Request Type Group, however there's no option to assign a Company or Contact.
There also isn't any indication that you need to go to the Companies/Contacts page to edit this.

I have to take two extra steps by going to the Companies/Contacts page, then to Request Type Groups and assign them a group there.

**Comment by Nness** [comment]
Could you submit your request through support.
