### ISSUE TITLE
Add Contact Number to Contact's Information in Tech Portal

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#567]
Currently, the contact information section of a specific contact in the TECH Portal only has the email address and not the contact number of each contact:
![Screen Shot 2021-06-14 at 1 59 43 PM](https://user-images.githubusercontent.com/13637718/121830317-e03dfc80-cd18-11eb-9064-ce883eba3890.png)

The customer is asking if we can add it as their techs may need to call the customers, so they need easy access to the number in the tech portal

**Comment by Chrispe66** [comment]
Would be nice if the phone number was also clickable in the event the Technician has a softphone and would like to execute a dial.

**Comment by Nness** [comment]
This has been completed and released.
