### ISSUE TITLE
Deeplink Chat Specific Ticket

### ISSUE THREAD

**Issue by Chrispe66** [DeskDirector/UserVoice#568]
I'm referring to the following document:

https://help.deskdirector.com/article/rb70qsabfd-portal-deep-linking

I cannot, for the life of me, figure out how to variable the ticket number in the communication so that I can deeplink a specific ticket chat. Can someone please advise how to complete this last part?

**Comment by iskolares** [comment]
I have reached out to you via ticket and created a sample email template with this. Closing this request.
