### ISSUE TITLE
Search functionality for DD Learning Center

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#569]
Feature request to include search functionality in the Learning Center:

![image](https://user-images.githubusercontent.com/30588784/121962254-9dcdfb80-cdbc-11eb-9b61-60c0e50d6f63.png)

**Comment by Nness** [comment]
learning centre has long been deprecated. We will have our own proper content system in the future. Search will be included as default feature for new content system. 

No additional modification will be put onto existing learning.
