### ISSUE TITLE
[25602, 25938] Ability for a "Manager" to see all Sites under a company (Connectwise)

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#571]
The introduction of the [User Group](https://help.deskdirector.com/article/bxd7i1kkw3-user-group) feature, added the option to grant users to be able to inherit their assigned site in Connectwise and add a ticket grouping in the client portal for the site.

Cust is asking if it's possible to add a capability for a "manager" of a company to be able to see all the Sites (and the ticket grouping) in the client portal.

**Use-case:**
A company has several branches, each of which is a site in Connectwise. They want that the Manager of a company is able to see all sites and the ticket grouping.

Using the user group to create each of the site is possible, but managing several user groups manually would be a pain. (e.g. if users are moved to different sites in Connectwise, that would mean also doing the same change in DeskDirector User Group.

Inheriting the Connectwise sites in the context of a Manager, like we inherit it in the context of the user would streamline the process.

**Comment by iskolares** [comment]
related request Ticket #25938

**Comment by Nness** [comment]
You can now filter by site if you have all tickets permission.
