### ISSUE TITLE
Chat with a Technician - Associating with Current Ticket

### ISSUE THREAD

**Issue by Chrispe66** [DeskDirector/UserVoice#572]
I can't seem to find an issue relating to Chat with a Technician from the portal or the application.

When a chat starting or finishing, there is no apparent way to associate it with a current ticket. Sometimes, we have users who will send an email to the system to create a ticket and then create a new session instead of chatting on the ticket. It would be nice if you could assign the chat to the ticket, or select "create a new ticket". I think, right now, the Chat with a Technician will create its own ticket and then we have to use the PSA to merge.

**Comment by Nness** [comment]
Chat is always associated with ticket. Contact with our support please.
