### ISSUE TITLE
Chat Supervisor

### ISSUE THREAD

**Issue by Chrispe66** [DeskDirector/UserVoice#574]
Is there a feature request to have Supervisor and Agent Chat technicians that can allow a supervisor to see all chats and either join or leave, whisper, or engage on the chat?

As a manager, I'd like to see all open chats, not just mine, or ones in waiting. Then, I'd like to monitor proactively and not wait to be invited.

**Comment by Nness** [comment]
Chat already capable on that. Please contact support.
