### ISSUE TITLE
Chat Notifications After Logging in

### ISSUE THREAD

**Issue by Chrispe66** [DeskDirector/UserVoice#575]
We had this weird situation today where there was no tech in the app before 9 am. A user created a chat, and I saw it because I was already logged in, but when new users started and logged into the chat at 9, they did not get notified nor see the chat waiting.

**Comment by Nness** [comment]
Please report to support with detailed info. Such as who is logged in as tech after nine am. Are there any chat coming in after nine am? What day is it.

**Comment by Nness** [comment]
User voice is not for support
