### ISSUE TITLE
Ability for users with All Tickets access to filter to other sites too

### ISSUE THREAD

**Issue by awill4457** [DeskDirector/UserVoice#577]
One of our clients has requested the ability to be able to filter down on any of their sites tickets, not just their current office.
If I grant the user "Access to ConnectWise Site Tickets" they can only see tickets for their office and can see this:
![image](https://user-images.githubusercontent.com/3886648/123708675-2d8ca300-d8af-11eb-9bc5-5b943b6eb02a.png)

However this means they cant see other sites tickets:
![image](https://user-images.githubusercontent.com/3886648/123708761-4d23cb80-d8af-11eb-85be-8bafa099e486.png)

They'd like the ability to filter to see any particular sites tickets, e.g. all Brisbane office, or all Sydney office, etc.

**Comment by Nness** [comment]
This has been planned and if nothing goes wrong it should be released later this month.

We will provide filter for people who have access to all tickets and also has company site restriction. (Filter means similar to filter by contact. Not stay as user group)

Note: Company site restriction now able to apply to company permission level.

@awill4457 next time if you could contact our support for user voice would be better. When user directly adding new user voice from here often has lower priority.

**Comment by Nness** [comment]
Currently we only planned to add this for ConnectWise. If you are Autotask customer, please let us know.

**Comment by iskolares** [comment]
Closing this. Identical request here #571 

Will keep the original request open.
