### ISSUE TITLE
[25804] Default Ticket Routing Configuration

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#581]
We currently have settings for Default Board and Default Source, however, none for default status, priority, type, and others
![Screen Shot 2021-07-01 at 6 56 35 AM](https://user-images.githubusercontent.com/13637718/124016268-8f791400-da39-11eb-88e0-7fa420428d1c.png)

If implemented, new request types created can then inherit whatever ticket defaults that they have set, instead of manually setting it for each request types.

**Comment by Nness** [comment]
Default priority, status, type, etc can be controled at PSA.
