### ISSUE TITLE
[26115] Client portal experience within Microsoft Teams

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#588]
Teams is a very common tool used by majority of DeskDirector customers (and their clients).

Having a DD app that can be integrated into Teams will make the DeskDirector portal more integrated into an app customers use daily. This will also encourage the easy use and consumption of the DD portal and our features.

-----

More specifically, client portal to be used within teams. Without need to login. User can use the application to log tickets, view tickets etc.

Extension content may not work, since the security control is no longer under our hand. Any CORS site may unable to load. e.g. extension iframe that pointing to different domain.

Cost side, we may have to maintain a separate application that designed based on Teams' requirement. e.g. not display anything that's not supported by teams. Such as.

* Chat
* CORS extension page

Alternatively, it can be a page to display a button. Where use can click on it and open client portal inside browser. Where login is handled through initial click.

**Comment by Jim-Bmore** [comment]
How does this not have a million likes?

**Comment by beverleyh473** [comment]
[#44500]

**Comment by ghost** [comment]
this would be great

**Comment by beverleyh473** [comment]
[#45196]

**Comment by DDAndyChen** [comment]
We are building our DeskDirector app for Microsoft Teams which has the SSO and notifications features, stay tuned!

**Comment by Fly-Kick** [comment]
Any idea when this will be released? I am also stunned this doesn't have 10,000 likes!

**Comment by DDAndyChen** [comment]
> Any idea when this will be released? I am also stunned this doesn't have 10,000 likes!

We have finished building the app actually, now we are waiting for Microsoft for the public release approval which I cannot say for sure how long it will take.

**Comment by DDAndyChen** [comment]
Our app has been release!
Here is brief introduction on getting started as we are creating more documentation.

First, we will need to set up some security settings in the admin portal first. [View documentation here](https://help.deskdirector.com/article/b755wpu2sf-installing-teams).

Then the app can be installed from here: (Ms. Teams admin required for installation)
[https://teams.microsoft.com/l/app/36c8b491-a1dc-43d0-bfad-ef27e98ef5fb](https://teams.microsoft.com/l/app/36c8b491-a1dc-43d0-bfad-ef27e98ef5fb)

* install to your own Ms. Teams first, as the "tech portal",
* in the settings of the *DeskDirector* tab of the installed app, you can link another Ms. Teams account to one of your client companies by their domain name or Azure AD tenant ID
* then install the DD teams app to your client company, as the "client portal". Branding can be changed in the [Microsoft Teams admin center](https://admin.teams.microsoft.com/policies/manage-apps/36c8b491-a1dc-43d0-bfad-ef27e98ef5fb)

Here is a video on the client portal in Teams user experience
https://help.deskdirector.com/article/33hsje7udg-setting-up-client-mode-in-desk-director-for-microsoft-teams
