### ISSUE TITLE
Direct Reference to Quote Link in DD Portal Quotes

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#59]
Create Reference for Order Porter Variable so when i send out a quote email they can click on that and go directly to the DD Portal Quote to approve it there.

**Comment by Nness** [comment]
Unless we know the CW opportunity ID, else its impossible at moment. The order porter is saved inside attachment of opportunity, it is not possible to query or find in short time.

If we can confirm quosal can give opportunity ID when send out quote email, then this is possible. Until then this will be marked as declined. 

Another possibility is for opportunity title to contain quosal variable, then we can try to query that, but this is not 100% guaranteed solution. Which means the link to dd-portal might work or might not. It depends on whether title been format correctly and whether there are duplicates.
