### ISSUE TITLE
Feature Request: Support for Windows vertical taskbar with Broadcast Notifications

### ISSUE THREAD

**Issue by Magnum901** [DeskDirector/UserVoice#592]
One of our users is using their windows taskbar vertically. When sending Broadcast notifications, it appears underneath the taskbar, meaning you're unable to dismiss the notification unless you go into the app. This is a picture from our branded 'F-Connect':
![image](https://user-images.githubusercontent.com/88411750/128109407-17c30f08-8029-4ed1-8abc-3610e7657a2c.png)
Is there a way to align this properly with the vertical taskbar?

**Comment by Nness** [comment]
Move desktop portal from electron to managed is one of thing on our roadmap. Such issue is purely caused by poorly constructed code in our electron implementation. 

I have created user voice for portal vNext.
