### ISSUE TITLE
Visual indicator of 100 company broadcast limit

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#597]
Broadcast fails to create with a network response showing a limit of 100 companies:
![image](https://user-images.githubusercontent.com/30588784/129812596-ed60703a-e76a-4fd7-9d61-fdc9b0b516e5.png)

Please include a visual indicator to the Company Filter module to support this limitation (70/100 companies)

**Comment by Nness** [comment]
there will be indicator for companies, contact tags and users in next TECH release. you can try out in staging TECH. under `https://:host/tech/staging` path
