### ISSUE TITLE
Remove individual companies from the Company Filter module in Broadcast

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#598]
The only way to remove companies from this list is to clear the entire list and start over.
Please add functionality to remove a single company once they're added to the Company Filter list

![image](https://user-images.githubusercontent.com/30588784/129812796-5eccab85-32f0-4b53-9b08-0fe668f766d7.png)

**Comment by Nness** [comment]
Delete button was implemented but have issue display under large screen, this has been addressed and will be released in next TECH portal release. expect to be 30th of Aug.

You can use under staging by use `https://:host/tech/staging`
