### ISSUE TITLE
[10277] Implement a new updater/installer

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#6]
There are a number of issues with the current updater/installer (Squirrel). To avoid some of these issues we could roll our own.

**Comment by Aycorn** [comment]
Closing: The [DD removal tool](https://help.deskdirector.com/article/huqqqba1r0-ddportal-removal-tool-uninstalling-windows-portals) is available for the mentioned deprecated Squirrel version.
