### ISSUE TITLE
[26212] Avoid Tech Portal Notification multicast

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#603]
Currently, if there are multiple tabs opened of the tech portal, the tech will receive a notification for each opened tab for the same ticket event/action.
 
It's very common that a tech has multiple tech portal tabs open, and the browser notification from each tab creates a lot of noise. If possible, there should only be one notification pushed per ticket action, no matter how many tech portal tabs are open.

**Comment by Nness** [comment]
This should be addressed in TECH portal release. 1.40
