### ISSUE TITLE
Email Notification event for Autotask CCs and Secondary Resource

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#605]
Adding CCs and secondary resource for DD Autotask currently on staging and to be released live soon. From tests, it looks like there is no email notification event/logic for CCs and secondary resource yet.

It will be best to add it so CCs and secondary resources are kept in the loop of ticket updates.

**Comment by iskolares** [comment]
Secondary Resource notification is already part of the "Assigned Technician Notification" event.

As for CC notification even, UI needs to be added for it. Issue created here https://github.com/DeskDirector/Issues/issues/229

**Comment by Nness** [comment]
This has already been released, for additional contact's notification event, it will be released on admin portal 1.30. You can use through staging channel. 

To access admin portal staging, change `admin/v2` URL to `admin/staging`.
