### ISSUE TITLE
[26368] Markdown support for email delivery

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#607]
Currently, public notes/time entries added to tickets with markdown, will look unformatted on email notifications we send out.

While unformatted markdown does not look as cluttered as HTML, it will still be great to be able to deliver the email notifications with the intended formatting.

**Comment by DevanMorrison** [comment]
Ticket #26368. 

This would be a great feature to have, as right now using Markup is great for view in the portal only, but users typically will rely on email notifications, especially when viewing old tickets, or even those CC'ed to tickets & not the ticket Owner. It will also allow for us to be consistent in visuals to clients from one item to the next. Lastly, we see use of Markdown with Team shared macros in the future, which would allow for canned responses with full content, which would be great to use with quick tickets / self help / etc. (similar to Forms formatting for things like your E-Mail Signature form shared during the webinars, etc)

**Comment by beverleyh473** [comment]
Ticket #44268.

Email signatures often have links that have messy formatting in email templates.
Is it possible to tidy up the email signatures or remove email signatures from email templates?

**Comment by Nness** [comment]
This has been implemented and released.
