### ISSUE TITLE
[26377, 26556,37868] Option to disable access to Tech Portal for specific Members

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#610]
We sync every member from Connectwise to DD. There are instances that some members are not supposed to use the Tech Portal.

For this specific ticket, their StreamlineIT members in particular already manages their own tickets from CW Manage. They only want these users to use DD for the client portal, and not the Tech Portal so they don't get confused.

Removing their board and company access is not sufficient as the option to login to the "Tech Portal" will still prompt the user.

**Comment by iskolares** [comment]
Related ticket #26556

**Comment by iskolares** [comment]
Related Ticket #37868

They have 500++ Tech Members and they only want 40 Techs to have access to the Tech Portal.

**Comment by Nness** [comment]
This has been implemented, there is flag to allow user access to TECH portal
