### ISSUE TITLE
[10812, 11259] URL Linking enabled for Request Types

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#62]
https://deskdirector.zendesk.com/hc/en-us/articles/212254426-URL-Linking-in-DD-Portal

Adding to the list of features currently available for URL Linking, having the option to send a user directly to a Request Type using this functionality would be a great option. This is currently limited only to the Request Support page.

Example Situation:
1) User emails a ticket in manually for a new user
2) Provide user with a direct URL to log a new user form

**Comment by Aycorn** [comment]
Raised on ticket: Service Ticket #11259 - Forward Fillable Forms

**Comment by Andrew-Lahikainen** [comment]
This was added a long time ago. Docs: https://help.deskdirector.com/article/rb70qsabfd-portal-deep-linking

Closing issue 🎆✨🎈🎊
