### ISSUE TITLE
Swap between admin, support and tech portal 

### ISSUE THREAD

**Issue by srhlncm** [DeskDirector/UserVoice#624]
Currently to swap between admin, support and tech portal, you need to log out and log in in order to select another portal to access.

It would be easier to switch between portals as a drop down under the account rather than log in and out. I feel this would provide better usability, especially if you have to switch between the 3 portals during the day.
I have been logging in to the different portal through separate browsers/incognitio mode as a workaround but it would be handy to do it all through my preferred/standard browser.

**Comment by Nness** [comment]
* Added admin portal link under user profile. If given user is admin. (TECH portal, released)
* Added TECH portal link at left side of admin portal.
