### ISSUE TITLE
Pressing ENTER to proceed after pasting an Email Token

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#628]
After copying and pasting an email token into DD Web Portal, I instinctively press ENTER on my keyboard to proceed.

This doesn't work, instead I will click NEXT to proceed.

![image](https://user-images.githubusercontent.com/30588784/138780829-0844239a-4c80-4144-a5dc-607400e04461.png)

Small user experience change that I think is worth implementing depending on the complexity. Can be assessed/considered with the lowest priority.

**Comment by prysmcorp** [comment]
Yes please!

**Comment by Nness** [comment]
This is already the case.
