### ISSUE TITLE
[10617] DD Tech: Ticket Count

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#63]
Similar the the functionality on Connect Wise - provide a Total Ticket Count on the Tickets section of DD Tech.

![2018_06_28_10_17_33_manage_v2018 2_53275_](https://user-images.githubusercontent.com/30588784/42002806-ac0a0014-7abc-11e8-90e1-c7b3ba30e7e1.png)

**Comment by Nness** [comment]
Ticket list is planned to re-look at. We will find an optimal way of display list.

**Comment by Nness** [comment]
@Andrew-Lahikainen with new list design, no count is there, but whether need count is the other question. Would you like to go through this user request again and see where we stand at moment.

**Comment by Andrew-Lahikainen** [comment]
This has been completed and deployed.
