### ISSUE TITLE
[26805] Ability to change wording in "New Ticket" subheader in Client Portal 

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#634]
Cust wants to use this section to briefly discuss what the request type categories are, so tickets are raised correctly using the right request types

![preview](https://user-images.githubusercontent.com/13637718/140844633-9e0b5ecd-aa6b-4841-ad3d-c18a8f2aee3e.jpeg)

**Comment by Nness** [comment]
@iskolares feel free to discuss this with Warwick. Let's settle down a phrase for our interface then I will change. no need option.

If we get into a place we need to allow edit every line of text of our interface. Something definitely went wrong.
