### ISSUE TITLE
[26808] Customise the name of the 'Something else' request

### ISSUE THREAD

**Issue by beverleyh473** [DeskDirector/UserVoice#635]
We were hoping to change it to something like ‘Can’t find what you are looking for?’ or ‘I can’t see a form for my problem?’

Something along those lines, we’ve had a few clients still call in because they think they must find a form which matches their exact problem, and they don’t instinctually click on something else.

**Comment by Nness** [comment]
Same as the other user voice Edcel raised.. #634  .. @iskolares could you discuss this with Warwick. We need some kind of process on those. 

1. Are there better way of calling it. If there is go with that. (We can also have a vote that can allow customer to participate. then settle down with one)
2. Something else is a short cut, if they don't like, we have option to turn off. We don't want to have option to change name. Feel free to create a request type and use sort order to achieve same thing.

In general, I would like to avoid naming configuration as much as possible. so  Declined.
