### ISSUE TITLE
Move the tooltip under the Contact Search textbox so it doesn't block search results

### ISSUE THREAD

**Issue by Spacetornado** [DeskDirector/UserVoice#637]
![DeskDirectorContactSearchFeatureRequest](https://user-images.githubusercontent.com/10275386/143151939-6396d1b9-87f1-4497-9820-9540d261fa7a.png)

When you search for a Contact a large tooltip shows up directly underneath the search results, blocking the first couple results (which are usually the desired contacts). You have to press Enter or click away from the tooltip to dismiss it. It may seem like a minor issue but it adds up when setting up many contacts at once. It could be moved off to the right, or a preference added to not view it (as it's not needed once you've read it a few times).

(I looked for a similar issue but couldn't find one. Apologies if there is one and I couldn't find it).

**Comment by Nness** [comment]
Until we find alternative way, this is most efficient way of teach user how to use full text search. We normally get few support tickets every week, since this aggressive approach, we don't have anyone come back ask how to search any more.

One way of get around is to introduce an local config to let you click away. Then for that browser, it shouldn't popup that for you any more, until you switch to a different device or browser.

**Comment by Spacetornado** [comment]
Hi Nness,

Thanks for the quick reply. Just a couple quick ideas that might be a good compromise:

1. The popup could be moved to the right. Even if it was just 250 pixels to the right, the first couple search results would be visible. (If concerned about low resolution desktops, moving it 250px to the right would make the whole screen 1300px width, which is slightly higher than the common 1280px screen width. This could maybe be fixed by reducing the width and increasing the height of the popup. Also, it doesn't seem like "Press enter to search" is required anymore, as the system searches automatically with every keystroke).
2. Have the system check the age of the user's account and/or the number if times they've searched. If the account is 3+ months old or has used the search feature 10+ times, don't display it for them. 

Again, it's just a very minor issue, but one that adds up when you're looking up or setting up many users at once.

**Comment by Nness** [comment]
Sure.. I will see if there are any simple way I can get around. Thanks for those ideas.

**Comment by Nness** [comment]
There is setting under preference to disable tooltip of your current browser.
