### ISSUE TITLE
Add support for tagging workflows

### ISSUE THREAD

**Issue by chunghakngor** [DeskDirector/UserVoice#639]
Adding support for tagging workflows provides a way to categorize and filter different workflow. This becomes a problem when there are many different workflows. Currently, there is no way to categorize except to prefix the workflow name and use the search feature. 

For example: If there is a set of workflows for a digest automation that contains 10 different workflows and there are also other workflows. Without the use of tags, it would be hard to identify all of them without using the prefix naming and search.  With the use of tags, we can tag the workflows with a `digest` tag and filter for the `digest` tag, allowing us to only see the digest related workflows

**Comment by DDAndyChen** [comment]
The next DD release will include the api update to support setting maximum of 10 tags to a workflow.

**Comment by DDAndyChen** [comment]
@Nness the backend change is done.

**Comment by Nness** [comment]
This should be included in next admin release. It is now available under staging.
