### ISSUE TITLE
[10618] DD Tech: Clear All Filters / Visibility on Current Filters

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#64]
Having the Company / Board filters on DD Tech's ticket page visually indicate (highlight) if they are enabled.
Having an option available on the tickets page to clear all filters/reset filters to default.

**Comment by Nness** [comment]
Ticket list will be re-look at, how filter been displayed or configured will change base on new design. We will keep usability in mind.

**Comment by Nness** [comment]
Ticket list redesign has started.

**Comment by Andrew-Lahikainen** [comment]
This has been completed and deployed.
