### ISSUE TITLE
Ticketless chat module greyed out instead of completely removed outside of business hours.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#643]
With the release of Portal v3.26 the following improvement was put in place:

_Improved office hours behaviour. Chat no longer allowed if out of office hours. This apply to pre-ticket chat or ticket chat._

From a user experience perspective, I think it would be good to have the module visible to the end user but greyed out. Maybe something like:

![image](https://user-images.githubusercontent.com/30588784/150448084-a7aea015-1a27-4552-9c7b-c0c2554587d1.png)

This supported by an on-hover message that "Chat is disabled outside of standard business hours" or an on-screen indication for when chat services are next available.

**Comment by Nness** [comment]
This has been adjusted. Option will always show but disabled based on out of business hours.
