### ISSUE TITLE
[38697] Bypass login option selection if only one login option is enabled

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#645]
Currently, even if there's only one login option enabled, users are still asked which login option to choose 

Sample screenshot of an instance where only mail login token is enabled (OAuth and password login not enabled)
![Screen Shot 2022-02-10 at 12 18 09 PM](https://user-images.githubusercontent.com/13637718/153306835-c82a2652-b9d4-42b8-b8bf-ef3398662879.png)

If possible, it's best to bypass this page if only one one login option is enabled

**Comment by Aycorn** [comment]
Similar request: **[40304] Update verbiage / button for E-Mail Token Screen**

**Comment by DevanMorrison** [comment]
Going straight to one login I feel would be a nice UX to just enter the email & await the code being sent to the applicable e-mail address. However, at minimum if the wording could be updated that the "Sign in using email token" is a button, that'd help. We've had numerous users say they aren't getting tokens on calls only to discover they weren't clicking the button. To those of us in DD daily it seems obvious but for newly onboarded clients this adds a small bit of frustration to the UX.

**Comment by appwjen** [comment]
Similar request: **[41098] General Feedback**

**Comment by Nness** [comment]
This has been resolved in latest login page release. It will take time to be available for all sites. (within next 5 hours or so)

If  user only has one platform and one method, they will directly go to that method. same as if they only have one method under a platform, then it will navigate to that method right away.
