### ISSUE TITLE
[10613] DD Tech: Mobile friendly settings page.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#65]
As per screenshot below - settings page is hidden by DD Tech scaling on smaller resolutions.

![screenshot_20180628-151836](https://user-images.githubusercontent.com/30588784/42011311-010bbaa6-7ae7-11e8-90d8-cfedf15ac52d.png)

**Comment by Nness** [comment]
Sorry at this stage tech is not designed for mobile.

**Comment by Nness** [comment]
Current TECH will never be responsive for mobile device, but if you expect an Mobile friendly TECH, you can vote on #68
