### ISSUE TITLE
Add ticket ID filter input for Workflow run history

### ISSUE THREAD

**Issue by keison-tang** [DeskDirector/UserVoice#652]
Add a ticket ID filter input for ticket event workflows, similar to email history.

Current workaround is to click on the bottom link of any row (e.g "1162 something else test") to add the filter and then change the url query parameter to a specific ticket number.

![image](https://user-images.githubusercontent.com/20856129/157547880-cc3e7e54-e2bb-4c7e-a93d-fd822305b639.png)

**Comment by Aycorn** [comment]
Closing - this is available.

![image](https://github.com/user-attachments/assets/852867e8-59b1-46f7-889e-eeba3bc2dc70)
