### ISSUE TITLE
[40266] Reinstate "Feature Preview" or a way to preview a new UI before rollout

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#662]
Old releases for the client portal can be gradually deployed via the "[Feature Preview](https://help.deskdirector.com/article/se69haxuxq-how-to-roll-out-a-new-portal-features-and-ui-designs)" section in the admin console before.

Over the past few major releases/updates to the client portal, this was not used anymore, and any changes were deployed right away. While this makes sure that everybody is using the new UI, it makes it harder for some companies to train/onboard their clients.

Some reasons could be:
- they have specific documentation built on the old UI, and a sudden UI change will deem the documentation invalid
- they have just onboarded and trained a new client, then a major UI change is deployed

**Comment by Nness** [comment]
We have no intention to introduce that any more. No one will use that to roll out. We did announce UI change on early Feb, and said we will release by end of Feb.

At end, the actual release date was on end of March.

Even then, customer is still not aware of such release. Why will feature preview help? The announcement is on home page of admin portal, above the feature release section.

**Comment by Nness** [comment]
To be clear.

1. At later Jan, we introduced UI switch inside client portal to introduce new interface, then customer come to ask us to remove it. And saying put in home page, so they have time to create introduction. So, a common practice to introduce new interface in app failed.
2. Feb we announce in home page and give 2 month, still have people not aware of it. 
3. In the past we introduce feature preview, it took 3 years, still many people not aware of it.

**Comment by avilarma** [comment]
> To be clear.
> 
> 1. At later Jan, we introduced UI switch inside client portal to introduce new interface, then customer come to ask us to remove it. And saying put in home page, so they have time to create introduction. So, a common practice to introduce new interface in app failed.
> 2. Feb we announce in home page and give 2 month, still have people not aware of it.
> 3. In the past we introduce feature preview, it took 3 years, still many people not aware of it.

We are not pending all the time about announcements. If we had the "Feature Preview" option, we know we can go there and check and, that way, we have some control about new releases. It is frustrating create documentation and onboardings and shortly after see that with no control on our end the layout changes. 

I suggest to use Feature Preview for any changes affecting Client Portal and user interface.

**Comment by Nness** [comment]
We already had feature preview in recent client portal UI change.

1. We had preview button in client portal for a week in Jan. Where in request support page you can click to see new home page. 
2. After we disabled preview button, we created announcement on admin portal home page and announce we will release the UI by end of Feb and urge customer to write document. Where we released on end of Mar. There was two month gap.


It doesn't matter we have feature preview option, or announcement or in app preview, there will always have customer won't be able to catch the change announcement. 

That is the reality. As going forward, we will announce on home page on any addition and change, and give time for you to prepare. But we will not introduce a page without give an deadline.

So as for your request.

- Do we have preview? Yes we do, and we already did. We have given 2 months for customer to prepare.
- Will we given our preview on client portal in the future? Yes we will, we may give longer time and make the announcement more obvious.
- What should customer be aware of? Check admin portal's home page once 2 weeks to see all the new release and announcement. Include deprecation. We will keep them updated

**Comment by Nness** [comment]
- [8th of Feb we announced home page release](https://github.com/DeskDirector/docs/commit/ef9d34dd579802d9ebeb7ef3f0dc693885969cb4)
- [2nd of Feb, we released home page with preview button on request support page](https://github.com/DeskDirector/docs/commit/54aa55e1925cb7b4dc24c38869c8d36604d74d3e)
- [21st of Mar, we released home page](https://github.com/DeskDirector/docs/commit/7e831571309625a51bad483223d8f95aed6df935)
