### ISSUE TITLE
[40302] Add "inline form" option/action for DD Flow Connector

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/UserVoice#664]
Currently, there is no option to add an inline form using the "Update a Ticket" action, or a separate action for the DD Flow Connector

**Comment by Aycorn** [comment]
The `run an advanced action` action now supports `add an inline form to ticket`

![image](https://github.com/user-attachments/assets/e819ba54-8068-4669-9c2b-9af79c8d19ed)
