### ISSUE TITLE
Improve the "Create Time Entry" button by showing status

### ISSUE THREAD

**Issue by JonPagoda** [DeskDirector/UserVoice#665]
I like the Create time entry button's pull down to set status by creating time entry a lot.  I can accomplish two things at once.
I often find myself wondering what the status currently is.  If I don't need to change it I can just click the button.  I know the status is on the right pane.  But often I need to scroll the right pane to see the ticket status.  
For me it would reduce friction when adding time to a ticket if the current status was displayed just below that button - or in the button.

**Comment by Nness** [comment]
Please submit through support.
