### ISSUE TITLE
Form Data Extraction+ Tag Sender

### ISSUE THREAD

**Issue by NetFusionDesigns** [DeskDirector/UserVoice#672]
In some cases we have forms specific for customers.

Example: Customer Onboarding

In some cases, if a specific field type is selected on the form ( maybe a drop down), for do they need access to Salesforce - if Yes is selected, we should have the ability to copy a individual on the request and send them data from specific fields we collect

**Comment by Nness** [comment]
Please describe your requirement through support, then they will help you log user voice here. We will close anything that didn't go through support first.
