### ISSUE TITLE
TECH Web APP for Mobile

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#68]
For anyone who expect current TECH to be responsive on mobile, the bad news is the responsive trendy is already in the past. It's impossible to make single app to look good on mobile and on desktop but still maintain performance and usability.

That's the reason why some of top site now have mobile specific version of website. e.g. wikipedia

**Comment by FluidNets-DamianS** [comment]
That kind of goes against what I was told about DD inbox and IT now!  I was told both apps are dead as the new user interface is responsive.  Regardless I hate most mobile apps.  I like to get information from my mobile device but do not have the patience or agility to update stuff from it.  However, with the new "Chat" functionality my bigger concern is that we need something to make new chats stand out and signal a persistent alert.  Once example being Tawk.To which I use for one of my businesses.  When a customer initiates a chat request I have an APP on my PC and phone that ring for me to answer (similar to a phone call).  The first time a customer tries to use chat and does not get a response it becomes "garbage" in their eyes.  

I only tried to access TECH from my phone to see if my mobile chrome will alert me of a chat alert.  While I like the notification options in Tech/Portal and the reduction of email alerts they encourage - chat needs to have the same importance as a phone call and there needs to be a mechanism to get the operators attention in a more persistent manner.  I employ 20+ guys but rarely is someone just sitting in front of their desks and when they are they are providing remote support.  A chat alert needs to be more pronounced and signal an alert on their desktops, laptops and mobile devices.

**Comment by dr3dgen** [comment]
@Nness What is the ETA on webhooks for chat events? I'm assuming we could use it with Slack? Our early adopters are also running into an issue where chat requests can be missed via mobile, which is encouraging more walk-ups/phone calls.

Honestly, in my opinion, a stand-alone chat app that pings for new chat requests, tickets assigned to technician logged in, and selected board updates, would be a great add-on.

**Comment by Aycorn** [comment]
The Tech Portal has received a lot of updates since this was first flagged in 2018, and in the current state, has a user friendly web interface:

![image](https://github.com/user-attachments/assets/589a531d-5844-4b3a-ba69-b96284f05c24)

I believe this can be closed as a dedicated installable application for iOS and Android devices will not be developed.
