### ISSUE TITLE
[46828] Symbol Support for "PortalName": in v5

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#687]
Symbols like & are not supported as the DD Portal v5 "PortalName"

![image](https://user-images.githubusercontent.com/30588784/201756550-afa1442f-453d-40a1-a6d4-50e2148485b4.png)

![image](https://user-images.githubusercontent.com/30588784/201756595-19053360-fb9b-4da8-8360-2069ff8244f3.png)

**Comment by Nness** [comment]
This has been fixed in release of `5.0.16`
