### ISSUE TITLE
DD Tech: Chat to new ticket

### ISSUE THREAD

**Issue by FluidNets-DamianS** [DeskDirector/UserVoice#69]
Since user bob@company.com logged in and started chatting we know who Bob is and what company he works for.  When converting a chat to a ticket should company and contact be pre-populated (yet changeable)?

**Comment by Nness** [comment]
To confirm, this is for ticketless chat. When ticketless chat is finished and process to convert it to ticket, tech should populate company and contact automatically. Is this correct?

**Comment by FluidNets-DamianS** [comment]
That is correct.  Obviously we should be able to change company/contact but we should default to the person chatting with us.

**Comment by Andrew-Lahikainen** [comment]
I'm going to close this for now because Portal is going to be creating a ticket with a pre-ticket chat which will populate that data.
