### ISSUE TITLE
[47754] Email Delivery Accounts: Notifications on account failures/errors

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#694]
Example is an Office 365 delivery account that could not refresh it's token and required consent to be re-granted:

![image](https://user-images.githubusercontent.com/30588784/206037928-dd810333-5777-4d69-986f-e45266c3f4ee.png)

Suggestion in these scenarios that a notification is sent to inform Master Admins or a list of configurable recipients of this failure.

Without logging into DD Admin Console and checking your delivery history, you would not know whether these failures were occuring.

**Comment by Nness** [comment]
This has been implemented and will be released after holiday.
