### ISSUE TITLE
[528220] Custom variable in default brand package overrides custom package 

### ISSUE THREAD

**Issue by Olivia-Lancom** [DeskDirector/UserVoice#720]
In the scenario where a color is specified under the "Advanced Theme" section of the default brand package, it will override the custom brand package if the same field in the custom package does not have a color specified. 

---

To clarify, the override is per custom variable field override, but custom variables as whole override. For example if there are 20 custom variables we can define, if we defined nothing, it will inherit from global, as long as we define one, it will use current setup.

**Comment by Nness** [comment]
In server `19.86.2` we have changed logic.

- In UI, if custom brand use custom theme, then it will not inherit custom variable from global
- In UI, if custom brand is use default theme, which means theme is defined at global level, then custom variables will be inherit from global, unless specified any at custom level.
