### ISSUE TITLE
#533630 | Dark Mode Preview for Email Templates

### ISSUE THREAD

**Issue by Olivia-Lancom** [DeskDirector/UserVoice#722]
Admin portal > Email tab > Custom template > Select template > Preview tab

Feature request to add Dark Mode Preview in addition to light mode

**Comment by Nness** [comment]
There is no light or dark mode for email, the colour choice is depends on email receiver application. Such as outlook. They decide the conversion and automatically calculate.

**Comment by Nness** [comment]
To clarify the decision on this, each email application, such as iPhone mail, outlook, thunderbird, every application has its own dark mode conversion on incoming emails. The dark theme for any email is not specified by sender, but by **auto calculated** at receiver end.

Thus, the sender has no way to tell or guarantee how it will look at receiver end.

- It depends on the receiver application
- It depends on the version of the receiver application

Even if we could reverse engineer one application for one specific time and its version, it will be out dated within a day or two. Unless receiver application has a contract documentation says here is our conversion logic and we will not change for next 6 ~ 12 months. Else the effort is worthless. Which means we are chasing a ever changing target.
