### ISSUE TITLE
[10703] Sign in with Microsoft for Desktop DD Portal

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#73]
The below feature is currently only available for the Web Portal.
Request to have this feature also available on DD Portal for Windows.

![2018-07-06 13_42_08-support portal](https://user-images.githubusercontent.com/30588784/42355712-95cf5bd4-8122-11e8-8753-22f614446904.png)

**Comment by Andrew-Lahikainen** [comment]
Shipped a few months ago
