### ISSUE TITLE
[568510] Feature request - Dynamic Field Object Access After Form Submission

### ISSUE THREAD

**Issue by gcao417** [DeskDirector/UserVoice#737]
Customer has requested to have access to the dynamic field object after submitting a form. 

Customer request: 

> I’ve been playing around with the dynamic form fields and really love the functionality, however, I noticed that after form submission, the dynamic field objects aren’t saved in the form results, only a string of the selected value.
>
> I think it would be really beneficial if the name and identifier of a dynamic field result could be passed through to the form result so both values can be used after form submission.
> 
> After a bit of digging around, I found that the data I need is being sent as a payload to the /api/v2/contact/tickets/create/form endpoint, but doesn’t back out the other side in the form results.
>
> Having this information be returned in the form results would mean I don’t need to repeat the calls to ConnectWise if I need the company id for example.

Example case: 

> My example use case is submitting a ConnectWise Opportunity after form submission. I have a dynamic field in my form that receives the company names and id numbers from ConnectWise, I would then like to run a Power Automate work after form submission, pick out the id of the company and create an opportunity against that company.
> 
> Currently I just receive the name of the selected company from my form and not the id that I originally passed in to the dynamic field.

**Comment by Nness** [comment]
It is already the case.
