### ISSUE TITLE
[10705] Notifications for new Quotes/Invoices

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#75]
Have to ability to enable notifications when a new invoice or quote is available for a client similar to the current notification systems within Desk Director.

**Comment by Nness** [comment]
Quotes and Invoices often have integration associate with them. Also email is preferred option than our notification system.

From technical point of view, this is not our data, we have to sync all quotes and invoice to our database and do periodical comparison to figure out what has been changed to be able to perform notifications.

For now this is not part of roadmap, I will close and reject this request.
