### ISSUE TITLE
[19251, 8916, 10550, 10554, 13580, 13656, 13791, 13941, 14095, 21467, 21483, 22085, 23445, 25136, 25494] Control portal's colour choice with CSS variable

### ISSUE THREAD

**Issue by Nness** [DeskDirector/UserVoice#77]
Deprecate the colour selection option inside admin console and use CSS variable to change colour.

We can expose a list of colours that customer can change, include background color, font colour. We will use CSS variable to allow that to happen and not use material UI's palette

**Comment by AirLHull** [comment]
We have a major demand for this. We have recently gone through some changes that require specific colors to be made available into the DD Desktop App (As it will match the changes). Not just for us but for everyone, i am sure they would prefer a large pallet / a way to manually enter in RGB codes etc to get the shade they want.

**Comment by froader** [comment]
Voicing my vote for the ability to properly brand the DD portals with colors based on RGB or codes. Thanks!!

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #13580 - Branding Options - Login Page - More Logo / Style Controls

**Comment by FluidNets-DamianS** [comment]
We just partnered with ScreenSteps.com for our internal and external documentation & KB platform.  DD should implement customization similar to this.  They have extensive options built in for color, layout, etc.  In addition if you are skilled in CSS everything is completely customizable.

**Comment by Nness** [comment]
We are using Angularjs material. Theme was natively supported by angularjs material. It is plus also minus. 

1. It need to be compiled before user access the page. Live change theme require refresh whole web app
2. Color theme is pre-defined. Even though they support custom theme, it is not as flexible as CSS override. 
3. It is not compatible with other framework.

Personally, I prefer a set of pre-defined scheme. Similar to slack, it is not color combination but pre-defined. It prioritize on readability and color contrast. On top of that we can provide CSS override. 

Such modification require a lengthy refactor. We have to wait on correct time to get this started.

**Comment by Aycorn** [comment]
Similar Reuqest: 
Service Ticket #13791 - Can I change the background color for the web login, as well as the color of the app when it...

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #14095 - Custom colors for portal

**Comment by Andrew-Lahikainen** [comment]
We might be able to do this with angularjs material. It seems to support dynamic themes at runtime (after config block).

We'll take a look at this approach when we implement this: https://github.com/DeskDirector/UserVoice/issues/125

**Comment by prysmcorp** [comment]
Happy to see an update on this. Does this look feasible in allowing us to set custom CSS hex colors?

**Comment by Nness** [comment]
For this topic, I would like to announce, as going forward theme will be limited to navigation bar only.

Portal: Navigation bar is themed, with capability to set font color and background color.

Login screen: We will introduce a limited space for theme color, everything else is either light or dark theme. 

All buttons will be consistent color. Theme cannot alter the button color.
* Primary button: Blue, Navy or Green, haven't decided.
* Secondary button: Gray
* Danger: Red
* Warning: Yellow

The goal is to improve color contrast, improve meaning of color. Avoid red to be used as primary button, or green used as warning color. Button's color code have to be static.

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #23386 - Help Desk Colors

**Comment by iskolares** [comment]
Similar request DD Ticket # 25136

**Comment by iskolares** [comment]
Similar request Ticket # 25494

**Comment by Nness** [comment]
This has been released on 31st of May 2021.
