### ISSUE TITLE
Chat : What is the status of the country code issue?

### ISSUE THREAD

**Issue by FluidNets-DamianS** [DeskDirector/UserVoice#83]
I noticed via the DDportal app the country code correctly defaults of +1 US.  However via the web interface it still defaults to +64 New Zealand.

**Comment by Nness** [comment]
This is bug not feature request. Please log through support.

**Comment by Nness** [comment]
This is not logged under issues board. [19](https://github.com/DeskDirector/Issues/issues/19)
