### ISSUE TITLE
[10812] URL Linking for ReOpen dialogue box.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#84]
Referencing article: https://deskdirector.zendesk.com/hc/en-us/articles/211272283-URL-Linking-in-DeskDirector

Including the ability to link directly to the "ReOpen Ticket' button within DD Portal.

![image](https://user-images.githubusercontent.com/30588784/42739152-a0910b60-88e5-11e8-84f7-ac32036b4ee7.png)

![image](https://user-images.githubusercontent.com/30588784/42739153-a4c433ba-88e5-11e8-9d81-f22c36945c8e.png)

**Comment by Nness** [comment]
We need scenario of why we need this feature. What's the problem we try to solve before this will be considered.

**Comment by FluidNets-DamianS** [comment]
Over 50% of our users love to reply with a "Thanks!" after we close their ticket.  This often tanks our SLA numbers for no legitimate reason and causes more work for our techs.  When we send out the final closed ticket notification I would like to provide a button to "reopen ticket".  That way if a user replies to a closed ticket we will not re-open automatically.

**Comment by AirLHull** [comment]
I fully agree Damian, this is a very common occurrence for us too! Not only does it effect the SLA but also it can effect our overall stats for the day / week.

**Comment by FluidNets-DamianS** [comment]
As I was thinking about it, most of our clients rely on email in their back and forth.  The goal with using DDportal is to get them into the portal.  Ideally it would be nice to utilize a URL string to activate any of the ticket action items:

FastTrack, Flag, Close, etc... with the result being the same as if they clicked the button in the portal.  That way when then click the button they are taken to the portal and have to provide the needed input.  The key is that we are encouraging them to get into the portal.

**Comment by Nness** [comment]
@FluidNets-DamianS , The use case on this is when they receive email, inside email have several actions they can perform, each action will allow navigate to portal. That's the use case right?

**Comment by FluidNets-DamianS** [comment]
@Nness , that is correct.  The goal would be to augment our email notifications with buttons to initiate actions based on the current ticket status.  Ex. On a closed ticket notification we would have a button to link to the re-open function.  On an new ticket I may want to add the "FastTrack" button.  On other tickets include the Flag, Close or Initiate Chat buttons.
I am looking for ways to show the benefit of what is in the portal and to connect users to those benefits.  This essentially trains users to "go to the portal" when they want to trigger an action.

**Comment by FluidNets-DamianS** [comment]
And is most of this already implemented with the link #62 ?  Although I was not able to get it to work...
https://deskdirector.zendesk.com/hc/en-us/articles/212254426-URL-Linking-in-DD-Portal

**Comment by Nness** [comment]
@FluidNets-DamianS , Anything listed inside [this article](https://deskdirector.zendesk.com/hc/en-us/articles/212254426-URL-Linking-in-DD-Portal) is suppose to be functional.

If any of them not working, you can contact support. If support able to reproduce and confirmed with us, we will try to resolve that as soon as possible. Since this is one of main functionality we have.

I can see there are already covered some of action you asked for.

**Comment by chris-ls** [comment]
Deep linking to re-open a ticket is supported.
You can read more about deep linking [here](https://help.deskdirector.com/article/rb70qsabfd-portal-deep-linking).

The current behavior of the 'reopen' action is *not* to automatically re-open the ticket, but to automatically open the dialog where the user can then confirm this action, leaving a note if desired.
