### ISSUE TITLE
[10823, 20197, 21771] Custom URL with Custom Branding

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#88]
Ability to have Custom URLs load into a login page without the global brand.

If branding is set at a customer level, even with a Custom URL there is no way for DD Portal to detect the customer.

![image](https://user-images.githubusercontent.com/30588784/42849968-a9c1a47a-8a79-11e8-8e98-0f99cd737a2a.png)

**Comment by Nness** [comment]
One of possibility could be domain matching with brand. That way we can leverage custom domain's power.

Other solution could be specific path. e.g. `support.deskdirector.com/portal/v2/{company}/login`. or query parameter.

**Comment by dkbrookie** [comment]
Really, really need this! Please add!!

**Comment by noahbalboah** [comment]
Yes please.

**Comment by mheld79** [comment]
Yes please, this would be a major win!

**Comment by Aycorn** [comment]
Similar Request: Service Ticket #21771 - Custom Domain

**Comment by gcaparulo** [comment]
another vote for this.

**Comment by Nness** [comment]
This implementation is related to DeskDirector/DeskDirector#904 and DeskDirector/admin-console#4

- [x] admin API to setup
- [x] portal brand API respect setting
- [x] portal logo and icon link respect setting
- [x] some of email template respect setting.
- [ ] admin setting page

This is still in early test phase, if it introduce huge debt for future development, we may pull out. If nothing goes wrong, I should be able to confirm of release later this week.

Admin setting page will came few weeks after.

**Comment by Aycorn** [comment]
I believe this is now available using Custom Branding and [Host Configurations](https://help.deskdirector.com/article/zt0szqwp35-hosts-configuration)

Marking as closed.
