### ISSUE TITLE
[10840 , 10873] DD Mac Installer - Menu Bar Icons instead of Dock.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/UserVoice#89]
Functionality added to have the Mac installer show on the Menu bar (top of screen by time) rather than the Dock.

![image](https://user-images.githubusercontent.com/30588784/42856456-7a740d28-8a99-11e8-87d2-6ba991ba351e.png)

**Comment by Nness** [comment]
This has been implemented and will be released with desktop portal version 4.3. 

It is released for AU today and EU, CA, US next Wed.
