### ISSUE TITLE
Portal Client: Tray Icon display always by default

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#97]
Would be nice for the client to display it's tray icon automatically by default.  If the users chooses to hide it, fine.

**Comment by Nness** [comment]
Microsoft didn't provide anyway to do it.
https://blogs.msdn.microsoft.com/oldnewthing/20101215-00/?p=12003/

There is hacky way by modify registry.
http://forums.codeguru.com/showthread.php?306661-How-to-always-show-an-icon-in-system-tray

I don't think this is something we want to get into.
