### ISSUE TITLE
Email Templates - Use natural case instead of all caps

### ISSUE THREAD

**Issue by PreciseNZ** [DeskDirector/UserVoice#99]
We have configured custom SMTP settings (with relevant SPF records) for the token emails, but we still find that these emails are getting caught in our clients spam filters.

Most spam scores are affected by subject lines in all uppercase.

Can I please request that a change be made to the token emails to use natural case for the subject line?

**Comment by Nness** [comment]
This is now converted to [issue](https://github.com/DeskDirector/Issues/issues/25)
